// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: trend.proto

package trend

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrendService_CreateTrend_FullMethodName              = "/trend.TrendService/CreateTrend"
	TrendService_DeleteTrend_FullMethodName              = "/trend.TrendService/DeleteTrend"
	TrendService_UpdateTrend_FullMethodName              = "/trend.TrendService/UpdateTrend"
	TrendService_ListTrends_FullMethodName               = "/trend.TrendService/ListTrends"
	TrendService_GetTrendDetail_FullMethodName           = "/trend.TrendService/GetTrendDetail"
	TrendService_GetLatestTrends_FullMethodName          = "/trend.TrendService/GetLatestTrends"
	TrendService_GetUserTrends_FullMethodName            = "/trend.TrendService/GetUserTrends"
	TrendService_GetUserTopTrend_FullMethodName          = "/trend.TrendService/GetUserTopTrend"
	TrendService_CreateRootDiscuss_FullMethodName        = "/trend.TrendService/CreateRootDiscuss"
	TrendService_CreateChildDiscuss_FullMethodName       = "/trend.TrendService/CreateChildDiscuss"
	TrendService_GetTrendDiscusses_FullMethodName        = "/trend.TrendService/GetTrendDiscusses"
	TrendService_GetRootDiscusses_FullMethodName         = "/trend.TrendService/GetRootDiscusses"
	TrendService_GetChildDiscusses_FullMethodName        = "/trend.TrendService/GetChildDiscusses"
	TrendService_DeleteDiscuss_FullMethodName            = "/trend.TrendService/DeleteDiscuss"
	TrendService_GetUnreadReplies_FullMethodName         = "/trend.TrendService/GetUnreadReplies"
	TrendService_MarkDiscussRead_FullMethodName          = "/trend.TrendService/MarkDiscussRead"
	TrendService_ToggleLike_FullMethodName               = "/trend.TrendService/ToggleLike"
	TrendService_GetTrendLikeSummary_FullMethodName      = "/trend.TrendService/GetTrendLikeSummary"
	TrendService_BatchGetTrendLikeSummary_FullMethodName = "/trend.TrendService/BatchGetTrendLikeSummary"
	TrendService_GetLikedUsers_FullMethodName            = "/trend.TrendService/GetLikedUsers"
	TrendService_GetUnreadLikes_FullMethodName           = "/trend.TrendService/GetUnreadLikes"
	TrendService_MarkLikesRead_FullMethodName            = "/trend.TrendService/MarkLikesRead"
	TrendService_SaveTrendDraft_FullMethodName           = "/trend.TrendService/SaveTrendDraft"
	TrendService_GetTrendDraft_FullMethodName            = "/trend.TrendService/GetTrendDraft"
	TrendService_DeleteTrendDraft_FullMethodName         = "/trend.TrendService/DeleteTrendDraft"
)

// TrendServiceClient is the client API for TrendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 动态服务接口定义
type TrendServiceClient interface {
	// 发布动态
	CreateTrend(ctx context.Context, in *CreateTrendRequest, opts ...grpc.CallOption) (*CreateTrendResponse, error)
	// 删除动态
	DeleteTrend(ctx context.Context, in *DeleteTrendRequest, opts ...grpc.CallOption) (*DeleteTrendResponse, error)
	// 获取最新动态,设置置顶，设置评论区，访问范围
	UpdateTrend(ctx context.Context, in *UpdateTrendRequest, opts ...grpc.CallOption) (*UpdateTrendResponse, error)
	// 获取动态列表
	ListTrends(ctx context.Context, in *ListTrendsRequest, opts ...grpc.CallOption) (*ListTrendsResponse, error)
	// 获取单个动态详情
	GetTrendDetail(ctx context.Context, in *GetTrendDetailRequest, opts ...grpc.CallOption) (*GetTrendDetailResponse, error)
	// 获取最新动态,设置置顶，设置评论区，访问范围
	GetLatestTrends(ctx context.Context, in *GetLatestTrendsRequest, opts ...grpc.CallOption) (*GetLatestTrendsResponse, error)
	// 获取用户个人动态列表
	GetUserTrends(ctx context.Context, in *GetUserTrendsRequest, opts ...grpc.CallOption) (*GetUserTrendsResponse, error)
	// 获取用户动态置顶
	GetUserTopTrend(ctx context.Context, in *GetUserTopTrendsRequest, opts ...grpc.CallOption) (*GetUserTrendsResponse, error)
	// 评论服务定义
	// 动态评论相关模块
	// 1. 发表一级评论（父评论ID=0）
	CreateRootDiscuss(ctx context.Context, in *CreateDiscussReq, opts ...grpc.CallOption) (*CreateDiscussResp, error)
	// 2. 发表多级评论（二级、三级等）
	CreateChildDiscuss(ctx context.Context, in *CreateDiscussReq, opts ...grpc.CallOption) (*CreateDiscussResp, error)
	// 3. 获取动态的多级评论树（树形结构）
	GetTrendDiscusses(ctx context.Context, in *GetDiscussesListReq, opts ...grpc.CallOption) (*GetDiscussesListResp, error)
	// 4. 获取一级评论（分页）
	GetRootDiscusses(ctx context.Context, in *GetDiscussesReq, opts ...grpc.CallOption) (*DiscussesListResp, error)
	// 5. 获取子评论（指定父评论下的所有评论）
	GetChildDiscusses(ctx context.Context, in *GetChildDiscussesReq, opts ...grpc.CallOption) (*DiscussesListResp, error)
	// 6. 删除评论（支持任意级别评论删除）
	DeleteDiscuss(ctx context.Context, in *DeleteDiscussReq, opts ...grpc.CallOption) (*DeleteDiscussResp, error)
	// 7. 获取未读回复
	GetUnreadReplies(ctx context.Context, in *GetUnreadRepliesReq, opts ...grpc.CallOption) (*RepliesListResp, error)
	// 8. 标记评论为已读
	MarkDiscussRead(ctx context.Context, in *MarkDiscussRequest, opts ...grpc.CallOption) (*MarkDiscussResponse, error)
	// 点赞/取消点赞
	ToggleLike(ctx context.Context, in *LikeToggleRequest, opts ...grpc.CallOption) (*LikeToggleResponse, error)
	// 获取动态点赞摘要 (用于动态下方展示)
	GetTrendLikeSummary(ctx context.Context, in *GetTrendLikeSummaryRequest, opts ...grpc.CallOption) (*GetTrendLikeSummaryResponse, error)
	// 批量获取点赞摘要 (用于动态流)
	BatchGetTrendLikeSummary(ctx context.Context, in *BatchTrendLikeSummaryRequest, opts ...grpc.CallOption) (*BatchTrendLikeSummaryResponse, error)
	// 获取点赞用户列表 (微信"查看全部点赞")
	GetLikedUsers(ctx context.Context, in *GetLikedUsersRequest, opts ...grpc.CallOption) (*GetLikedUsersResponse, error)
	// 获取未读点赞通知
	GetUnreadLikes(ctx context.Context, in *GetUnreadLikesRequest, opts ...grpc.CallOption) (*GetUnreadLikesResponse, error)
	// 标记点赞为已读
	MarkLikesRead(ctx context.Context, in *MarkLikesReadRequest, opts ...grpc.CallOption) (*MarkLikesReadResponse, error)
	// 保存动态草稿
	SaveTrendDraft(ctx context.Context, in *SaveTrendDraftRequest, opts ...grpc.CallOption) (*SaveTrendDraftResponse, error)
	// 获取动态草稿
	GetTrendDraft(ctx context.Context, in *GetTrendDraftRequest, opts ...grpc.CallOption) (*GetTrendDraftResponse, error)
	// 删除动态草稿
	DeleteTrendDraft(ctx context.Context, in *DeleteTrendDraftRequest, opts ...grpc.CallOption) (*DeleteTrendDraftResponse, error)
}

type trendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrendServiceClient(cc grpc.ClientConnInterface) TrendServiceClient {
	return &trendServiceClient{cc}
}

func (c *trendServiceClient) CreateTrend(ctx context.Context, in *CreateTrendRequest, opts ...grpc.CallOption) (*CreateTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTrendResponse)
	err := c.cc.Invoke(ctx, TrendService_CreateTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) DeleteTrend(ctx context.Context, in *DeleteTrendRequest, opts ...grpc.CallOption) (*DeleteTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTrendResponse)
	err := c.cc.Invoke(ctx, TrendService_DeleteTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) UpdateTrend(ctx context.Context, in *UpdateTrendRequest, opts ...grpc.CallOption) (*UpdateTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTrendResponse)
	err := c.cc.Invoke(ctx, TrendService_UpdateTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) ListTrends(ctx context.Context, in *ListTrendsRequest, opts ...grpc.CallOption) (*ListTrendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrendsResponse)
	err := c.cc.Invoke(ctx, TrendService_ListTrends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) GetTrendDetail(ctx context.Context, in *GetTrendDetailRequest, opts ...grpc.CallOption) (*GetTrendDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrendDetailResponse)
	err := c.cc.Invoke(ctx, TrendService_GetTrendDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) GetLatestTrends(ctx context.Context, in *GetLatestTrendsRequest, opts ...grpc.CallOption) (*GetLatestTrendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestTrendsResponse)
	err := c.cc.Invoke(ctx, TrendService_GetLatestTrends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) GetUserTrends(ctx context.Context, in *GetUserTrendsRequest, opts ...grpc.CallOption) (*GetUserTrendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTrendsResponse)
	err := c.cc.Invoke(ctx, TrendService_GetUserTrends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) GetUserTopTrend(ctx context.Context, in *GetUserTopTrendsRequest, opts ...grpc.CallOption) (*GetUserTrendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTrendsResponse)
	err := c.cc.Invoke(ctx, TrendService_GetUserTopTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) CreateRootDiscuss(ctx context.Context, in *CreateDiscussReq, opts ...grpc.CallOption) (*CreateDiscussResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDiscussResp)
	err := c.cc.Invoke(ctx, TrendService_CreateRootDiscuss_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) CreateChildDiscuss(ctx context.Context, in *CreateDiscussReq, opts ...grpc.CallOption) (*CreateDiscussResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDiscussResp)
	err := c.cc.Invoke(ctx, TrendService_CreateChildDiscuss_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) GetTrendDiscusses(ctx context.Context, in *GetDiscussesListReq, opts ...grpc.CallOption) (*GetDiscussesListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiscussesListResp)
	err := c.cc.Invoke(ctx, TrendService_GetTrendDiscusses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) GetRootDiscusses(ctx context.Context, in *GetDiscussesReq, opts ...grpc.CallOption) (*DiscussesListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscussesListResp)
	err := c.cc.Invoke(ctx, TrendService_GetRootDiscusses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) GetChildDiscusses(ctx context.Context, in *GetChildDiscussesReq, opts ...grpc.CallOption) (*DiscussesListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscussesListResp)
	err := c.cc.Invoke(ctx, TrendService_GetChildDiscusses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) DeleteDiscuss(ctx context.Context, in *DeleteDiscussReq, opts ...grpc.CallOption) (*DeleteDiscussResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDiscussResp)
	err := c.cc.Invoke(ctx, TrendService_DeleteDiscuss_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) GetUnreadReplies(ctx context.Context, in *GetUnreadRepliesReq, opts ...grpc.CallOption) (*RepliesListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepliesListResp)
	err := c.cc.Invoke(ctx, TrendService_GetUnreadReplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) MarkDiscussRead(ctx context.Context, in *MarkDiscussRequest, opts ...grpc.CallOption) (*MarkDiscussResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkDiscussResponse)
	err := c.cc.Invoke(ctx, TrendService_MarkDiscussRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) ToggleLike(ctx context.Context, in *LikeToggleRequest, opts ...grpc.CallOption) (*LikeToggleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeToggleResponse)
	err := c.cc.Invoke(ctx, TrendService_ToggleLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) GetTrendLikeSummary(ctx context.Context, in *GetTrendLikeSummaryRequest, opts ...grpc.CallOption) (*GetTrendLikeSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrendLikeSummaryResponse)
	err := c.cc.Invoke(ctx, TrendService_GetTrendLikeSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) BatchGetTrendLikeSummary(ctx context.Context, in *BatchTrendLikeSummaryRequest, opts ...grpc.CallOption) (*BatchTrendLikeSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchTrendLikeSummaryResponse)
	err := c.cc.Invoke(ctx, TrendService_BatchGetTrendLikeSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) GetLikedUsers(ctx context.Context, in *GetLikedUsersRequest, opts ...grpc.CallOption) (*GetLikedUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLikedUsersResponse)
	err := c.cc.Invoke(ctx, TrendService_GetLikedUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) GetUnreadLikes(ctx context.Context, in *GetUnreadLikesRequest, opts ...grpc.CallOption) (*GetUnreadLikesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnreadLikesResponse)
	err := c.cc.Invoke(ctx, TrendService_GetUnreadLikes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) MarkLikesRead(ctx context.Context, in *MarkLikesReadRequest, opts ...grpc.CallOption) (*MarkLikesReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkLikesReadResponse)
	err := c.cc.Invoke(ctx, TrendService_MarkLikesRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) SaveTrendDraft(ctx context.Context, in *SaveTrendDraftRequest, opts ...grpc.CallOption) (*SaveTrendDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveTrendDraftResponse)
	err := c.cc.Invoke(ctx, TrendService_SaveTrendDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) GetTrendDraft(ctx context.Context, in *GetTrendDraftRequest, opts ...grpc.CallOption) (*GetTrendDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrendDraftResponse)
	err := c.cc.Invoke(ctx, TrendService_GetTrendDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) DeleteTrendDraft(ctx context.Context, in *DeleteTrendDraftRequest, opts ...grpc.CallOption) (*DeleteTrendDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTrendDraftResponse)
	err := c.cc.Invoke(ctx, TrendService_DeleteTrendDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrendServiceServer is the server API for TrendService service.
// All implementations must embed UnimplementedTrendServiceServer
// for forward compatibility.
//
// 动态服务接口定义
type TrendServiceServer interface {
	// 发布动态
	CreateTrend(context.Context, *CreateTrendRequest) (*CreateTrendResponse, error)
	// 删除动态
	DeleteTrend(context.Context, *DeleteTrendRequest) (*DeleteTrendResponse, error)
	// 获取最新动态,设置置顶，设置评论区，访问范围
	UpdateTrend(context.Context, *UpdateTrendRequest) (*UpdateTrendResponse, error)
	// 获取动态列表
	ListTrends(context.Context, *ListTrendsRequest) (*ListTrendsResponse, error)
	// 获取单个动态详情
	GetTrendDetail(context.Context, *GetTrendDetailRequest) (*GetTrendDetailResponse, error)
	// 获取最新动态,设置置顶，设置评论区，访问范围
	GetLatestTrends(context.Context, *GetLatestTrendsRequest) (*GetLatestTrendsResponse, error)
	// 获取用户个人动态列表
	GetUserTrends(context.Context, *GetUserTrendsRequest) (*GetUserTrendsResponse, error)
	// 获取用户动态置顶
	GetUserTopTrend(context.Context, *GetUserTopTrendsRequest) (*GetUserTrendsResponse, error)
	// 评论服务定义
	// 动态评论相关模块
	// 1. 发表一级评论（父评论ID=0）
	CreateRootDiscuss(context.Context, *CreateDiscussReq) (*CreateDiscussResp, error)
	// 2. 发表多级评论（二级、三级等）
	CreateChildDiscuss(context.Context, *CreateDiscussReq) (*CreateDiscussResp, error)
	// 3. 获取动态的多级评论树（树形结构）
	GetTrendDiscusses(context.Context, *GetDiscussesListReq) (*GetDiscussesListResp, error)
	// 4. 获取一级评论（分页）
	GetRootDiscusses(context.Context, *GetDiscussesReq) (*DiscussesListResp, error)
	// 5. 获取子评论（指定父评论下的所有评论）
	GetChildDiscusses(context.Context, *GetChildDiscussesReq) (*DiscussesListResp, error)
	// 6. 删除评论（支持任意级别评论删除）
	DeleteDiscuss(context.Context, *DeleteDiscussReq) (*DeleteDiscussResp, error)
	// 7. 获取未读回复
	GetUnreadReplies(context.Context, *GetUnreadRepliesReq) (*RepliesListResp, error)
	// 8. 标记评论为已读
	MarkDiscussRead(context.Context, *MarkDiscussRequest) (*MarkDiscussResponse, error)
	// 点赞/取消点赞
	ToggleLike(context.Context, *LikeToggleRequest) (*LikeToggleResponse, error)
	// 获取动态点赞摘要 (用于动态下方展示)
	GetTrendLikeSummary(context.Context, *GetTrendLikeSummaryRequest) (*GetTrendLikeSummaryResponse, error)
	// 批量获取点赞摘要 (用于动态流)
	BatchGetTrendLikeSummary(context.Context, *BatchTrendLikeSummaryRequest) (*BatchTrendLikeSummaryResponse, error)
	// 获取点赞用户列表 (微信"查看全部点赞")
	GetLikedUsers(context.Context, *GetLikedUsersRequest) (*GetLikedUsersResponse, error)
	// 获取未读点赞通知
	GetUnreadLikes(context.Context, *GetUnreadLikesRequest) (*GetUnreadLikesResponse, error)
	// 标记点赞为已读
	MarkLikesRead(context.Context, *MarkLikesReadRequest) (*MarkLikesReadResponse, error)
	// 保存动态草稿
	SaveTrendDraft(context.Context, *SaveTrendDraftRequest) (*SaveTrendDraftResponse, error)
	// 获取动态草稿
	GetTrendDraft(context.Context, *GetTrendDraftRequest) (*GetTrendDraftResponse, error)
	// 删除动态草稿
	DeleteTrendDraft(context.Context, *DeleteTrendDraftRequest) (*DeleteTrendDraftResponse, error)
	mustEmbedUnimplementedTrendServiceServer()
}

// UnimplementedTrendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrendServiceServer struct{}

func (UnimplementedTrendServiceServer) CreateTrend(context.Context, *CreateTrendRequest) (*CreateTrendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrend not implemented")
}
func (UnimplementedTrendServiceServer) DeleteTrend(context.Context, *DeleteTrendRequest) (*DeleteTrendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTrend not implemented")
}
func (UnimplementedTrendServiceServer) UpdateTrend(context.Context, *UpdateTrendRequest) (*UpdateTrendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrend not implemented")
}
func (UnimplementedTrendServiceServer) ListTrends(context.Context, *ListTrendsRequest) (*ListTrendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTrends not implemented")
}
func (UnimplementedTrendServiceServer) GetTrendDetail(context.Context, *GetTrendDetailRequest) (*GetTrendDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrendDetail not implemented")
}
func (UnimplementedTrendServiceServer) GetLatestTrends(context.Context, *GetLatestTrendsRequest) (*GetLatestTrendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestTrends not implemented")
}
func (UnimplementedTrendServiceServer) GetUserTrends(context.Context, *GetUserTrendsRequest) (*GetUserTrendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTrends not implemented")
}
func (UnimplementedTrendServiceServer) GetUserTopTrend(context.Context, *GetUserTopTrendsRequest) (*GetUserTrendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTopTrend not implemented")
}
func (UnimplementedTrendServiceServer) CreateRootDiscuss(context.Context, *CreateDiscussReq) (*CreateDiscussResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRootDiscuss not implemented")
}
func (UnimplementedTrendServiceServer) CreateChildDiscuss(context.Context, *CreateDiscussReq) (*CreateDiscussResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChildDiscuss not implemented")
}
func (UnimplementedTrendServiceServer) GetTrendDiscusses(context.Context, *GetDiscussesListReq) (*GetDiscussesListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrendDiscusses not implemented")
}
func (UnimplementedTrendServiceServer) GetRootDiscusses(context.Context, *GetDiscussesReq) (*DiscussesListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRootDiscusses not implemented")
}
func (UnimplementedTrendServiceServer) GetChildDiscusses(context.Context, *GetChildDiscussesReq) (*DiscussesListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChildDiscusses not implemented")
}
func (UnimplementedTrendServiceServer) DeleteDiscuss(context.Context, *DeleteDiscussReq) (*DeleteDiscussResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDiscuss not implemented")
}
func (UnimplementedTrendServiceServer) GetUnreadReplies(context.Context, *GetUnreadRepliesReq) (*RepliesListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnreadReplies not implemented")
}
func (UnimplementedTrendServiceServer) MarkDiscussRead(context.Context, *MarkDiscussRequest) (*MarkDiscussResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkDiscussRead not implemented")
}
func (UnimplementedTrendServiceServer) ToggleLike(context.Context, *LikeToggleRequest) (*LikeToggleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleLike not implemented")
}
func (UnimplementedTrendServiceServer) GetTrendLikeSummary(context.Context, *GetTrendLikeSummaryRequest) (*GetTrendLikeSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrendLikeSummary not implemented")
}
func (UnimplementedTrendServiceServer) BatchGetTrendLikeSummary(context.Context, *BatchTrendLikeSummaryRequest) (*BatchTrendLikeSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetTrendLikeSummary not implemented")
}
func (UnimplementedTrendServiceServer) GetLikedUsers(context.Context, *GetLikedUsersRequest) (*GetLikedUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLikedUsers not implemented")
}
func (UnimplementedTrendServiceServer) GetUnreadLikes(context.Context, *GetUnreadLikesRequest) (*GetUnreadLikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnreadLikes not implemented")
}
func (UnimplementedTrendServiceServer) MarkLikesRead(context.Context, *MarkLikesReadRequest) (*MarkLikesReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkLikesRead not implemented")
}
func (UnimplementedTrendServiceServer) SaveTrendDraft(context.Context, *SaveTrendDraftRequest) (*SaveTrendDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTrendDraft not implemented")
}
func (UnimplementedTrendServiceServer) GetTrendDraft(context.Context, *GetTrendDraftRequest) (*GetTrendDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrendDraft not implemented")
}
func (UnimplementedTrendServiceServer) DeleteTrendDraft(context.Context, *DeleteTrendDraftRequest) (*DeleteTrendDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTrendDraft not implemented")
}
func (UnimplementedTrendServiceServer) mustEmbedUnimplementedTrendServiceServer() {}
func (UnimplementedTrendServiceServer) testEmbeddedByValue()                      {}

// UnsafeTrendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrendServiceServer will
// result in compilation errors.
type UnsafeTrendServiceServer interface {
	mustEmbedUnimplementedTrendServiceServer()
}

func RegisterTrendServiceServer(s grpc.ServiceRegistrar, srv TrendServiceServer) {
	// If the following call pancis, it indicates UnimplementedTrendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrendService_ServiceDesc, srv)
}

func _TrendService_CreateTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).CreateTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_CreateTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).CreateTrend(ctx, req.(*CreateTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_DeleteTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).DeleteTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_DeleteTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).DeleteTrend(ctx, req.(*DeleteTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_UpdateTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).UpdateTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_UpdateTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).UpdateTrend(ctx, req.(*UpdateTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_ListTrends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).ListTrends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_ListTrends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).ListTrends(ctx, req.(*ListTrendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_GetTrendDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).GetTrendDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_GetTrendDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).GetTrendDetail(ctx, req.(*GetTrendDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_GetLatestTrends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestTrendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).GetLatestTrends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_GetLatestTrends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).GetLatestTrends(ctx, req.(*GetLatestTrendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_GetUserTrends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTrendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).GetUserTrends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_GetUserTrends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).GetUserTrends(ctx, req.(*GetUserTrendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_GetUserTopTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTopTrendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).GetUserTopTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_GetUserTopTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).GetUserTopTrend(ctx, req.(*GetUserTopTrendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_CreateRootDiscuss_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDiscussReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).CreateRootDiscuss(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_CreateRootDiscuss_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).CreateRootDiscuss(ctx, req.(*CreateDiscussReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_CreateChildDiscuss_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDiscussReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).CreateChildDiscuss(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_CreateChildDiscuss_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).CreateChildDiscuss(ctx, req.(*CreateDiscussReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_GetTrendDiscusses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscussesListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).GetTrendDiscusses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_GetTrendDiscusses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).GetTrendDiscusses(ctx, req.(*GetDiscussesListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_GetRootDiscusses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscussesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).GetRootDiscusses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_GetRootDiscusses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).GetRootDiscusses(ctx, req.(*GetDiscussesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_GetChildDiscusses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChildDiscussesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).GetChildDiscusses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_GetChildDiscusses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).GetChildDiscusses(ctx, req.(*GetChildDiscussesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_DeleteDiscuss_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDiscussReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).DeleteDiscuss(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_DeleteDiscuss_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).DeleteDiscuss(ctx, req.(*DeleteDiscussReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_GetUnreadReplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadRepliesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).GetUnreadReplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_GetUnreadReplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).GetUnreadReplies(ctx, req.(*GetUnreadRepliesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_MarkDiscussRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkDiscussRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).MarkDiscussRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_MarkDiscussRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).MarkDiscussRead(ctx, req.(*MarkDiscussRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_ToggleLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeToggleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).ToggleLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_ToggleLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).ToggleLike(ctx, req.(*LikeToggleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_GetTrendLikeSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendLikeSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).GetTrendLikeSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_GetTrendLikeSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).GetTrendLikeSummary(ctx, req.(*GetTrendLikeSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_BatchGetTrendLikeSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchTrendLikeSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).BatchGetTrendLikeSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_BatchGetTrendLikeSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).BatchGetTrendLikeSummary(ctx, req.(*BatchTrendLikeSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_GetLikedUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLikedUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).GetLikedUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_GetLikedUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).GetLikedUsers(ctx, req.(*GetLikedUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_GetUnreadLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadLikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).GetUnreadLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_GetUnreadLikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).GetUnreadLikes(ctx, req.(*GetUnreadLikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_MarkLikesRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkLikesReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).MarkLikesRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_MarkLikesRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).MarkLikesRead(ctx, req.(*MarkLikesReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_SaveTrendDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTrendDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).SaveTrendDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_SaveTrendDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).SaveTrendDraft(ctx, req.(*SaveTrendDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_GetTrendDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).GetTrendDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_GetTrendDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).GetTrendDraft(ctx, req.(*GetTrendDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_DeleteTrendDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTrendDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).DeleteTrendDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_DeleteTrendDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).DeleteTrendDraft(ctx, req.(*DeleteTrendDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrendService_ServiceDesc is the grpc.ServiceDesc for TrendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trend.TrendService",
	HandlerType: (*TrendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrend",
			Handler:    _TrendService_CreateTrend_Handler,
		},
		{
			MethodName: "DeleteTrend",
			Handler:    _TrendService_DeleteTrend_Handler,
		},
		{
			MethodName: "UpdateTrend",
			Handler:    _TrendService_UpdateTrend_Handler,
		},
		{
			MethodName: "ListTrends",
			Handler:    _TrendService_ListTrends_Handler,
		},
		{
			MethodName: "GetTrendDetail",
			Handler:    _TrendService_GetTrendDetail_Handler,
		},
		{
			MethodName: "GetLatestTrends",
			Handler:    _TrendService_GetLatestTrends_Handler,
		},
		{
			MethodName: "GetUserTrends",
			Handler:    _TrendService_GetUserTrends_Handler,
		},
		{
			MethodName: "GetUserTopTrend",
			Handler:    _TrendService_GetUserTopTrend_Handler,
		},
		{
			MethodName: "CreateRootDiscuss",
			Handler:    _TrendService_CreateRootDiscuss_Handler,
		},
		{
			MethodName: "CreateChildDiscuss",
			Handler:    _TrendService_CreateChildDiscuss_Handler,
		},
		{
			MethodName: "GetTrendDiscusses",
			Handler:    _TrendService_GetTrendDiscusses_Handler,
		},
		{
			MethodName: "GetRootDiscusses",
			Handler:    _TrendService_GetRootDiscusses_Handler,
		},
		{
			MethodName: "GetChildDiscusses",
			Handler:    _TrendService_GetChildDiscusses_Handler,
		},
		{
			MethodName: "DeleteDiscuss",
			Handler:    _TrendService_DeleteDiscuss_Handler,
		},
		{
			MethodName: "GetUnreadReplies",
			Handler:    _TrendService_GetUnreadReplies_Handler,
		},
		{
			MethodName: "MarkDiscussRead",
			Handler:    _TrendService_MarkDiscussRead_Handler,
		},
		{
			MethodName: "ToggleLike",
			Handler:    _TrendService_ToggleLike_Handler,
		},
		{
			MethodName: "GetTrendLikeSummary",
			Handler:    _TrendService_GetTrendLikeSummary_Handler,
		},
		{
			MethodName: "BatchGetTrendLikeSummary",
			Handler:    _TrendService_BatchGetTrendLikeSummary_Handler,
		},
		{
			MethodName: "GetLikedUsers",
			Handler:    _TrendService_GetLikedUsers_Handler,
		},
		{
			MethodName: "GetUnreadLikes",
			Handler:    _TrendService_GetUnreadLikes_Handler,
		},
		{
			MethodName: "MarkLikesRead",
			Handler:    _TrendService_MarkLikesRead_Handler,
		},
		{
			MethodName: "SaveTrendDraft",
			Handler:    _TrendService_SaveTrendDraft_Handler,
		},
		{
			MethodName: "GetTrendDraft",
			Handler:    _TrendService_GetTrendDraft_Handler,
		},
		{
			MethodName: "DeleteTrendDraft",
			Handler:    _TrendService_DeleteTrendDraft_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trend.proto",
}
