// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: im.proto

package imclient

import (
	"context"

	"github.com/iceymoss/go-hichat-api/apps/im/rpc/im"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatLog                        = im.ChatLog
	Conversation                   = im.Conversation
	CreateGroupConversationReq     = im.CreateGroupConversationReq
	CreateGroupConversationResp    = im.CreateGroupConversationResp
	CreateNotificationReq          = im.CreateNotificationReq
	CreateNotificationResp         = im.CreateNotificationResp
	EnsureGroupConversationReq     = im.EnsureGroupConversationReq
	EnsureGroupConversationResp    = im.EnsureGroupConversationResp
	GetAtMeMessagesReq             = im.GetAtMeMessagesReq
	GetAtMeMessagesResp            = im.GetAtMeMessagesResp
	GetChatLogReq                  = im.GetChatLogReq
	GetChatLogResp                 = im.GetChatLogResp
	GetConversationsReq            = im.GetConversationsReq
	GetConversationsResp           = im.GetConversationsResp
	GetUnreadNotificationCountReq  = im.GetUnreadNotificationCountReq
	GetUnreadNotificationCountResp = im.GetUnreadNotificationCountResp
	ListNotificationsReq           = im.ListNotificationsReq
	ListNotificationsResp          = im.ListNotificationsResp
	MarkNotificationsReadReq       = im.MarkNotificationsReadReq
	MarkNotificationsReadResp      = im.MarkNotificationsReadResp
	Notification                   = im.Notification
	PutConversationsReq            = im.PutConversationsReq
	PutConversationsResp           = im.PutConversationsResp
	RecallMsgReq                   = im.RecallMsgReq
	RecallMsgResp                  = im.RecallMsgResp
	SetConversationSettingsReq     = im.SetConversationSettingsReq
	SetConversationSettingsResp    = im.SetConversationSettingsResp
	SetUpUserConversationReq       = im.SetUpUserConversationReq
	SetUpUserConversationResp      = im.SetUpUserConversationResp

	Im interface {
		// 获取会话记录
		GetChatLog(ctx context.Context, in *GetChatLogReq, opts ...grpc.CallOption) (*GetChatLogResp, error)
		// 建立会话: 群聊, 私聊
		SetUpUserConversation(ctx context.Context, in *SetUpUserConversationReq, opts ...grpc.CallOption) (*SetUpUserConversationResp, error)
		// 获取会话
		GetConversations(ctx context.Context, in *GetConversationsReq, opts ...grpc.CallOption) (*GetConversationsResp, error)
		// 更新会话
		PutConversations(ctx context.Context, in *PutConversationsReq, opts ...grpc.CallOption) (*PutConversationsResp, error)
		// 创建群会话
		CreateGroupConversation(ctx context.Context, in *CreateGroupConversationReq, opts ...grpc.CallOption) (*CreateGroupConversationResp, error)
		// 设置会话置顶/免打扰
		SetConversationSettings(ctx context.Context, in *SetConversationSettingsReq, opts ...grpc.CallOption) (*SetConversationSettingsResp, error)
		// 撤回消息（本人限时 / 群管理员不限时）
		RecallMsg(ctx context.Context, in *RecallMsgReq, opts ...grpc.CallOption) (*RecallMsgResp, error)
		// 获取会话中 @我 且未读的消息列表（用于"有人@我"快速跳转）
		GetAtMeMessages(ctx context.Context, in *GetAtMeMessagesReq, opts ...grpc.CallOption) (*GetAtMeMessagesResp, error)
		// 公共通知通道：落库一条通知（幂等）
		CreateNotification(ctx context.Context, in *CreateNotificationReq, opts ...grpc.CallOption) (*CreateNotificationResp, error)
		// 公共通知通道：拉取接收者通知列表（分页）
		ListNotifications(ctx context.Context, in *ListNotificationsReq, opts ...grpc.CallOption) (*ListNotificationsResp, error)
		// 公共通知通道：标记通知已读（单条/批量/全部）
		MarkNotificationsRead(ctx context.Context, in *MarkNotificationsReadReq, opts ...grpc.CallOption) (*MarkNotificationsReadResp, error)
		// 公共通知通道：接收者未读数
		GetUnreadNotificationCount(ctx context.Context, in *GetUnreadNotificationCountReq, opts ...grpc.CallOption) (*GetUnreadNotificationCountResp, error)
		EnsureGroupConversation(ctx context.Context, in *EnsureGroupConversationReq, opts ...grpc.CallOption) (*EnsureGroupConversationResp, error)
	}

	defaultIm struct {
		cli zrpc.Client
	}
)

func NewIm(cli zrpc.Client) Im {
	return &defaultIm{
		cli: cli,
	}
}

// 获取会话记录
func (m *defaultIm) GetChatLog(ctx context.Context, in *GetChatLogReq, opts ...grpc.CallOption) (*GetChatLogResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.GetChatLog(ctx, in, opts...)
}

// 建立会话: 群聊, 私聊
func (m *defaultIm) SetUpUserConversation(ctx context.Context, in *SetUpUserConversationReq, opts ...grpc.CallOption) (*SetUpUserConversationResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.SetUpUserConversation(ctx, in, opts...)
}

// 获取会话
func (m *defaultIm) GetConversations(ctx context.Context, in *GetConversationsReq, opts ...grpc.CallOption) (*GetConversationsResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.GetConversations(ctx, in, opts...)
}

// 更新会话
func (m *defaultIm) PutConversations(ctx context.Context, in *PutConversationsReq, opts ...grpc.CallOption) (*PutConversationsResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.PutConversations(ctx, in, opts...)
}

// 创建群会话
func (m *defaultIm) CreateGroupConversation(ctx context.Context, in *CreateGroupConversationReq, opts ...grpc.CallOption) (*CreateGroupConversationResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.CreateGroupConversation(ctx, in, opts...)
}

// 设置会话置顶/免打扰
func (m *defaultIm) SetConversationSettings(ctx context.Context, in *SetConversationSettingsReq, opts ...grpc.CallOption) (*SetConversationSettingsResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.SetConversationSettings(ctx, in, opts...)
}

// 撤回消息（本人限时 / 群管理员不限时）
func (m *defaultIm) RecallMsg(ctx context.Context, in *RecallMsgReq, opts ...grpc.CallOption) (*RecallMsgResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.RecallMsg(ctx, in, opts...)
}

// 获取会话中 @我 且未读的消息列表（用于"有人@我"快速跳转）
func (m *defaultIm) GetAtMeMessages(ctx context.Context, in *GetAtMeMessagesReq, opts ...grpc.CallOption) (*GetAtMeMessagesResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.GetAtMeMessages(ctx, in, opts...)
}

// 公共通知通道：落库一条通知（幂等）
func (m *defaultIm) CreateNotification(ctx context.Context, in *CreateNotificationReq, opts ...grpc.CallOption) (*CreateNotificationResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.CreateNotification(ctx, in, opts...)
}

// 公共通知通道：拉取接收者通知列表（分页）
func (m *defaultIm) ListNotifications(ctx context.Context, in *ListNotificationsReq, opts ...grpc.CallOption) (*ListNotificationsResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.ListNotifications(ctx, in, opts...)
}

// 公共通知通道：标记通知已读（单条/批量/全部）
func (m *defaultIm) MarkNotificationsRead(ctx context.Context, in *MarkNotificationsReadReq, opts ...grpc.CallOption) (*MarkNotificationsReadResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.MarkNotificationsRead(ctx, in, opts...)
}

// 公共通知通道：接收者未读数
func (m *defaultIm) GetUnreadNotificationCount(ctx context.Context, in *GetUnreadNotificationCountReq, opts ...grpc.CallOption) (*GetUnreadNotificationCountResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.GetUnreadNotificationCount(ctx, in, opts...)
}

func (m *defaultIm) EnsureGroupConversation(ctx context.Context, in *EnsureGroupConversationReq, opts ...grpc.CallOption) (*EnsureGroupConversationResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.EnsureGroupConversation(ctx, in, opts...)
}
