// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: social.proto

package server

import (
	"context"

	"github.com/iceymoss/go-hichat-api/apps/social/rpc/internal/logic"
	"github.com/iceymoss/go-hichat-api/apps/social/rpc/internal/svc"
	"github.com/iceymoss/go-hichat-api/apps/social/rpc/social"
)

type SocialServer struct {
	svcCtx *svc.ServiceContext
	social.UnimplementedSocialServer
}

func NewSocialServer(svcCtx *svc.ServiceContext) *SocialServer {
	return &SocialServer{
		svcCtx: svcCtx,
	}
}

// 好友业务：请求好友、通过或拒绝申请、好友列表
func (s *SocialServer) FriendPutIn(ctx context.Context, in *social.FriendPutInReq) (*social.FriendPutInResp, error) {
	l := logic.NewFriendPutInLogic(ctx, s.svcCtx)
	return l.FriendPutIn(in)
}

func (s *SocialServer) FriendPutInHandle(ctx context.Context, in *social.FriendPutInHandleReq) (*social.FriendPutInHandleResp, error) {
	l := logic.NewFriendPutInHandleLogic(ctx, s.svcCtx)
	return l.FriendPutInHandle(in)
}

func (s *SocialServer) FriendPutInRead(ctx context.Context, in *social.FriendPutInReadReq) (*social.FriendPutInReadResp, error) {
	l := logic.NewFriendPutInReadLogic(ctx, s.svcCtx)
	return l.FriendPutInRead(in)
}

func (s *SocialServer) FriendPutInDelete(ctx context.Context, in *social.FriendPutInDeleteReq) (*social.FriendPutInDeleteResp, error) {
	l := logic.NewFriendPutInDeleteLogic(ctx, s.svcCtx)
	return l.FriendPutInDelete(in)
}

func (s *SocialServer) FriendPutInList(ctx context.Context, in *social.FriendPutInListReq) (*social.FriendPutInListResp, error) {
	l := logic.NewFriendPutInListLogic(ctx, s.svcCtx)
	return l.FriendPutInList(in)
}

func (s *SocialServer) FriendPutInMessageCount(ctx context.Context, in *social.FriendPutInMessageCountReq) (*social.FriendPutInMessageCountResp, error) {
	l := logic.NewFriendPutInMessageCountLogic(ctx, s.svcCtx)
	return l.FriendPutInMessageCount(in)
}

func (s *SocialServer) FriendList(ctx context.Context, in *social.FriendListReq) (*social.FriendListResp, error) {
	l := logic.NewFriendListLogic(ctx, s.svcCtx)
	return l.FriendList(in)
}

func (s *SocialServer) FriendUpdateRemark(ctx context.Context, in *social.FriendUpdateRemarkReq) (*social.FriendUpdateRemarkResp, error) {
	l := logic.NewFriendUpdateRemarkLogic(ctx, s.svcCtx)
	return l.FriendUpdateRemark(in)
}

func (s *SocialServer) FriendDelete(ctx context.Context, in *social.FriendDeleteReq) (*social.FriendDeleteResp, error) {
	l := logic.NewFriendDeleteLogic(ctx, s.svcCtx)
	return l.FriendDelete(in)
}

func (s *SocialServer) FriendBlock(ctx context.Context, in *social.FriendBlockReq) (*social.FriendBlockResp, error) {
	l := logic.NewFriendBlockLogic(ctx, s.svcCtx)
	return l.FriendBlock(in)
}

func (s *SocialServer) FriendMomentsPermission(ctx context.Context, in *social.FriendMomentsPermissionReq) (*social.FriendMomentsPermissionResp, error) {
	l := logic.NewFriendMomentsPermissionLogic(ctx, s.svcCtx)
	return l.FriendMomentsPermission(in)
}

func (s *SocialServer) FriendNotification(ctx context.Context, in *social.FriendNotificationReq) (*social.FriendNotificationResp, error) {
	l := logic.NewFriendNotificationLogic(ctx, s.svcCtx)
	return l.FriendNotification(in)
}

func (s *SocialServer) FriendPin(ctx context.Context, in *social.FriendPinReq) (*social.FriendPinResp, error) {
	l := logic.NewFriendPinLogic(ctx, s.svcCtx)
	return l.FriendPin(in)
}

func (s *SocialServer) FriendMute(ctx context.Context, in *social.FriendMuteReq) (*social.FriendMuteResp, error) {
	l := logic.NewFriendMuteLogic(ctx, s.svcCtx)
	return l.FriendMute(in)
}

func (s *SocialServer) FriendTags(ctx context.Context, in *social.FriendTagsReq) (*social.FriendTagsResp, error) {
	l := logic.NewFriendTagsLogic(ctx, s.svcCtx)
	return l.FriendTags(in)
}

func (s *SocialServer) FriendReport(ctx context.Context, in *social.FriendReportReq) (*social.FriendReportResp, error) {
	l := logic.NewFriendReportLogic(ctx, s.svcCtx)
	return l.FriendReport(in)
}

func (s *SocialServer) FriendShare(ctx context.Context, in *social.FriendShareReq) (*social.FriendShareResp, error) {
	l := logic.NewFriendShareLogic(ctx, s.svcCtx)
	return l.FriendShare(in)
}

// 群业务：创建群，修改群，群公告，申请群，用户群列表，群成员，申请群，群退出..
func (s *SocialServer) GroupCreate(ctx context.Context, in *social.GroupCreateReq) (*social.GroupCreateResp, error) {
	l := logic.NewGroupCreateLogic(ctx, s.svcCtx)
	return l.GroupCreate(in)
}

func (s *SocialServer) GroupPutin(ctx context.Context, in *social.GroupPutinReq) (*social.GroupPutinResp, error) {
	l := logic.NewGroupPutinLogic(ctx, s.svcCtx)
	return l.GroupPutin(in)
}

func (s *SocialServer) GroupPutinList(ctx context.Context, in *social.GroupPutinListReq) (*social.GroupPutinListResp, error) {
	l := logic.NewGroupPutinListLogic(ctx, s.svcCtx)
	return l.GroupPutinList(in)
}

func (s *SocialServer) GetGroupPutListByUid(ctx context.Context, in *social.GetGroupPutListByUidReq) (*social.GroupPutinListResp, error) {
	l := logic.NewGetGroupPutListByUidLogic(ctx, s.svcCtx)
	return l.GetGroupPutListByUid(in)
}

func (s *SocialServer) GroupPutInHandle(ctx context.Context, in *social.GroupPutInHandleReq) (*social.GroupPutInHandleResp, error) {
	l := logic.NewGroupPutInHandleLogic(ctx, s.svcCtx)
	return l.GroupPutInHandle(in)
}

func (s *SocialServer) GroupList(ctx context.Context, in *social.GroupListReq) (*social.GroupListResp, error) {
	l := logic.NewGroupListLogic(ctx, s.svcCtx)
	return l.GroupList(in)
}

func (s *SocialServer) GroupUsers(ctx context.Context, in *social.GroupUsersReq) (*social.GroupUsersResp, error) {
	l := logic.NewGroupUsersLogic(ctx, s.svcCtx)
	return l.GroupUsers(in)
}

func (s *SocialServer) FindGroupList(ctx context.Context, in *social.FindGroupListReq) (*social.FindGroupListResp, error) {
	l := logic.NewFindGroupListLogic(ctx, s.svcCtx)
	return l.FindGroupList(in)
}

func (s *SocialServer) GroupQuit(ctx context.Context, in *social.GroupQuitReq) (*social.GroupQuitResp, error) {
	l := logic.NewGroupQuitLogic(ctx, s.svcCtx)
	return l.GroupQuit(in)
}

func (s *SocialServer) GroupKick(ctx context.Context, in *social.GroupKickReq) (*social.GroupKickResp, error) {
	l := logic.NewGroupKickLogic(ctx, s.svcCtx)
	return l.GroupKick(in)
}

func (s *SocialServer) GroupUpdate(ctx context.Context, in *social.GroupUpdateReq) (*social.GroupUpdateResp, error) {
	l := logic.NewGroupUpdateLogic(ctx, s.svcCtx)
	return l.GroupUpdate(in)
}

func (s *SocialServer) GroupDetail(ctx context.Context, in *social.GroupDetailReq) (*social.GroupDetailResp, error) {
	l := logic.NewGroupDetailLogic(ctx, s.svcCtx)
	return l.GroupDetail(in)
}

func (s *SocialServer) GroupDisband(ctx context.Context, in *social.GroupDisbandReq) (*social.GroupDisbandResp, error) {
	l := logic.NewGroupDisbandLogic(ctx, s.svcCtx)
	return l.GroupDisband(in)
}

func (s *SocialServer) GroupTransferOwner(ctx context.Context, in *social.GroupTransferOwnerReq) (*social.GroupTransferOwnerResp, error) {
	l := logic.NewGroupTransferOwnerLogic(ctx, s.svcCtx)
	return l.GroupTransferOwner(in)
}

func (s *SocialServer) GroupSetAdmin(ctx context.Context, in *social.GroupSetAdminReq) (*social.GroupSetAdminResp, error) {
	l := logic.NewGroupSetAdminLogic(ctx, s.svcCtx)
	return l.GroupSetAdmin(in)
}

// 邀请链接/二维码入群
func (s *SocialServer) GroupInviteLinkCreate(ctx context.Context, in *social.GroupInviteLinkCreateReq) (*social.GroupInviteLinkCreateResp, error) {
	l := logic.NewGroupInviteLinkCreateLogic(ctx, s.svcCtx)
	return l.GroupInviteLinkCreate(in)
}

func (s *SocialServer) GroupInviteLinkList(ctx context.Context, in *social.GroupInviteLinkListReq) (*social.GroupInviteLinkListResp, error) {
	l := logic.NewGroupInviteLinkListLogic(ctx, s.svcCtx)
	return l.GroupInviteLinkList(in)
}

func (s *SocialServer) GroupInviteLinkRevoke(ctx context.Context, in *social.GroupInviteLinkRevokeReq) (*social.GroupInviteLinkRevokeResp, error) {
	l := logic.NewGroupInviteLinkRevokeLogic(ctx, s.svcCtx)
	return l.GroupInviteLinkRevoke(in)
}

func (s *SocialServer) GroupJoinByToken(ctx context.Context, in *social.GroupJoinByTokenReq) (*social.GroupJoinByTokenResp, error) {
	l := logic.NewGroupJoinByTokenLogic(ctx, s.svcCtx)
	return l.GroupJoinByToken(in)
}

// 群成员资料（群内昵称/群备注/@列表）
func (s *SocialServer) GetMyGroupMemberSetting(ctx context.Context, in *social.GetMyGroupMemberSettingReq) (*social.GetMyGroupMemberSettingResp, error) {
	l := logic.NewGetMyGroupMemberSettingLogic(ctx, s.svcCtx)
	return l.GetMyGroupMemberSetting(in)
}

func (s *SocialServer) UpdateMyGroupMemberSetting(ctx context.Context, in *social.UpdateMyGroupMemberSettingReq) (*social.UpdateMyGroupMemberSettingResp, error) {
	l := logic.NewUpdateMyGroupMemberSettingLogic(ctx, s.svcCtx)
	return l.UpdateMyGroupMemberSetting(in)
}

func (s *SocialServer) GroupAtList(ctx context.Context, in *social.GroupAtListReq) (*social.GroupAtListResp, error) {
	l := logic.NewGroupAtListLogic(ctx, s.svcCtx)
	return l.GroupAtList(in)
}

// 公告历史/置顶
func (s *SocialServer) GroupAnnouncementCreate(ctx context.Context, in *social.GroupAnnouncementCreateReq) (*social.GroupAnnouncementCreateResp, error) {
	l := logic.NewGroupAnnouncementCreateLogic(ctx, s.svcCtx)
	return l.GroupAnnouncementCreate(in)
}

func (s *SocialServer) GroupAnnouncementList(ctx context.Context, in *social.GroupAnnouncementListReq) (*social.GroupAnnouncementListResp, error) {
	l := logic.NewGroupAnnouncementListLogic(ctx, s.svcCtx)
	return l.GroupAnnouncementList(in)
}

func (s *SocialServer) GroupAnnouncementPin(ctx context.Context, in *social.GroupAnnouncementPinReq) (*social.GroupAnnouncementPinResp, error) {
	l := logic.NewGroupAnnouncementPinLogic(ctx, s.svcCtx)
	return l.GroupAnnouncementPin(in)
}
