// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: im.proto

package server

import (
	"context"

	"github.com/iceymoss/go-hichat-api/apps/im/rpc/im"
	"github.com/iceymoss/go-hichat-api/apps/im/rpc/internal/logic"
	"github.com/iceymoss/go-hichat-api/apps/im/rpc/internal/svc"
)

type ImServer struct {
	svcCtx *svc.ServiceContext
	im.UnimplementedImServer
}

func NewImServer(svcCtx *svc.ServiceContext) *ImServer {
	return &ImServer{
		svcCtx: svcCtx,
	}
}

func (s *ImServer) Ping(ctx context.Context, in *im.Request) (*im.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
