// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	friend "github.com/iceymoss/go-hichat-api/apps/social/api/internal/handler/friend"
	group "github.com/iceymoss/go-hichat-api/apps/social/api/internal/handler/group"
	"github.com/iceymoss/go-hichat-api/apps/social/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 拉黑/取消拉黑
				Method:  http.MethodPost,
				Path:    "/friend/block",
				Handler: friend.FriendBlockHandler(serverCtx),
			},
			{
				// 删除好友（双向）
				Method:  http.MethodPost,
				Path:    "/friend/delete",
				Handler: friend.FriendDeleteHandler(serverCtx),
			},
			{
				// 朋友圈权限
				Method:  http.MethodPost,
				Path:    "/friend/momentsPermission",
				Handler: friend.FriendMomentsPermissionHandler(serverCtx),
			},
			{
				// 静音开关
				Method:  http.MethodPost,
				Path:    "/friend/mute",
				Handler: friend.FriendMuteHandler(serverCtx),
			},
			{
				// 消息通知开关
				Method:  http.MethodPost,
				Path:    "/friend/notification",
				Handler: friend.FriendNotificationHandler(serverCtx),
			},
			{
				// 置顶开关
				Method:  http.MethodPost,
				Path:    "/friend/pin",
				Handler: friend.FriendPinHandler(serverCtx),
			},
			{
				// 好友申请
				Method:  http.MethodPost,
				Path:    "/friend/putIn",
				Handler: friend.FriendPutInHandler(serverCtx),
			},
			{
				// 好友申请处理
				Method:  http.MethodPut,
				Path:    "/friend/putIn",
				Handler: friend.FriendPutInHandleHandler(serverCtx),
			},
			{
				// 删除好友申请
				Method:  http.MethodPost,
				Path:    "/friend/putIn/delete",
				Handler: friend.FriendPutInDeleteHandler(serverCtx),
			},
			{
				// 获取好友申请消息数量
				Method:  http.MethodGet,
				Path:    "/friend/putIn/messageCount",
				Handler: friend.FriendPutInMessageCountHandler(serverCtx),
			},
			{
				// 好友申请列表
				Method:  http.MethodGet,
				Path:    "/friend/putIns",
				Handler: friend.FriendPutInListHandler(serverCtx),
			},
			{
				// 更新好友备注
				Method:  http.MethodPost,
				Path:    "/friend/remark",
				Handler: friend.FriendRemarkHandler(serverCtx),
			},
			{
				// 好友举报
				Method:  http.MethodPost,
				Path:    "/friend/report",
				Handler: friend.FriendReportHandler(serverCtx),
			},
			{
				// 好友分享（预留）
				Method:  http.MethodPost,
				Path:    "/friend/share",
				Handler: friend.FriendShareHandler(serverCtx),
			},
			{
				// 好友标签设置
				Method:  http.MethodPost,
				Path:    "/friend/tags",
				Handler: friend.FriendTagsHandler(serverCtx),
			},
			{
				// 好友列表
				Method:  http.MethodGet,
				Path:    "/friends",
				Handler: friend.FriendListHandler(serverCtx),
			},
			{
				// 好友在线情况
				Method:  http.MethodGet,
				Path:    "/friends/online",
				Handler: friend.FriendsOnlineHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/social"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创群
				Method:  http.MethodPost,
				Path:    "/group",
				Handler: group.CreateGroupHandler(serverCtx),
			},
			{
				// 申请进群
				Method:  http.MethodPost,
				Path:    "/group/putIn",
				Handler: group.GroupPutInHandler(serverCtx),
			},
			{
				// 申请进群处理
				Method:  http.MethodPut,
				Path:    "/group/putIn",
				Handler: group.GroupPutInHandleHandler(serverCtx),
			},
			{
				// 申请进群列表
				Method:  http.MethodGet,
				Path:    "/group/putIns",
				Handler: group.GroupPutInListHandler(serverCtx),
			},
			{
				// 成员列表列表
				Method:  http.MethodGet,
				Path:    "/group/users",
				Handler: group.GroupUserListHandler(serverCtx),
			},
			{
				// 群在线用户
				Method:  http.MethodGet,
				Path:    "/group/users/online",
				Handler: group.GroupUserOnlineHandler(serverCtx),
			},
			{
				// 用户申群列表
				Method:  http.MethodGet,
				Path:    "/groups",
				Handler: group.GroupListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/social"),
	)
}
