// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type LogoutReq struct {
}

type LogoutResp struct {
}

type RegisterReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
	Sex      int    `json:"sex"`
	Avatar   string `json:"avatar"`
	Email    string `json:"email"`
}

type RegisterResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type ResetPassWordReq struct {
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}

type ResetPassWordResp struct {
}

type SendVerificationEmailReq struct {
	Email string `json:"email"`
}

type SendVerificationEmailResp struct {
}

type UpdateUserReq struct {
	Name         string `json:"name"`
	Phone        string `json:"phone"`
	Avatar       string `json:"avatar"`
	Type         string `json:"type"`
	Email        string `json:"email"`
	Sex          int    `json:"sex"`
	Introduction string `json "introduction"`
	Password     string `json:"password"`
}

type UpdateUserResp struct {
}

type User struct {
	Id           string `json:"id"`
	Mobile       string `json:"mobile"`
	Nickname     string `json:"nickname"`
	Sex          int    `json:"sex"`
	Avatar       string `json:"avatar"`
	LastLogin    string `json:"lastLogin"`
	Introduction string `json "introduction"`
	Email        string `json:"email"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	Info User `json:"info"`
}

type VerifyEmailReq struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

type VerifyEmailResp struct {
}
