// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type BindEmailReq struct {
	Email string `json:"email"` // 邮箱地址
	Code  string `json:"code"`  // 邮箱验证码
}

type BindEmailResp struct {
}

type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type LogoutReq struct {
}

type LogoutResp struct {
}

type RegisterReq struct {
	Phone     string `json:"phone"`
	Password  string `json:"password"`
	Nickname  string `json:"nickname"`
	Sex       int    `json:"sex,optional"`    // 可选，注册时不设置，后续可在个人主页编辑
	Avatar    string `json:"avatar,optional"` // 可选，注册时不设置，后续可在个人主页编辑
	PhoneCode string `json:"phoneCode"`       // 手机验证码（6位数），必填
}

type RegisterResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type ResetPassWordReq struct {
	Password string `json:"password"`
	Phone    string `json:"phone,optional"` // 手机号（与邮箱二选一）
	Email    string `json:"email,optional"` // 邮箱（与手机号二选一）
	Code     string `json:"code"`           // 验证码
}

type ResetPassWordResp struct {
}

type SearchUserReq struct {
	Name  string   `form:"name,optional"`  // 用户昵称（模糊匹配）
	Phone string   `form:"phone,optional"` // 手机号（精准匹配）
	Email string   `form:"email,optional"` // 邮箱（精准匹配）
	Ids   []string `form:"ids,optional"`   // 用户ID列表（精准匹配）
}

type SearchUserResp struct {
	Users []User `json:"users"` // 用户列表
}

type SendPhoneCodeReq struct {
	Phone string `json:"phone"`
}

type SendPhoneCodeResp struct {
}

type SendVerificationEmailReq struct {
	Email string `json:"email"`
}

type SendVerificationEmailResp struct {
}

type UpdateUserReq struct {
	Name         string `json:"name,optional"`
	Phone        string `json:"phone,optional"`
	Avatar       string `json:"avatar,optional"`
	Type         string `json:"type,optional"`
	Sex          int    `json:"sex,optional"`
	Introduction string `json:"introduction,optional"`
	Password     string `json:"password,optional"`
	Region       string `json:"region,optional"`
	Occupation   string `json:"occupation,optional"`
	Tags         string `json:"tags,optional"`
}

type UpdateUserResp struct {
}

type UploadAvatarReq struct {
}

type UploadAvatarResp struct {
	Url string `json:"url"`
}

type User struct {
	Id           string `json:"id"`
	Mobile       string `json:"mobile"`
	Nickname     string `json:"nickname"`
	Sex          int    `json:"sex"`
	Avatar       string `json:"avatar"`
	LastLogin    string `json:"lastLogin"`
	Introduction string `json:"introduction"`
	Email        string `json:"email"`
	Region       string `json:"region"`
	Occupation   string `json:"occupation"`
	Tags         string `json:"tags"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	Info User `json:"info"`
}

type VerifyEmailReq struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

type VerifyEmailResp struct {
}

type VerifyPhoneCodeReq struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type VerifyPhoneCodeResp struct {
}

// ── Favorites ──

type AddFavoriteReq struct {
	Type     string `json:"type"`               // text/image/link/file/video/location/note
	Title    string `json:"title,optional"`
	Content  string `json:"content"`
	Source   string `json:"source,optional"`     // chat/moment/manual
	SourceId string `json:"sourceId,optional"`
	Tags     string `json:"tags,optional"`       // JSON array string
}

type AddFavoriteResp struct {
	Id uint64 `json:"id"`
}

type DeleteFavoriteReq struct {
	Id uint64 `json:"id"`
}

type DeleteFavoriteResp struct {
}

type ListFavoritesReq struct {
	Type     string `form:"type,optional"`
	Keyword  string `form:"keyword,optional"`
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
}

type FavoriteItem struct {
	Id        uint64 `json:"id"`
	Type      string `json:"type"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Source    string `json:"source"`
	SourceId  string `json:"sourceId"`
	Tags      string `json:"tags"`
	CreatedAt string `json:"createdAt"`
}

type ListFavoritesResp struct {
	List  []FavoriteItem `json:"list"`
	Total int64          `json:"total"`
}

// ── User Settings ──

type GetSettingsReq struct {
}

type GetSettingsResp struct {
	Settings string `json:"settings"` // JSON string
}

type UpdateSettingsReq struct {
	Settings string `json:"settings"` // JSON string
}

type UpdateSettingsResp struct {
}

// ── User Emojis / Stickers ──

type AddEmojiReq struct {
	Url       string `json:"url"`
	Name      string `json:"name,optional"`
	Thumbnail string `json:"thumbnail,optional"`
	Width     uint   `json:"width,optional"`
	Height    uint   `json:"height,optional"`
	Size      uint   `json:"size,optional"`
	FileType  string `json:"fileType,optional"` // image/gif/sticker
}

type AddEmojiResp struct {
	Id uint64 `json:"id"`
}

type DeleteEmojiReq struct {
	Id uint64 `json:"id"`
}

type DeleteEmojiResp struct {
}

type ListEmojisReq struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}

type EmojiItem struct {
	Id        uint64 `json:"id"`
	Url       string `json:"url"`
	Name      string `json:"name"`
	Thumbnail string `json:"thumbnail"`
	Width     uint   `json:"width"`
	Height    uint   `json:"height"`
	Size      uint   `json:"size"`
	FileType  string `json:"fileType"`
	CreatedAt string `json:"createdAt"`
}

type ListEmojisResp struct {
	List  []EmojiItem `json:"list"`
	Total int64       `json:"total"`
}
