// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package model

import (
	"context"
	"fmt"
	"time"

	"github.com/iceymoss/go-hichat-api/pkg/constants"
	zLog "github.com/iceymoss/go-hichat-api/pkg/logger"

	"github.com/pkg/errors"
	"github.com/zer
	"github.com/zeromicro/go-zero/core/logx"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"github.com/pkg/errors"
	"go.uber.org/zap"
)

const (
	HiChat2  = "hichat2"
	ChatLogs = "chat_logs"
)

var DefaultChatLogCount int64 = 100

type ChatLogQuery struct {
	ConversationID string
	StartTime      int64
	EndTime        int64
	Status         *int
	MsgType        *constants.MType
	Page           int
	PageSize       int
}

type chatLogModel interface {
	Insert(ctx context.Context, log *ChatLog) (*primitive.ObjectID, error)
	Delete(ctx context.Context, id string) (int64, error)
	FindByQuery(ctx context.Context, q ChatLogQuery) ([]*ChatLog, int64, error)
	Update(ctx context.Context, data *ChatLog) (*mongo.UpdateResult, error)

	// 根据时间获取列表
	ListBySendTime(ctx context.Context, conversationId string, startSendTime, endSendTime, count int64) ([]*ChatLog, error)

	// 根据id获取消息
	FindOne(ctx context.Context, id string) (*ChatLog, error)

	// 根据id批量获取消息
	ListByMsgId(ctx context.Context, id []string) ([]*ChatLog, error)

	// 更新已读数
	UpdateMakeRead(ctx context.Context, id primitive.ObjectID, readRecords []byte) error
}

type defaultChatLogModel struct {
	Conn *mongo.Client
}

func newDefaultChatLogModel(conn *mongo.Client) *defaultChatLogModel {
	return &defaultChatLogModel{
		Conn: conn,
	}
}

func (m *defaultChatLogModel) FindOne(ctx context.Context, id string) (*ChatLog, error) {
	// 转换字符串ID为ObjectID
	objectID, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("id to objectID err: %v", err)
	}

	// 构建查询过滤器
	filter := bson.M{"_id": objectID}

	// 获取集合
	collection := m.Conn.Database(HiChat2).Collection(ChatLogs)

	// 执行查询
	var result ChatLog
	err = collection.FindOne(ctx, filter).Decode(&result)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, err
		}
		return nil, fmt.Errorf("query failed: %w", err)
	}

	return &result, nil
}

// Insert 插入新聊天记录
func (m *defaultChatLogModel) Insert(ctx context.Context, log *ChatLog) (*primitive.ObjectID, error) {
	now := time.Now()
	log.CreateAt = now
	log.UpdateAt = now

	if log.SendTime == 0 {
		log.SendTime = now.UnixMilli()
	}

	res, err := m.Conn.Database(HiChat2).Collection(ChatLogs).InsertOne(ctx, log)
	if err != nil {
		if mongo.IsDuplicateKeyError(err) {
			return nil, errors.New(fmt.Sprintf("IsDuplicateKeyError: %s", err.Error()))
		}
		return nil, err
	}

	id := res.InsertedID.(primitive.ObjectID)
	return &id, nil
}

// FindByQuery 高级查询
func (m *defaultChatLogModel) FindByQuery(ctx context.Context, q ChatLogQuery) ([]*ChatLog, int64, error) {
	filter := bson.M{}

	// 构建过滤条件
	if q.ConversationID != "" {
		filter["conversationId"] = q.ConversationID
	}
	if q.StartTime > 0 || q.EndTime > 0 {
		timeFilter := bson.M{}
		if q.StartTime > 0 {
			timeFilter["$gte"] = q.StartTime
		}
		if q.EndTime > 0 {
			timeFilter["$lte"] = q.EndTime
		}
		filter["sendTime"] = timeFilter
	}
	if q.Status != nil {
		filter["status"] = *q.Status
	}
	if q.MsgType != nil {
		filter["msgType"] = *q.MsgType
	}

	// 分页参数
	opts := options.Find().
		SetSort(bson.D{{Key: "sendTime", Value: -1}}).
		SetSkip(int64((q.Page - 1) * q.PageSize)).
		SetLimit(int64(q.PageSize))

	// 执行查询
	cur, err := m.Conn.Database(HiChat2).Collection(ChatLogs).Find(ctx, filter, opts)
	if err != nil {
		return nil, 0, err
	}
	defer cur.Close(ctx)

	var results []*ChatLog
	if err := cur.All(ctx, &results); err != nil {
		return nil, 0, err
	}

	// 获取总数
	total, err := m.Conn.Database(HiChat2).Collection(ChatLogs).CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	return results, total, nil
}

func (m *defaultChatLogModel) Update(ctx context.Context, data *ChatLog) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now()

	res, err := m.Conn.Database(HiChat2).Collection(ChatLogs).UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultChatLogModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}

	res, err := m.Conn.Database(HiChat2).Collection(ChatLogs).DeleteOne(ctx, bson.M{"_id": oid})
	return res.DeletedCount, err
}

func (m *defaultChatLogModel) ListByMsgId(ctx context.Context, msgIds []string) ([]*ChatLog, error) {
	// 处理空输入
	if len(msgIds) == 0 {
		return []*ChatLog{}, nil
	}

	// 转换ID并验证有效性
	ids := make([]primitive.ObjectID, 0, len(msgIds))
	for _, id := range msgIds {
		oid, err := primitive.ObjectIDFromHex(id)
		if err != nil {
			// 记录无效ID并跳过
			logx.WithContext(ctx).Errorf("无效的消息ID格式: %s, 错误: %v", id, err)
			continue
		}
		ids = append(ids, oid)
	}

	// 检查是否有有效ID
	if len(ids) == 0 {
		return nil, errors.New("所有提供的消息ID格式无效")
	}

	// 构建查询过滤器
	filter := bson.M{"_id": bson.M{"$in": ids}}

	// 获取集合
	collection := m.Conn.Database(HiChat2).Collection(ChatLogs)

	// 执行查询
	cursor, err := collection.Find(ctx, filter)
	if err != nil {
		logx.WithContext(ctx).Errorf("查询消息失败: %v", err)
		return nil, fmt.Errorf("数据库查询失败: %w", err)
	}
	defer cursor.Close(ctx)

	// 解码结果
	var results []*ChatLog
	for cursor.Next(ctx) {
		var chatLog ChatLog
		if err := cursor.Decode(&chatLog); err != nil {
			logx.WithContext(ctx).Errorf("消息解码失败: %v", err)
			continue // 跳过无效文档继续处理
		}
		results = append(results, &chatLog)
	}

	// 检查游标错误
	if err := cursor.Err(); err != nil {
		logx.WithContext(ctx).Errorf("游标迭代错误: %v", err)
		return nil, fmt.Errorf("数据处理失败: %w", err)
	}

	// 处理空结果
	if len(results) == 0 {
		logx.WithContext(ctx).Infof("未找到指定消息: %v", msgIds)
		return nil, ErrNotFound
	}

	return results, nil
}

// ListBySendTime 根据发送时间获取对应会话的聊天记录
func (m *defaultChatLogModel) ListBySendTime(ctx context.Context, conversationId string, startSendTime, endSendTime, count int64) ([]*ChatLog, error) {
	// 初始化返回结构和默认参数
	var data []*ChatLog
	opt := options.Find()

	// 构建基础查询条件
	filter := bson.M{
		"conversationId": conversationId,
	}

	// 处理时间范围逻辑（修复关键错误点）
	timeFilter := bson.M{}
	if startSendTime > 0 && endSendTime > 0 {
		// 有效时间区间查询
		if startSendTime > endSendTime {
			return nil, errors.New("起始时间不能晚于结束时间")
		}
		timeFilter["$gte"] = startSendTime
		timeFilter["$lte"] = endSendTime
	} else if startSendTime > 0 {
		// 查询大于等于起始时间的历史消息
		timeFilter["$gte"] = startSendTime
	} else if endSendTime > 0 {
		// 查询早于等于结束时间的历史消息
		timeFilter["$lte"] = endSendTime
	}

	// 如果有时间条件才加入查询
	if len(timeFilter) > 0 {
		filter["sendTime"] = timeFilter
	}

	// 设置排序和分页（优化排序逻辑）
	opt.SetSort(bson.D{{Key: "sendTime", Value: -1}})

	// 处理返回数量
	if count > 0 {
		opt.SetLimit(count)
	} else {
		opt.SetLimit(DefaultChatLogCount)
	}

	// 执行查询
	collection := m.Conn.Database(HiChat2).Collection(ChatLogs)
	cursor, err := collection.Find(ctx, filter, opt)
	if err != nil {
		return nil, fmt.Errorf("数据库查询失败: %w", err)
	}
	defer cursor.Close(ctx)

	// 解码结果
	if err = cursor.All(ctx, &data); err != nil {
		return nil, fmt.Errorf("数据解码失败: %w", err)
	}

	return data, nil
}

func (m *defaultChatLogModel) UpdateMakeRead(ctx context.Context, id primitive.ObjectID, readRecords []byte) error {
	// 验证输入参数
	if id.IsZero() {
		logx.WithContext(ctx).Errorf("更新已读记录失败: 无效的消息ID")
		return errors.New("无效的消息ID")
	}

	if len(readRecords) == 0 {
		zLog.Error("更新已读记录: 空记录消息", zap.Any("id", id.Hex()))
	}

	// 构建更新操作
	filter := bson.M{"_id": id}
	update := bson.M{"$set": bson.M{"readRecords": readRecords}}

	// 执行更新操作
	collection := m.Conn.Database(HiChat2).Collection(ChatLogs)
	result, err := collection.UpdateOne(ctx, filter, update)
	if err != nil {
		logx.WithContext(ctx).Errorf("更新已读记录失败: 消息ID=%s, 错误: %v", id.Hex(), err)
		return fmt.Errorf("数据库更新失败: %w", err)
	}

	// 检查更新结果
	switch {
	case result.MatchedCount == 0:
		zLog.Error("未找到消息记录", zap.Any("id", id.Hex()))
		return ErrNotFound
	case result.ModifiedCount == 0:
		zLog.Error("未找到消息记录", zap.Any("id", id.Hex()))
		return nil
	default:
		zLog.Error("成功更新已读记录: 消息", zap.Any("id", id.Hex()), zap.Any("更新记录数", result.ModifiedCount))
		return nil
	}
}
