// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package model

import (
	"context"
	"errors"
	"fmt"
	"time"

	zLog "github.com/iceymoss/go-hichat-api/pkg/logger"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
	"go.uber.org/zap"
)

const Conversation_Collections = "conversations"

type conversationsModel interface {
	Insert(ctx context.Context, data *Conversations) error
	FindOne(ctx context.Context, id string) (*Conversations, error)
	Update(ctx context.Context, data *Conversations) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
	FindByUserId(ctx context.Context, uid string) (*Conversations, error)
}

type defaultConversationsModel struct {
	conn *mongo.Client
}

func newDefaultConversationsModel(conn *mongo.Client) *defaultConversationsModel {
	return &defaultConversationsModel{conn: conn}
}

// 获取集合快捷方法
func (m *defaultConversationsModel) getColl() *mongo.Collection {
	return m.conn.Database(HiChat2).Collection(Conversation_Collections)
}

func (m *defaultConversationsModel) Insert(ctx context.Context, data *Conversations) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	_, err := m.getColl().InsertOne(ctx, data)
	return err
}

func (m *defaultConversationsModel) FindOne(ctx context.Context, id string) (*Conversations, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	fmt.Println("old", oid)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var result Conversations
	err = m.getColl().FindOne(ctx, bson.M{"_id": oid}).Decode(&result)

	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, ErrNotFound
		}
		return nil, err
	}
	return &result, nil
}

func (m *defaultConversationsModel) Update(ctx context.Context, data *Conversations) (*mongo.UpdateResult, error) {
	// 确保更新时间戳准确
	data.UpdateAt = time.Now().UTC() // 使用UTC时间避免时区问题

	// 构建原子性操作
	filter := bson.M{"_id": data.ID}
	update := bson.M{"$set": data}

	// 执行 Upsert 操作（存在则更新，不存在则创建）
	result, err := m.getColl().UpdateOne(
		ctx,
		filter,
		update,
		options.Update().SetUpsert(true), // 启用 Upsert 模式
	)

	// 错误处理
	if err != nil {
		logFields := []zap.Field{
			zap.Any("filter", filter),
			zap.Any("update", update),
			zap.Error(err),
		}

		// 区分错误类型记录日志
		if mongo.IsDuplicateKeyError(err) {
			zLog.Error("唯一键冲突", logFields...)
			return nil, fmt.Errorf("会话已存在: %w", err)
		} else if isNetworkError(err) {
			zLog.Warn("网络波动导致更新失败", logFields...)
			return nil, fmt.Errorf("网络连接异常: %w", err)
		} else {
			zLog.Error("数据库更新失败", logFields...)
			return nil, fmt.Errorf("系统错误: %w", err)
		}
	}

	// 验证操作结果
	if result.MatchedCount == 0 && result.UpsertedCount == 0 {
		zLog.Warn("未匹配到文档且未创建新文档",
			zap.Int64("matched", result.MatchedCount),
			zap.Int64("upserted", result.UpsertedCount),
		)
		return nil, errors.New("操作未生效")
	}

	return result, nil
}

// isNetworkError 错误类型判断示例
func isNetworkError(err error) bool {
	var cmdErr mongo.CommandError
	if errors.As(err, &cmdErr) {
		return cmdErr.HasErrorLabel("NetworkError")
	}
	return false
}

func (m *defaultConversationsModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}

	result, err := m.getColl().DeleteOne(ctx, bson.M{"_id": oid})
	if err != nil {
		return 0, err
	}
	return result.DeletedCount, nil
}

// FindByUserId 获取用户的会话信息
func (m *defaultConversationsModel) FindByUserId(ctx context.Context, uid string) (*Conversations, error) {
	var data Conversations

	// 构建查询条件（假设userId字段是字符串类型）
	filter := bson.M{"userId": uid}

	// 执行查询
	err := m.getColl().FindOne(ctx, filter).Decode(&data)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("查询失败: %w", err)
	}

	return &data, nil
}
