// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: social.proto

package socialclient

import (
	"context"

	"github.com/iceymoss/go-hichat-api/apps/social/rpc/social"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FindGroupListReq            = social.FindGroupListReq
	FindGroupListResp           = social.FindGroupListResp
	FriendBlockReq              = social.FriendBlockReq
	FriendBlockResp             = social.FriendBlockResp
	FriendDeleteReq             = social.FriendDeleteReq
	FriendDeleteResp            = social.FriendDeleteResp
	FriendListReq               = social.FriendListReq
	FriendListResp              = social.FriendListResp
	FriendMomentsPermissionReq  = social.FriendMomentsPermissionReq
	FriendMomentsPermissionResp = social.FriendMomentsPermissionResp
	FriendMuteReq               = social.FriendMuteReq
	FriendMuteResp              = social.FriendMuteResp
	FriendNotificationReq       = social.FriendNotificationReq
	FriendNotificationResp      = social.FriendNotificationResp
	FriendPinReq                = social.FriendPinReq
	FriendPinResp               = social.FriendPinResp
	FriendPutInHandleReq        = social.FriendPutInHandleReq
	FriendPutInHandleResp       = social.FriendPutInHandleResp
	FriendPutInListReq          = social.FriendPutInListReq
	FriendPutInListResp         = social.FriendPutInListResp
	FriendPutInMessageCountReq  = social.FriendPutInMessageCountReq
	FriendPutInMessageCountResp = social.FriendPutInMessageCountResp
	FriendPutInReq              = social.FriendPutInReq
	FriendPutInResp             = social.FriendPutInResp
	FriendReportReq             = social.FriendReportReq
	FriendReportResp            = social.FriendReportResp
	FriendRequests              = social.FriendRequests
	FriendShareReq              = social.FriendShareReq
	FriendShareResp             = social.FriendShareResp
	FriendTagsReq               = social.FriendTagsReq
	FriendTagsResp              = social.FriendTagsResp
	FriendUpdateRemarkReq       = social.FriendUpdateRemarkReq
	FriendUpdateRemarkResp      = social.FriendUpdateRemarkResp
	Friends                     = social.Friends
	GroupCreateReq              = social.GroupCreateReq
	GroupCreateResp             = social.GroupCreateResp
	GroupListReq                = social.GroupListReq
	GroupListResp               = social.GroupListResp
	GroupMembers                = social.GroupMembers
	GroupPutInHandleReq         = social.GroupPutInHandleReq
	GroupPutInHandleResp        = social.GroupPutInHandleResp
	GroupPutinListReq           = social.GroupPutinListReq
	GroupPutinListResp          = social.GroupPutinListResp
	GroupPutinReq               = social.GroupPutinReq
	GroupPutinResp              = social.GroupPutinResp
	GroupRequests               = social.GroupRequests
	GroupUsersReq               = social.GroupUsersReq
	GroupUsersResp              = social.GroupUsersResp
	Groups                      = social.Groups

	Social interface {
		// 好友业务：请求好友、通过或拒绝申请、好友列表
		FriendPutIn(ctx context.Context, in *FriendPutInReq, opts ...grpc.CallOption) (*FriendPutInResp, error)
		FriendPutInHandle(ctx context.Context, in *FriendPutInHandleReq, opts ...grpc.CallOption) (*FriendPutInHandleResp, error)
		FriendPutInList(ctx context.Context, in *FriendPutInListReq, opts ...grpc.CallOption) (*FriendPutInListResp, error)
		FriendPutInMessageCount(ctx context.Context, in *FriendPutInMessageCountReq, opts ...grpc.CallOption) (*FriendPutInMessageCountResp, error)
		FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error)
		FriendUpdateRemark(ctx context.Context, in *FriendUpdateRemarkReq, opts ...grpc.CallOption) (*FriendUpdateRemarkResp, error)
		FriendDelete(ctx context.Context, in *FriendDeleteReq, opts ...grpc.CallOption) (*FriendDeleteResp, error)
		FriendBlock(ctx context.Context, in *FriendBlockReq, opts ...grpc.CallOption) (*FriendBlockResp, error)
		FriendMomentsPermission(ctx context.Context, in *FriendMomentsPermissionReq, opts ...grpc.CallOption) (*FriendMomentsPermissionResp, error)
		FriendNotification(ctx context.Context, in *FriendNotificationReq, opts ...grpc.CallOption) (*FriendNotificationResp, error)
		FriendPin(ctx context.Context, in *FriendPinReq, opts ...grpc.CallOption) (*FriendPinResp, error)
		FriendMute(ctx context.Context, in *FriendMuteReq, opts ...grpc.CallOption) (*FriendMuteResp, error)
		FriendTags(ctx context.Context, in *FriendTagsReq, opts ...grpc.CallOption) (*FriendTagsResp, error)
		FriendReport(ctx context.Context, in *FriendReportReq, opts ...grpc.CallOption) (*FriendReportResp, error)
		FriendShare(ctx context.Context, in *FriendShareReq, opts ...grpc.CallOption) (*FriendShareResp, error)
		// 群业务：创建群，修改群，群公告，申请群，用户群列表，群成员，申请群，群退出..
		GroupCreate(ctx context.Context, in *GroupCreateReq, opts ...grpc.CallOption) (*GroupCreateResp, error)
		GroupPutin(ctx context.Context, in *GroupPutinReq, opts ...grpc.CallOption) (*GroupPutinResp, error)
		GroupPutinList(ctx context.Context, in *GroupPutinListReq, opts ...grpc.CallOption) (*GroupPutinListResp, error)
		GroupPutInHandle(ctx context.Context, in *GroupPutInHandleReq, opts ...grpc.CallOption) (*GroupPutInHandleResp, error)
		GroupList(ctx context.Context, in *GroupListReq, opts ...grpc.CallOption) (*GroupListResp, error)
		GroupUsers(ctx context.Context, in *GroupUsersReq, opts ...grpc.CallOption) (*GroupUsersResp, error)
		FindGroupList(ctx context.Context, in *FindGroupListReq, opts ...grpc.CallOption) (*FindGroupListResp, error)
	}

	defaultSocial struct {
		cli zrpc.Client
	}
)

func NewSocial(cli zrpc.Client) Social {
	return &defaultSocial{
		cli: cli,
	}
}

// 好友业务：请求好友、通过或拒绝申请、好友列表
func (m *defaultSocial) FriendPutIn(ctx context.Context, in *FriendPutInReq, opts ...grpc.CallOption) (*FriendPutInResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPutIn(ctx, in, opts...)
}

func (m *defaultSocial) FriendPutInHandle(ctx context.Context, in *FriendPutInHandleReq, opts ...grpc.CallOption) (*FriendPutInHandleResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPutInHandle(ctx, in, opts...)
}

func (m *defaultSocial) FriendPutInList(ctx context.Context, in *FriendPutInListReq, opts ...grpc.CallOption) (*FriendPutInListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPutInList(ctx, in, opts...)
}

func (m *defaultSocial) FriendPutInMessageCount(ctx context.Context, in *FriendPutInMessageCountReq, opts ...grpc.CallOption) (*FriendPutInMessageCountResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPutInMessageCount(ctx, in, opts...)
}

func (m *defaultSocial) FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendList(ctx, in, opts...)
}

func (m *defaultSocial) FriendUpdateRemark(ctx context.Context, in *FriendUpdateRemarkReq, opts ...grpc.CallOption) (*FriendUpdateRemarkResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendUpdateRemark(ctx, in, opts...)
}

func (m *defaultSocial) FriendDelete(ctx context.Context, in *FriendDeleteReq, opts ...grpc.CallOption) (*FriendDeleteResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendDelete(ctx, in, opts...)
}

func (m *defaultSocial) FriendBlock(ctx context.Context, in *FriendBlockReq, opts ...grpc.CallOption) (*FriendBlockResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendBlock(ctx, in, opts...)
}

func (m *defaultSocial) FriendMomentsPermission(ctx context.Context, in *FriendMomentsPermissionReq, opts ...grpc.CallOption) (*FriendMomentsPermissionResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendMomentsPermission(ctx, in, opts...)
}

func (m *defaultSocial) FriendNotification(ctx context.Context, in *FriendNotificationReq, opts ...grpc.CallOption) (*FriendNotificationResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendNotification(ctx, in, opts...)
}

func (m *defaultSocial) FriendPin(ctx context.Context, in *FriendPinReq, opts ...grpc.CallOption) (*FriendPinResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPin(ctx, in, opts...)
}

func (m *defaultSocial) FriendMute(ctx context.Context, in *FriendMuteReq, opts ...grpc.CallOption) (*FriendMuteResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendMute(ctx, in, opts...)
}

func (m *defaultSocial) FriendTags(ctx context.Context, in *FriendTagsReq, opts ...grpc.CallOption) (*FriendTagsResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendTags(ctx, in, opts...)
}

func (m *defaultSocial) FriendReport(ctx context.Context, in *FriendReportReq, opts ...grpc.CallOption) (*FriendReportResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendReport(ctx, in, opts...)
}

func (m *defaultSocial) FriendShare(ctx context.Context, in *FriendShareReq, opts ...grpc.CallOption) (*FriendShareResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendShare(ctx, in, opts...)
}

// 群业务：创建群，修改群，群公告，申请群，用户群列表，群成员，申请群，群退出..
func (m *defaultSocial) GroupCreate(ctx context.Context, in *GroupCreateReq, opts ...grpc.CallOption) (*GroupCreateResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupCreate(ctx, in, opts...)
}

func (m *defaultSocial) GroupPutin(ctx context.Context, in *GroupPutinReq, opts ...grpc.CallOption) (*GroupPutinResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupPutin(ctx, in, opts...)
}

func (m *defaultSocial) GroupPutinList(ctx context.Context, in *GroupPutinListReq, opts ...grpc.CallOption) (*GroupPutinListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupPutinList(ctx, in, opts...)
}

func (m *defaultSocial) GroupPutInHandle(ctx context.Context, in *GroupPutInHandleReq, opts ...grpc.CallOption) (*GroupPutInHandleResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupPutInHandle(ctx, in, opts...)
}

func (m *defaultSocial) GroupList(ctx context.Context, in *GroupListReq, opts ...grpc.CallOption) (*GroupListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupList(ctx, in, opts...)
}

func (m *defaultSocial) GroupUsers(ctx context.Context, in *GroupUsersReq, opts ...grpc.CallOption) (*GroupUsersResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupUsers(ctx, in, opts...)
}

func (m *defaultSocial) FindGroupList(ctx context.Context, in *FindGroupListReq, opts ...grpc.CallOption) (*FindGroupListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FindGroupList(ctx, in, opts...)
}
