// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: social.proto

package socialclient

import (
	"context"

	"github.com/iceymoss/go-hichat-api/apps/social/rpc/social"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AtMember                       = social.AtMember
	ExpireGroupInvitationsReq      = social.ExpireGroupInvitationsReq
	ExpireGroupInvitationsResp     = social.ExpireGroupInvitationsResp
	FindGroupListReq               = social.FindGroupListReq
	FindGroupListResp              = social.FindGroupListResp
	FriendBlockReq                 = social.FriendBlockReq
	FriendBlockResp                = social.FriendBlockResp
	FriendDeleteReq                = social.FriendDeleteReq
	FriendDeleteResp               = social.FriendDeleteResp
	FriendListReq                  = social.FriendListReq
	FriendListResp                 = social.FriendListResp
	FriendMomentsPermissionReq     = social.FriendMomentsPermissionReq
	FriendMomentsPermissionResp    = social.FriendMomentsPermissionResp
	FriendMuteReq                  = social.FriendMuteReq
	FriendMuteResp                 = social.FriendMuteResp
	FriendNotificationReq          = social.FriendNotificationReq
	FriendNotificationResp         = social.FriendNotificationResp
	FriendPinReq                   = social.FriendPinReq
	FriendPinResp                  = social.FriendPinResp
	FriendPutInDeleteReq           = social.FriendPutInDeleteReq
	FriendPutInDeleteResp          = social.FriendPutInDeleteResp
	FriendPutInHandleReq           = social.FriendPutInHandleReq
	FriendPutInHandleResp          = social.FriendPutInHandleResp
	FriendPutInListReq             = social.FriendPutInListReq
	FriendPutInListResp            = social.FriendPutInListResp
	FriendPutInMessageCountReq     = social.FriendPutInMessageCountReq
	FriendPutInMessageCountResp    = social.FriendPutInMessageCountResp
	FriendPutInReadReq             = social.FriendPutInReadReq
	FriendPutInReadResp            = social.FriendPutInReadResp
	FriendPutInReq                 = social.FriendPutInReq
	FriendPutInResp                = social.FriendPutInResp
	FriendReportReq                = social.FriendReportReq
	FriendReportResp               = social.FriendReportResp
	FriendRequests                 = social.FriendRequests
	FriendShareReq                 = social.FriendShareReq
	FriendShareResp                = social.FriendShareResp
	FriendTagsReq                  = social.FriendTagsReq
	FriendTagsResp                 = social.FriendTagsResp
	FriendUpdateRemarkReq          = social.FriendUpdateRemarkReq
	FriendUpdateRemarkResp         = social.FriendUpdateRemarkResp
	Friends                        = social.Friends
	GetGroupPutListByUidReq        = social.GetGroupPutListByUidReq
	GetMemberRoleReq               = social.GetMemberRoleReq
	GetMemberRoleResp              = social.GetMemberRoleResp
	GetMyGroupMemberSettingReq     = social.GetMyGroupMemberSettingReq
	GetMyGroupMemberSettingResp    = social.GetMyGroupMemberSettingResp
	GroupAnnouncement              = social.GroupAnnouncement
	GroupAnnouncementCreateReq     = social.GroupAnnouncementCreateReq
	GroupAnnouncementCreateResp    = social.GroupAnnouncementCreateResp
	GroupAnnouncementListReq       = social.GroupAnnouncementListReq
	GroupAnnouncementListResp      = social.GroupAnnouncementListResp
	GroupAnnouncementPinReq        = social.GroupAnnouncementPinReq
	GroupAnnouncementPinResp       = social.GroupAnnouncementPinResp
	GroupAtListReq                 = social.GroupAtListReq
	GroupAtListResp                = social.GroupAtListResp
	GroupCreateReq                 = social.GroupCreateReq
	GroupCreateResp                = social.GroupCreateResp
	GroupDetailReq                 = social.GroupDetailReq
	GroupDetailResp                = social.GroupDetailResp
	GroupDisbandReq                = social.GroupDisbandReq
	GroupDisbandResp               = social.GroupDisbandResp
	GroupInvitation                = social.GroupInvitation
	GroupInvitationCreateReq       = social.GroupInvitationCreateReq
	GroupInvitationCreateResp      = social.GroupInvitationCreateResp
	GroupInvitationHandleReq       = social.GroupInvitationHandleReq
	GroupInvitationHandleResp      = social.GroupInvitationHandleResp
	GroupInvitationListReq         = social.GroupInvitationListReq
	GroupInvitationListResp        = social.GroupInvitationListResp
	GroupInvitationReadReq         = social.GroupInvitationReadReq
	GroupInvitationReadResp        = social.GroupInvitationReadResp
	GroupInviteLink                = social.GroupInviteLink
	GroupInviteLinkCreateReq       = social.GroupInviteLinkCreateReq
	GroupInviteLinkCreateResp      = social.GroupInviteLinkCreateResp
	GroupInviteLinkListReq         = social.GroupInviteLinkListReq
	GroupInviteLinkListResp        = social.GroupInviteLinkListResp
	GroupInviteLinkRevokeReq       = social.GroupInviteLinkRevokeReq
	GroupInviteLinkRevokeResp      = social.GroupInviteLinkRevokeResp
	GroupInviteReq                 = social.GroupInviteReq
	GroupInviteResp                = social.GroupInviteResp
	GroupJoinByTokenReq            = social.GroupJoinByTokenReq
	GroupJoinByTokenResp           = social.GroupJoinByTokenResp
	GroupKickReq                   = social.GroupKickReq
	GroupKickResp                  = social.GroupKickResp
	GroupListReq                   = social.GroupListReq
	GroupListResp                  = social.GroupListResp
	GroupMemberSetting             = social.GroupMemberSetting
	GroupMembers                   = social.GroupMembers
	GroupPutInHandleReq            = social.GroupPutInHandleReq
	GroupPutInHandleResp           = social.GroupPutInHandleResp
	GroupPutinListReq              = social.GroupPutinListReq
	GroupPutinListResp             = social.GroupPutinListResp
	GroupPutinReq                  = social.GroupPutinReq
	GroupPutinResp                 = social.GroupPutinResp
	GroupQuitReq                   = social.GroupQuitReq
	GroupQuitResp                  = social.GroupQuitResp
	GroupRequestMessageCountReq    = social.GroupRequestMessageCountReq
	GroupRequestMessageCountResp   = social.GroupRequestMessageCountResp
	GroupRequests                  = social.GroupRequests
	GroupSearchItem                = social.GroupSearchItem
	GroupSearchReq                 = social.GroupSearchReq
	GroupSearchResp                = social.GroupSearchResp
	GroupSetAdminReq               = social.GroupSetAdminReq
	GroupSetAdminResp              = social.GroupSetAdminResp
	GroupTransferOwnerReq          = social.GroupTransferOwnerReq
	GroupTransferOwnerResp         = social.GroupTransferOwnerResp
	GroupUpdateReq                 = social.GroupUpdateReq
	GroupUpdateResp                = social.GroupUpdateResp
	GroupUsersReq                  = social.GroupUsersReq
	GroupUsersResp                 = social.GroupUsersResp
	Groups                         = social.Groups
	MarkGroupReqReadReq            = social.MarkGroupReqReadReq
	MarkGroupReqReadResp           = social.MarkGroupReqReadResp
	UpdateMyGroupMemberSettingReq  = social.UpdateMyGroupMemberSettingReq
	UpdateMyGroupMemberSettingResp = social.UpdateMyGroupMemberSettingResp

	Social interface {
		// 好友业务：请求好友、通过或拒绝申请、好友列表
		FriendPutIn(ctx context.Context, in *FriendPutInReq, opts ...grpc.CallOption) (*FriendPutInResp, error)
		FriendPutInHandle(ctx context.Context, in *FriendPutInHandleReq, opts ...grpc.CallOption) (*FriendPutInHandleResp, error)
		FriendPutInRead(ctx context.Context, in *FriendPutInReadReq, opts ...grpc.CallOption) (*FriendPutInReadResp, error)
		FriendPutInDelete(ctx context.Context, in *FriendPutInDeleteReq, opts ...grpc.CallOption) (*FriendPutInDeleteResp, error)
		FriendPutInList(ctx context.Context, in *FriendPutInListReq, opts ...grpc.CallOption) (*FriendPutInListResp, error)
		FriendPutInMessageCount(ctx context.Context, in *FriendPutInMessageCountReq, opts ...grpc.CallOption) (*FriendPutInMessageCountResp, error)
		FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error)
		FriendUpdateRemark(ctx context.Context, in *FriendUpdateRemarkReq, opts ...grpc.CallOption) (*FriendUpdateRemarkResp, error)
		FriendDelete(ctx context.Context, in *FriendDeleteReq, opts ...grpc.CallOption) (*FriendDeleteResp, error)
		FriendBlock(ctx context.Context, in *FriendBlockReq, opts ...grpc.CallOption) (*FriendBlockResp, error)
		FriendMomentsPermission(ctx context.Context, in *FriendMomentsPermissionReq, opts ...grpc.CallOption) (*FriendMomentsPermissionResp, error)
		FriendNotification(ctx context.Context, in *FriendNotificationReq, opts ...grpc.CallOption) (*FriendNotificationResp, error)
		FriendPin(ctx context.Context, in *FriendPinReq, opts ...grpc.CallOption) (*FriendPinResp, error)
		FriendMute(ctx context.Context, in *FriendMuteReq, opts ...grpc.CallOption) (*FriendMuteResp, error)
		FriendTags(ctx context.Context, in *FriendTagsReq, opts ...grpc.CallOption) (*FriendTagsResp, error)
		FriendReport(ctx context.Context, in *FriendReportReq, opts ...grpc.CallOption) (*FriendReportResp, error)
		FriendShare(ctx context.Context, in *FriendShareReq, opts ...grpc.CallOption) (*FriendShareResp, error)
		// 群业务：创建群，修改群，群公告，申请群，用户群列表，群成员，申请群，群退出..
		GroupCreate(ctx context.Context, in *GroupCreateReq, opts ...grpc.CallOption) (*GroupCreateResp, error)
		GroupPutin(ctx context.Context, in *GroupPutinReq, opts ...grpc.CallOption) (*GroupPutinResp, error)
		GroupPutinList(ctx context.Context, in *GroupPutinListReq, opts ...grpc.CallOption) (*GroupPutinListResp, error)
		GetGroupPutListByUid(ctx context.Context, in *GetGroupPutListByUidReq, opts ...grpc.CallOption) (*GroupPutinListResp, error)
		MarkGroupReqRead(ctx context.Context, in *MarkGroupReqReadReq, opts ...grpc.CallOption) (*MarkGroupReqReadResp, error)
		GroupPutInHandle(ctx context.Context, in *GroupPutInHandleReq, opts ...grpc.CallOption) (*GroupPutInHandleResp, error)
		GroupList(ctx context.Context, in *GroupListReq, opts ...grpc.CallOption) (*GroupListResp, error)
		GroupUsers(ctx context.Context, in *GroupUsersReq, opts ...grpc.CallOption) (*GroupUsersResp, error)
		FindGroupList(ctx context.Context, in *FindGroupListReq, opts ...grpc.CallOption) (*FindGroupListResp, error)
		GroupSearch(ctx context.Context, in *GroupSearchReq, opts ...grpc.CallOption) (*GroupSearchResp, error)
		GroupQuit(ctx context.Context, in *GroupQuitReq, opts ...grpc.CallOption) (*GroupQuitResp, error)
		GroupKick(ctx context.Context, in *GroupKickReq, opts ...grpc.CallOption) (*GroupKickResp, error)
		GroupUpdate(ctx context.Context, in *GroupUpdateReq, opts ...grpc.CallOption) (*GroupUpdateResp, error)
		GroupDetail(ctx context.Context, in *GroupDetailReq, opts ...grpc.CallOption) (*GroupDetailResp, error)
		GroupDisband(ctx context.Context, in *GroupDisbandReq, opts ...grpc.CallOption) (*GroupDisbandResp, error)
		GroupTransferOwner(ctx context.Context, in *GroupTransferOwnerReq, opts ...grpc.CallOption) (*GroupTransferOwnerResp, error)
		GroupSetAdmin(ctx context.Context, in *GroupSetAdminReq, opts ...grpc.CallOption) (*GroupSetAdminResp, error)
		GroupInvite(ctx context.Context, in *GroupInviteReq, opts ...grpc.CallOption) (*GroupInviteResp, error)
		// 邀请链接/二维码入群
		GroupInviteLinkCreate(ctx context.Context, in *GroupInviteLinkCreateReq, opts ...grpc.CallOption) (*GroupInviteLinkCreateResp, error)
		GroupInviteLinkList(ctx context.Context, in *GroupInviteLinkListReq, opts ...grpc.CallOption) (*GroupInviteLinkListResp, error)
		GroupInviteLinkRevoke(ctx context.Context, in *GroupInviteLinkRevokeReq, opts ...grpc.CallOption) (*GroupInviteLinkRevokeResp, error)
		GroupJoinByToken(ctx context.Context, in *GroupJoinByTokenReq, opts ...grpc.CallOption) (*GroupJoinByTokenResp, error)
		// 群成员资料（群内昵称/群备注/@列表）
		GetMyGroupMemberSetting(ctx context.Context, in *GetMyGroupMemberSettingReq, opts ...grpc.CallOption) (*GetMyGroupMemberSettingResp, error)
		UpdateMyGroupMemberSetting(ctx context.Context, in *UpdateMyGroupMemberSettingReq, opts ...grpc.CallOption) (*UpdateMyGroupMemberSettingResp, error)
		GroupAtList(ctx context.Context, in *GroupAtListReq, opts ...grpc.CallOption) (*GroupAtListResp, error)
		GetMemberRole(ctx context.Context, in *GetMemberRoleReq, opts ...grpc.CallOption) (*GetMemberRoleResp, error)
		// 公告历史/置顶
		GroupAnnouncementCreate(ctx context.Context, in *GroupAnnouncementCreateReq, opts ...grpc.CallOption) (*GroupAnnouncementCreateResp, error)
		GroupAnnouncementList(ctx context.Context, in *GroupAnnouncementListReq, opts ...grpc.CallOption) (*GroupAnnouncementListResp, error)
		GroupAnnouncementPin(ctx context.Context, in *GroupAnnouncementPinReq, opts ...grpc.CallOption) (*GroupAnnouncementPinResp, error)
		GroupInvitationCreate(ctx context.Context, in *GroupInvitationCreateReq, opts ...grpc.CallOption) (*GroupInvitationCreateResp, error)
		GroupInvitationList(ctx context.Context, in *GroupInvitationListReq, opts ...grpc.CallOption) (*GroupInvitationListResp, error)
		GroupInvitationRead(ctx context.Context, in *GroupInvitationReadReq, opts ...grpc.CallOption) (*GroupInvitationReadResp, error)
		GroupRequestMessageCount(ctx context.Context, in *GroupRequestMessageCountReq, opts ...grpc.CallOption) (*GroupRequestMessageCountResp, error)
		GroupInvitationHandle(ctx context.Context, in *GroupInvitationHandleReq, opts ...grpc.CallOption) (*GroupInvitationHandleResp, error)
		ExpireGroupInvitations(ctx context.Context, in *ExpireGroupInvitationsReq, opts ...grpc.CallOption) (*ExpireGroupInvitationsResp, error)
	}

	defaultSocial struct {
		cli zrpc.Client
	}
)

func NewSocial(cli zrpc.Client) Social {
	return &defaultSocial{
		cli: cli,
	}
}

// 好友业务：请求好友、通过或拒绝申请、好友列表
func (m *defaultSocial) FriendPutIn(ctx context.Context, in *FriendPutInReq, opts ...grpc.CallOption) (*FriendPutInResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPutIn(ctx, in, opts...)
}

func (m *defaultSocial) FriendPutInHandle(ctx context.Context, in *FriendPutInHandleReq, opts ...grpc.CallOption) (*FriendPutInHandleResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPutInHandle(ctx, in, opts...)
}

func (m *defaultSocial) FriendPutInRead(ctx context.Context, in *FriendPutInReadReq, opts ...grpc.CallOption) (*FriendPutInReadResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPutInRead(ctx, in, opts...)
}

func (m *defaultSocial) FriendPutInDelete(ctx context.Context, in *FriendPutInDeleteReq, opts ...grpc.CallOption) (*FriendPutInDeleteResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPutInDelete(ctx, in, opts...)
}

func (m *defaultSocial) FriendPutInList(ctx context.Context, in *FriendPutInListReq, opts ...grpc.CallOption) (*FriendPutInListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPutInList(ctx, in, opts...)
}

func (m *defaultSocial) FriendPutInMessageCount(ctx context.Context, in *FriendPutInMessageCountReq, opts ...grpc.CallOption) (*FriendPutInMessageCountResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPutInMessageCount(ctx, in, opts...)
}

func (m *defaultSocial) FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendList(ctx, in, opts...)
}

func (m *defaultSocial) FriendUpdateRemark(ctx context.Context, in *FriendUpdateRemarkReq, opts ...grpc.CallOption) (*FriendUpdateRemarkResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendUpdateRemark(ctx, in, opts...)
}

func (m *defaultSocial) FriendDelete(ctx context.Context, in *FriendDeleteReq, opts ...grpc.CallOption) (*FriendDeleteResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendDelete(ctx, in, opts...)
}

func (m *defaultSocial) FriendBlock(ctx context.Context, in *FriendBlockReq, opts ...grpc.CallOption) (*FriendBlockResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendBlock(ctx, in, opts...)
}

func (m *defaultSocial) FriendMomentsPermission(ctx context.Context, in *FriendMomentsPermissionReq, opts ...grpc.CallOption) (*FriendMomentsPermissionResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendMomentsPermission(ctx, in, opts...)
}

func (m *defaultSocial) FriendNotification(ctx context.Context, in *FriendNotificationReq, opts ...grpc.CallOption) (*FriendNotificationResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendNotification(ctx, in, opts...)
}

func (m *defaultSocial) FriendPin(ctx context.Context, in *FriendPinReq, opts ...grpc.CallOption) (*FriendPinResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPin(ctx, in, opts...)
}

func (m *defaultSocial) FriendMute(ctx context.Context, in *FriendMuteReq, opts ...grpc.CallOption) (*FriendMuteResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendMute(ctx, in, opts...)
}

func (m *defaultSocial) FriendTags(ctx context.Context, in *FriendTagsReq, opts ...grpc.CallOption) (*FriendTagsResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendTags(ctx, in, opts...)
}

func (m *defaultSocial) FriendReport(ctx context.Context, in *FriendReportReq, opts ...grpc.CallOption) (*FriendReportResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendReport(ctx, in, opts...)
}

func (m *defaultSocial) FriendShare(ctx context.Context, in *FriendShareReq, opts ...grpc.CallOption) (*FriendShareResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendShare(ctx, in, opts...)
}

// 群业务：创建群，修改群，群公告，申请群，用户群列表，群成员，申请群，群退出..
func (m *defaultSocial) GroupCreate(ctx context.Context, in *GroupCreateReq, opts ...grpc.CallOption) (*GroupCreateResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupCreate(ctx, in, opts...)
}

func (m *defaultSocial) GroupPutin(ctx context.Context, in *GroupPutinReq, opts ...grpc.CallOption) (*GroupPutinResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupPutin(ctx, in, opts...)
}

func (m *defaultSocial) GroupPutinList(ctx context.Context, in *GroupPutinListReq, opts ...grpc.CallOption) (*GroupPutinListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupPutinList(ctx, in, opts...)
}

func (m *defaultSocial) GetGroupPutListByUid(ctx context.Context, in *GetGroupPutListByUidReq, opts ...grpc.CallOption) (*GroupPutinListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GetGroupPutListByUid(ctx, in, opts...)
}

func (m *defaultSocial) MarkGroupReqRead(ctx context.Context, in *MarkGroupReqReadReq, opts ...grpc.CallOption) (*MarkGroupReqReadResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.MarkGroupReqRead(ctx, in, opts...)
}

func (m *defaultSocial) GroupPutInHandle(ctx context.Context, in *GroupPutInHandleReq, opts ...grpc.CallOption) (*GroupPutInHandleResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupPutInHandle(ctx, in, opts...)
}

func (m *defaultSocial) GroupList(ctx context.Context, in *GroupListReq, opts ...grpc.CallOption) (*GroupListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupList(ctx, in, opts...)
}

func (m *defaultSocial) GroupUsers(ctx context.Context, in *GroupUsersReq, opts ...grpc.CallOption) (*GroupUsersResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupUsers(ctx, in, opts...)
}

func (m *defaultSocial) FindGroupList(ctx context.Context, in *FindGroupListReq, opts ...grpc.CallOption) (*FindGroupListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FindGroupList(ctx, in, opts...)
}

func (m *defaultSocial) GroupSearch(ctx context.Context, in *GroupSearchReq, opts ...grpc.CallOption) (*GroupSearchResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupSearch(ctx, in, opts...)
}

func (m *defaultSocial) GroupQuit(ctx context.Context, in *GroupQuitReq, opts ...grpc.CallOption) (*GroupQuitResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupQuit(ctx, in, opts...)
}

func (m *defaultSocial) GroupKick(ctx context.Context, in *GroupKickReq, opts ...grpc.CallOption) (*GroupKickResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupKick(ctx, in, opts...)
}

func (m *defaultSocial) GroupUpdate(ctx context.Context, in *GroupUpdateReq, opts ...grpc.CallOption) (*GroupUpdateResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupUpdate(ctx, in, opts...)
}

func (m *defaultSocial) GroupDetail(ctx context.Context, in *GroupDetailReq, opts ...grpc.CallOption) (*GroupDetailResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupDetail(ctx, in, opts...)
}

func (m *defaultSocial) GroupDisband(ctx context.Context, in *GroupDisbandReq, opts ...grpc.CallOption) (*GroupDisbandResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupDisband(ctx, in, opts...)
}

func (m *defaultSocial) GroupTransferOwner(ctx context.Context, in *GroupTransferOwnerReq, opts ...grpc.CallOption) (*GroupTransferOwnerResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupTransferOwner(ctx, in, opts...)
}

func (m *defaultSocial) GroupSetAdmin(ctx context.Context, in *GroupSetAdminReq, opts ...grpc.CallOption) (*GroupSetAdminResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupSetAdmin(ctx, in, opts...)
}

func (m *defaultSocial) GroupInvite(ctx context.Context, in *GroupInviteReq, opts ...grpc.CallOption) (*GroupInviteResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupInvite(ctx, in, opts...)
}

// 邀请链接/二维码入群
func (m *defaultSocial) GroupInviteLinkCreate(ctx context.Context, in *GroupInviteLinkCreateReq, opts ...grpc.CallOption) (*GroupInviteLinkCreateResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupInviteLinkCreate(ctx, in, opts...)
}

func (m *defaultSocial) GroupInviteLinkList(ctx context.Context, in *GroupInviteLinkListReq, opts ...grpc.CallOption) (*GroupInviteLinkListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupInviteLinkList(ctx, in, opts...)
}

func (m *defaultSocial) GroupInviteLinkRevoke(ctx context.Context, in *GroupInviteLinkRevokeReq, opts ...grpc.CallOption) (*GroupInviteLinkRevokeResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupInviteLinkRevoke(ctx, in, opts...)
}

func (m *defaultSocial) GroupJoinByToken(ctx context.Context, in *GroupJoinByTokenReq, opts ...grpc.CallOption) (*GroupJoinByTokenResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupJoinByToken(ctx, in, opts...)
}

// 群成员资料（群内昵称/群备注/@列表）
func (m *defaultSocial) GetMyGroupMemberSetting(ctx context.Context, in *GetMyGroupMemberSettingReq, opts ...grpc.CallOption) (*GetMyGroupMemberSettingResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GetMyGroupMemberSetting(ctx, in, opts...)
}

func (m *defaultSocial) UpdateMyGroupMemberSetting(ctx context.Context, in *UpdateMyGroupMemberSettingReq, opts ...grpc.CallOption) (*UpdateMyGroupMemberSettingResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.UpdateMyGroupMemberSetting(ctx, in, opts...)
}

func (m *defaultSocial) GroupAtList(ctx context.Context, in *GroupAtListReq, opts ...grpc.CallOption) (*GroupAtListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupAtList(ctx, in, opts...)
}

func (m *defaultSocial) GetMemberRole(ctx context.Context, in *GetMemberRoleReq, opts ...grpc.CallOption) (*GetMemberRoleResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GetMemberRole(ctx, in, opts...)
}

// 公告历史/置顶
func (m *defaultSocial) GroupAnnouncementCreate(ctx context.Context, in *GroupAnnouncementCreateReq, opts ...grpc.CallOption) (*GroupAnnouncementCreateResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupAnnouncementCreate(ctx, in, opts...)
}

func (m *defaultSocial) GroupAnnouncementList(ctx context.Context, in *GroupAnnouncementListReq, opts ...grpc.CallOption) (*GroupAnnouncementListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupAnnouncementList(ctx, in, opts...)
}

func (m *defaultSocial) GroupAnnouncementPin(ctx context.Context, in *GroupAnnouncementPinReq, opts ...grpc.CallOption) (*GroupAnnouncementPinResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupAnnouncementPin(ctx, in, opts...)
}

func (m *defaultSocial) GroupInvitationCreate(ctx context.Context, in *GroupInvitationCreateReq, opts ...grpc.CallOption) (*GroupInvitationCreateResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupInvitationCreate(ctx, in, opts...)
}

func (m *defaultSocial) GroupInvitationList(ctx context.Context, in *GroupInvitationListReq, opts ...grpc.CallOption) (*GroupInvitationListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupInvitationList(ctx, in, opts...)
}

func (m *defaultSocial) GroupInvitationRead(ctx context.Context, in *GroupInvitationReadReq, opts ...grpc.CallOption) (*GroupInvitationReadResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupInvitationRead(ctx, in, opts...)
}

func (m *defaultSocial) GroupRequestMessageCount(ctx context.Context, in *GroupRequestMessageCountReq, opts ...grpc.CallOption) (*GroupRequestMessageCountResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupRequestMessageCount(ctx, in, opts...)
}

func (m *defaultSocial) GroupInvitationHandle(ctx context.Context, in *GroupInvitationHandleReq, opts ...grpc.CallOption) (*GroupInvitationHandleResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupInvitationHandle(ctx, in, opts...)
}

func (m *defaultSocial) ExpireGroupInvitations(ctx context.Context, in *ExpireGroupInvitationsReq, opts ...grpc.CallOption) (*ExpireGroupInvitationsResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.ExpireGroupInvitations(ctx, in, opts...)
}
