// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: im.proto

package im

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Im_GetChatLog_FullMethodName                 = "/im.Im/GetChatLog"
	Im_SetUpUserConversation_FullMethodName      = "/im.Im/SetUpUserConversation"
	Im_GetConversations_FullMethodName           = "/im.Im/GetConversations"
	Im_PutConversations_FullMethodName           = "/im.Im/PutConversations"
	Im_CreateGroupConversation_FullMethodName    = "/im.Im/CreateGroupConversation"
	Im_SetConversationSettings_FullMethodName    = "/im.Im/SetConversationSettings"
	Im_RecallMsg_FullMethodName                  = "/im.Im/RecallMsg"
	Im_GetAtMeMessages_FullMethodName            = "/im.Im/GetAtMeMessages"
	Im_CreateNotification_FullMethodName         = "/im.Im/CreateNotification"
	Im_ListNotifications_FullMethodName          = "/im.Im/ListNotifications"
	Im_MarkNotificationsRead_FullMethodName      = "/im.Im/MarkNotificationsRead"
	Im_GetUnreadNotificationCount_FullMethodName = "/im.Im/GetUnreadNotificationCount"
	Im_EnsureGroupConversation_FullMethodName    = "/im.Im/EnsureGroupConversation"
)

// ImClient is the client API for Im service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImClient interface {
	// 获取会话记录
	GetChatLog(ctx context.Context, in *GetChatLogReq, opts ...grpc.CallOption) (*GetChatLogResp, error)
	// 建立会话: 群聊, 私聊
	SetUpUserConversation(ctx context.Context, in *SetUpUserConversationReq, opts ...grpc.CallOption) (*SetUpUserConversationResp, error)
	// 获取会话
	GetConversations(ctx context.Context, in *GetConversationsReq, opts ...grpc.CallOption) (*GetConversationsResp, error)
	// 更新会话
	PutConversations(ctx context.Context, in *PutConversationsReq, opts ...grpc.CallOption) (*PutConversationsResp, error)
	// 创建群会话
	CreateGroupConversation(ctx context.Context, in *CreateGroupConversationReq, opts ...grpc.CallOption) (*CreateGroupConversationResp, error)
	// 设置会话置顶/免打扰
	SetConversationSettings(ctx context.Context, in *SetConversationSettingsReq, opts ...grpc.CallOption) (*SetConversationSettingsResp, error)
	// 撤回消息（本人限时 / 群管理员不限时）
	RecallMsg(ctx context.Context, in *RecallMsgReq, opts ...grpc.CallOption) (*RecallMsgResp, error)
	// 获取会话中 @我 且未读的消息列表（用于"有人@我"快速跳转）
	GetAtMeMessages(ctx context.Context, in *GetAtMeMessagesReq, opts ...grpc.CallOption) (*GetAtMeMessagesResp, error)
	// 公共通知通道：落库一条通知（幂等）
	CreateNotification(ctx context.Context, in *CreateNotificationReq, opts ...grpc.CallOption) (*CreateNotificationResp, error)
	// 公共通知通道：拉取接收者通知列表（分页）
	ListNotifications(ctx context.Context, in *ListNotificationsReq, opts ...grpc.CallOption) (*ListNotificationsResp, error)
	// 公共通知通道：标记通知已读（单条/批量/全部）
	MarkNotificationsRead(ctx context.Context, in *MarkNotificationsReadReq, opts ...grpc.CallOption) (*MarkNotificationsReadResp, error)
	// 公共通知通道：接收者未读数
	GetUnreadNotificationCount(ctx context.Context, in *GetUnreadNotificationCountReq, opts ...grpc.CallOption) (*GetUnreadNotificationCountResp, error)
	EnsureGroupConversation(ctx context.Context, in *EnsureGroupConversationReq, opts ...grpc.CallOption) (*EnsureGroupConversationResp, error)
}

type imClient struct {
	cc grpc.ClientConnInterface
}

func NewImClient(cc grpc.ClientConnInterface) ImClient {
	return &imClient{cc}
}

func (c *imClient) GetChatLog(ctx context.Context, in *GetChatLogReq, opts ...grpc.CallOption) (*GetChatLogResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatLogResp)
	err := c.cc.Invoke(ctx, Im_GetChatLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imClient) SetUpUserConversation(ctx context.Context, in *SetUpUserConversationReq, opts ...grpc.CallOption) (*SetUpUserConversationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUpUserConversationResp)
	err := c.cc.Invoke(ctx, Im_SetUpUserConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imClient) GetConversations(ctx context.Context, in *GetConversationsReq, opts ...grpc.CallOption) (*GetConversationsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConversationsResp)
	err := c.cc.Invoke(ctx, Im_GetConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imClient) PutConversations(ctx context.Context, in *PutConversationsReq, opts ...grpc.CallOption) (*PutConversationsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutConversationsResp)
	err := c.cc.Invoke(ctx, Im_PutConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imClient) CreateGroupConversation(ctx context.Context, in *CreateGroupConversationReq, opts ...grpc.CallOption) (*CreateGroupConversationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupConversationResp)
	err := c.cc.Invoke(ctx, Im_CreateGroupConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imClient) SetConversationSettings(ctx context.Context, in *SetConversationSettingsReq, opts ...grpc.CallOption) (*SetConversationSettingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetConversationSettingsResp)
	err := c.cc.Invoke(ctx, Im_SetConversationSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imClient) RecallMsg(ctx context.Context, in *RecallMsgReq, opts ...grpc.CallOption) (*RecallMsgResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecallMsgResp)
	err := c.cc.Invoke(ctx, Im_RecallMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imClient) GetAtMeMessages(ctx context.Context, in *GetAtMeMessagesReq, opts ...grpc.CallOption) (*GetAtMeMessagesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAtMeMessagesResp)
	err := c.cc.Invoke(ctx, Im_GetAtMeMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imClient) CreateNotification(ctx context.Context, in *CreateNotificationReq, opts ...grpc.CallOption) (*CreateNotificationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNotificationResp)
	err := c.cc.Invoke(ctx, Im_CreateNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imClient) ListNotifications(ctx context.Context, in *ListNotificationsReq, opts ...grpc.CallOption) (*ListNotificationsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotificationsResp)
	err := c.cc.Invoke(ctx, Im_ListNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imClient) MarkNotificationsRead(ctx context.Context, in *MarkNotificationsReadReq, opts ...grpc.CallOption) (*MarkNotificationsReadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkNotificationsReadResp)
	err := c.cc.Invoke(ctx, Im_MarkNotificationsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imClient) GetUnreadNotificationCount(ctx context.Context, in *GetUnreadNotificationCountReq, opts ...grpc.CallOption) (*GetUnreadNotificationCountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnreadNotificationCountResp)
	err := c.cc.Invoke(ctx, Im_GetUnreadNotificationCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imClient) EnsureGroupConversation(ctx context.Context, in *EnsureGroupConversationReq, opts ...grpc.CallOption) (*EnsureGroupConversationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureGroupConversationResp)
	err := c.cc.Invoke(ctx, Im_EnsureGroupConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImServer is the server API for Im service.
// All implementations must embed UnimplementedImServer
// for forward compatibility.
type ImServer interface {
	// 获取会话记录
	GetChatLog(context.Context, *GetChatLogReq) (*GetChatLogResp, error)
	// 建立会话: 群聊, 私聊
	SetUpUserConversation(context.Context, *SetUpUserConversationReq) (*SetUpUserConversationResp, error)
	// 获取会话
	GetConversations(context.Context, *GetConversationsReq) (*GetConversationsResp, error)
	// 更新会话
	PutConversations(context.Context, *PutConversationsReq) (*PutConversationsResp, error)
	// 创建群会话
	CreateGroupConversation(context.Context, *CreateGroupConversationReq) (*CreateGroupConversationResp, error)
	// 设置会话置顶/免打扰
	SetConversationSettings(context.Context, *SetConversationSettingsReq) (*SetConversationSettingsResp, error)
	// 撤回消息（本人限时 / 群管理员不限时）
	RecallMsg(context.Context, *RecallMsgReq) (*RecallMsgResp, error)
	// 获取会话中 @我 且未读的消息列表（用于"有人@我"快速跳转）
	GetAtMeMessages(context.Context, *GetAtMeMessagesReq) (*GetAtMeMessagesResp, error)
	// 公共通知通道：落库一条通知（幂等）
	CreateNotification(context.Context, *CreateNotificationReq) (*CreateNotificationResp, error)
	// 公共通知通道：拉取接收者通知列表（分页）
	ListNotifications(context.Context, *ListNotificationsReq) (*ListNotificationsResp, error)
	// 公共通知通道：标记通知已读（单条/批量/全部）
	MarkNotificationsRead(context.Context, *MarkNotificationsReadReq) (*MarkNotificationsReadResp, error)
	// 公共通知通道：接收者未读数
	GetUnreadNotificationCount(context.Context, *GetUnreadNotificationCountReq) (*GetUnreadNotificationCountResp, error)
	EnsureGroupConversation(context.Context, *EnsureGroupConversationReq) (*EnsureGroupConversationResp, error)
	mustEmbedUnimplementedImServer()
}

// UnimplementedImServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImServer struct{}

func (UnimplementedImServer) GetChatLog(context.Context, *GetChatLogReq) (*GetChatLogResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatLog not implemented")
}
func (UnimplementedImServer) SetUpUserConversation(context.Context, *SetUpUserConversationReq) (*SetUpUserConversationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUpUserConversation not implemented")
}
func (UnimplementedImServer) GetConversations(context.Context, *GetConversationsReq) (*GetConversationsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversations not implemented")
}
func (UnimplementedImServer) PutConversations(context.Context, *PutConversationsReq) (*PutConversationsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutConversations not implemented")
}
func (UnimplementedImServer) CreateGroupConversation(context.Context, *CreateGroupConversationReq) (*CreateGroupConversationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroupConversation not implemented")
}
func (UnimplementedImServer) SetConversationSettings(context.Context, *SetConversationSettingsReq) (*SetConversationSettingsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConversationSettings not implemented")
}
func (UnimplementedImServer) RecallMsg(context.Context, *RecallMsgReq) (*RecallMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecallMsg not implemented")
}
func (UnimplementedImServer) GetAtMeMessages(context.Context, *GetAtMeMessagesReq) (*GetAtMeMessagesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAtMeMessages not implemented")
}
func (UnimplementedImServer) CreateNotification(context.Context, *CreateNotificationReq) (*CreateNotificationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNotification not implemented")
}
func (UnimplementedImServer) ListNotifications(context.Context, *ListNotificationsReq) (*ListNotificationsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNotifications not implemented")
}
func (UnimplementedImServer) MarkNotificationsRead(context.Context, *MarkNotificationsReadReq) (*MarkNotificationsReadResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkNotificationsRead not implemented")
}
func (UnimplementedImServer) GetUnreadNotificationCount(context.Context, *GetUnreadNotificationCountReq) (*GetUnreadNotificationCountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnreadNotificationCount not implemented")
}
func (UnimplementedImServer) EnsureGroupConversation(context.Context, *EnsureGroupConversationReq) (*EnsureGroupConversationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureGroupConversation not implemented")
}
func (UnimplementedImServer) mustEmbedUnimplementedImServer() {}
func (UnimplementedImServer) testEmbeddedByValue()            {}

// UnsafeImServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImServer will
// result in compilation errors.
type UnsafeImServer interface {
	mustEmbedUnimplementedImServer()
}

func RegisterImServer(s grpc.ServiceRegistrar, srv ImServer) {
	// If the following call pancis, it indicates UnimplementedImServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Im_ServiceDesc, srv)
}

func _Im_GetChatLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImServer).GetChatLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Im_GetChatLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImServer).GetChatLog(ctx, req.(*GetChatLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Im_SetUpUserConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUpUserConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImServer).SetUpUserConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Im_SetUpUserConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImServer).SetUpUserConversation(ctx, req.(*SetUpUserConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Im_GetConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImServer).GetConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Im_GetConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImServer).GetConversations(ctx, req.(*GetConversationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Im_PutConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutConversationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImServer).PutConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Im_PutConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImServer).PutConversations(ctx, req.(*PutConversationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Im_CreateGroupConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImServer).CreateGroupConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Im_CreateGroupConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImServer).CreateGroupConversation(ctx, req.(*CreateGroupConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Im_SetConversationSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConversationSettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImServer).SetConversationSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Im_SetConversationSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImServer).SetConversationSettings(ctx, req.(*SetConversationSettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Im_RecallMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecallMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImServer).RecallMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Im_RecallMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImServer).RecallMsg(ctx, req.(*RecallMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Im_GetAtMeMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAtMeMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImServer).GetAtMeMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Im_GetAtMeMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImServer).GetAtMeMessages(ctx, req.(*GetAtMeMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Im_CreateNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImServer).CreateNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Im_CreateNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImServer).CreateNotification(ctx, req.(*CreateNotificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Im_ListNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotificationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImServer).ListNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Im_ListNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImServer).ListNotifications(ctx, req.(*ListNotificationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Im_MarkNotificationsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNotificationsReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImServer).MarkNotificationsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Im_MarkNotificationsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImServer).MarkNotificationsRead(ctx, req.(*MarkNotificationsReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Im_GetUnreadNotificationCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadNotificationCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImServer).GetUnreadNotificationCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Im_GetUnreadNotificationCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImServer).GetUnreadNotificationCount(ctx, req.(*GetUnreadNotificationCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Im_EnsureGroupConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureGroupConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImServer).EnsureGroupConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Im_EnsureGroupConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImServer).EnsureGroupConversation(ctx, req.(*EnsureGroupConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Im_ServiceDesc is the grpc.ServiceDesc for Im service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Im_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "im.Im",
	HandlerType: (*ImServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChatLog",
			Handler:    _Im_GetChatLog_Handler,
		},
		{
			MethodName: "SetUpUserConversation",
			Handler:    _Im_SetUpUserConversation_Handler,
		},
		{
			MethodName: "GetConversations",
			Handler:    _Im_GetConversations_Handler,
		},
		{
			MethodName: "PutConversations",
			Handler:    _Im_PutConversations_Handler,
		},
		{
			MethodName: "CreateGroupConversation",
			Handler:    _Im_CreateGroupConversation_Handler,
		},
		{
			MethodName: "SetConversationSettings",
			Handler:    _Im_SetConversationSettings_Handler,
		},
		{
			MethodName: "RecallMsg",
			Handler:    _Im_RecallMsg_Handler,
		},
		{
			MethodName: "GetAtMeMessages",
			Handler:    _Im_GetAtMeMessages_Handler,
		},
		{
			MethodName: "CreateNotification",
			Handler:    _Im_CreateNotification_Handler,
		},
		{
			MethodName: "ListNotifications",
			Handler:    _Im_ListNotifications_Handler,
		},
		{
			MethodName: "MarkNotificationsRead",
			Handler:    _Im_MarkNotificationsRead_Handler,
		},
		{
			MethodName: "GetUnreadNotificationCount",
			Handler:    _Im_GetUnreadNotificationCount_Handler,
		},
		{
			MethodName: "EnsureGroupConversation",
			Handler:    _Im_EnsureGroupConversation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "im.proto",
}
