// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package socialmodels

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/iceymoss/go-hichat-api/pkg/db"
	"gorm.io/gorm"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendRequestsFieldNames          = builder.RawFieldNames(&FriendRequests{})
	friendRequestsRows                = strings.Join(friendRequestsFieldNames, ",")
	friendRequestsRowsExpectAutoSet   = strings.Join(stringx.Remove(friendRequestsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	friendRequestsRowsWithPlaceHolder = strings.Join(stringx.Remove(friendRequestsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFriendRequestsIdPrefix = "cache:friendRequests:id:v2:"
)

type (
	friendRequestsModel interface {
		Insert(ctx context.Context, data *FriendRequests) (sql.Result, error)
		FindOne(ctx context.Context, id uint64, uid string) (*FriendRequests, error)
		Update(ctx context.Context, session sqlx.Session, data *FriendRequests) error
		Delete(ctx context.Context, id uint64) error
		FindByReqUidAndUserId(ctx context.Context, rid, uid string) (*FriendRequests, error)
		ListNoHandler(ctx context.Context, userId string) ([]*FriendRequests, error)
		Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error
		ListAllHandler(ctx context.Context, userId string) ([]*FriendRequests, error)
		ListFilterHandler(ctx context.Context, userId string, typeList int32, putType string) ([]*FriendRequests, error)
	}

	defaultFriendRequestsModel struct {
		sqlc.CachedConn
		table string
	}

	FriendRequests struct {
		Id           uint64    `db:"id"`            // 自增主键
		UserId       uint64    `db:"user_id"`       // 申请人用户ID
		ReqUid       uint64    `db:"req_uid"`       // 被申请人用户ID
		ReqMsg       string    `db:"req_msg"`       // 好友申请留言
		ReqTime      time.Time `db:"req_time"`      // 申请发起时间
		HandleResult int       `db:"handle_result"` // 处理结果（0:待处理 1:同意 2:拒绝）
		HandleMsg    string    `db:"handle_msg"`    // 处理结果备注
		HandledAt    time.Time `db:"handled_at"`    // 处理操作时间
	}
)

func newFriendRequestsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFriendRequestsModel {
	return &defaultFriendRequestsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`friend_requests`",
	}
}

func (m *defaultFriendRequestsModel) Delete(ctx context.Context, id uint64) error {
	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, friendRequestsIdKey)
	return err
}

func (m *defaultFriendRequestsModel) FindOne(ctx context.Context, id uint64, uid string) (*FriendRequests, error) {
	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, id)
	var resp FriendRequests
	err := m.QueryRowCtx(ctx, &resp, friendRequestsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and `req_uid` = ? limit 1", friendRequestsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, uid)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// ListFilterHandler 获取好友申请
func (m *defaultFriendRequestsModel) ListFilterHandler(ctx context.Context, userId string, typeTag int32, putType string) ([]*FriendRequests, error) {
	var reqList []*FriendRequests
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	query := mysqlConn.Table(m.table)
	if typeTag != 0 {
		query.Where("handle_result = ?", typeTag)
	}
	if putType == "1" {
		query = query.Where("req_uid = ?", userId)
	} else {
		query = query.Where("user_id = ?", userId)
	}

	err := query.Find(&reqList).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return []*FriendRequests{}, err
	}

	return reqList, nil
}

func (m *defaultFriendRequestsModel) FindByReqUidAndUserId(ctx context.Context, rid, uid string) (*FriendRequests, error) {
	query := fmt.Sprintf("select %s from %s where `req_uid` = ? and `user_id` = ?", friendRequestsRows, m.table)

	var resp FriendRequests
	err := m.QueryRowNoCacheCtx(ctx, &resp, query, rid, uid)

	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// ListNoHandler获取好友申请列表
func (m *defaultFriendRequestsModel) ListNoHandler(ctx context.Context, userId string) ([]*FriendRequests, error) {
	query := fmt.Sprintf("select %s from %s where `handle_result` = 1 and `user_id` = ?", friendRequestsRows, m.table)

	var resp []*FriendRequests
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query, userId)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

// ListNoHandler获取好友申请列表
func (m *defaultFriendRequestsModel) ListAllHandler(ctx context.Context, userId string) ([]*FriendRequests, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ?", friendRequestsRows, m.table)

	var resp []*FriendRequests
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query, userId)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultFriendRequestsModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultFriendRequestsModel) Update(ctx context.Context, session sqlx.Session, data *FriendRequests) error {
	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, friendRequestsRowsWithPlaceHolder)
		return session.ExecCtx(ctx, query, data.UserId, data.ReqUid, data.ReqMsg, data.ReqTime, data.HandleResult, data.HandleMsg, data.HandledAt, data.Id)
	}, friendRequestsIdKey)
	return err
}

func (m *defaultFriendRequestsModel) Insert(ctx context.Context, data *FriendRequests) (sql.Result, error) {
	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, friendRequestsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.ReqUid, data.ReqMsg, data.ReqTime, data.HandleResult, data.HandleMsg, data.HandledAt)
	}, friendRequestsIdKey)
	return ret, err
}

func (m *defaultFriendRequestsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, primary)
}

func (m *defaultFriendRequestsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendRequestsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFriendRequestsModel) tableName() string {
	return m.table
}
