// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package socialmodels

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/iceymoss/go-hichat-api/pkg/db"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	friendRequestsFieldNames          = builder.RawFieldNames(&FriendRequests{})
	friendRequestsRows                = strings.Join(friendRequestsFieldNames, ",")
	friendRequestsRowsExpectAutoSet   = strings.Join(stringx.Remove(friendRequestsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	friendRequestsRowsWithPlaceHolder = strings.Join(stringx.Remove(friendRequestsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFriendRequestsIdPrefix = "cache:friendRequests:id:v2:"
)

type (
	friendRequestsModel interface {
		Insert(ctx context.Context, data *FriendRequests) (sql.Result, error)
		FindOne(ctx context.Context, id uint64, uid string) (*FriendRequests, error)
		Update(ctx context.Context, session sqlx.Session, data *FriendRequests) error
		Delete(ctx context.Context, id uint64) error
		FindByReqUidAndUserId(ctx context.Context, rid, uid string) (*FriendRequests, error)
		ListNoHandler(ctx context.Context, userId string) ([]*FriendRequests, error)
		Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error
		ListAllHandler(ctx context.Context, userId string) ([]*FriendRequests, error)
		ListFilterHandler(ctx context.Context, userId string, typeList int32, putType string) ([]*FriendRequests, error)
		MarkAsRead(ctx context.Context, id int32, userId string) error
		MarkAllAsRead(ctx context.Context, userId string) error
	}

	defaultFriendRequestsModel struct {
		sqlc.CachedConn
		table string
	}

	FriendRequests struct {
		Id           uint64    `db:"id"`             // 自增主键
		UserId       uint64    `db:"user_id"`        // 申请人用户ID
		ReqUid       uint64    `db:"req_uid"`        // 被申请人用户ID
		ReqMsg       string    `db:"req_msg"`        // 好友申请留言
		Status       int       `db:"status"`         // 消息状态（0:已删除 1:正常显示 2:忽略不显示）
		ReqTime      time.Time `db:"req_time"`       // 申请发起时间
		HandleResult int       `db:"handle_result"`  // 处理结果（0:待处理 1:同意 2:拒绝 3:忽略）
		HandleMsg    string    `db:"handle_msg"`     // 处理结果备注
		HandledAt    time.Time `db:"handled_at"`     // 处理操作时间
		ReadState    int       `db:"read_state"`     // (废弃，保留兼容) 旧的读取状态
		ReceiverRead int       `db:"receiver_read"`  // 接收方已读（0:未读 1:已读）
		SenderRead   int       `db:"sender_read"`    // 发起方已读处理结果（0:未读 1:已读）
	}
)

func newFriendRequestsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFriendRequestsModel {
	return &defaultFriendRequestsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`friend_requests`",
	}
}

func (m *defaultFriendRequestsModel) Delete(ctx context.Context, id uint64) error {
	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, friendRequestsIdKey)
	return err
}

func (m *defaultFriendRequestsModel) FindOne(ctx context.Context, id uint64, uid string) (*FriendRequests, error) {
	var resp FriendRequests
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	res := mysqlConn.Table(m.table).Where("id = ?", id).Where("req_uid = ? OR user_id = ?", uid, uid).First(&resp)
	if res.Error != nil && res.Error != gorm.ErrRecordNotFound {
		return nil, res.Error
	}
	return &resp, nil
}

// ListFilterHandler 获取好友申请
func (m *defaultFriendRequestsModel) ListFilterHandler(ctx context.Context, userId string, typeTag int32, putType string) ([]*FriendRequests, error) {
	var reqList []*FriendRequests
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	query := mysqlConn.Table(m.table)
	// 过滤掉已删除的记录（status = 0）
	query = query.Where("status != ?", 0)
	// typeTag: 0-待处理, 1-已通过, 2-已拒绝, 3-已忽略
	// 当typeTag为0时，也应该添加筛选条件，只返回待处理的记录
	query = query.Where("handle_result = ?", typeTag)
	if putType == "1" {
		query = query.Where("req_uid = ?", userId)
	} else {
		query = query.Where("user_id = ?", userId)
	}

	err := query.Find(&reqList).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return []*FriendRequests{}, err
	}

	return reqList, nil
}

func (m *defaultFriendRequestsModel) FindByReqUidAndUserId(ctx context.Context, rid, uid string) (*FriendRequests, error) {
	// 只查找待处理且未删除的记录，已处理过的不返回，允许重新申请时新建记录
	query := fmt.Sprintf("select %s from %s where `req_uid` = ? and `user_id` = ? and `handle_result` = 0 and `status` = 1", friendRequestsRows, m.table)

	var resp FriendRequests
	err := m.QueryRowNoCacheCtx(ctx, &resp, query, rid, uid)

	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// ListNoHandler获取好友申请列表
func (m *defaultFriendRequestsModel) ListNoHandler(ctx context.Context, userId string) ([]*FriendRequests, error) {
	query := fmt.Sprintf("select %s from %s where `handle_result` = 1 and `user_id` = ?", friendRequestsRows, m.table)

	var resp []*FriendRequests
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query, userId)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

// ListNoHandler获取好友申请列表
func (m *defaultFriendRequestsModel) ListAllHandler(ctx context.Context, userId string) ([]*FriendRequests, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ?", friendRequestsRows, m.table)

	var resp []*FriendRequests
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query, userId)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultFriendRequestsModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultFriendRequestsModel) Update(ctx context.Context, session sqlx.Session, data *FriendRequests) error {
	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, friendRequestsRowsWithPlaceHolder)
		return session.ExecCtx(ctx, query, data.UserId, data.ReqUid, data.ReqMsg, data.Status, data.ReqTime, data.HandleResult, data.HandleMsg, data.HandledAt, data.ReadState, data.ReceiverRead, data.SenderRead, data.Id)
	}, friendRequestsIdKey)
	return err
}

func (m *defaultFriendRequestsModel) Insert(ctx context.Context, data *FriendRequests) (sql.Result, error) {
	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, friendRequestsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.ReqUid, data.ReqMsg, data.Status, data.ReqTime, data.HandleResult, data.HandleMsg, data.HandledAt, data.ReadState, data.ReceiverRead, data.SenderRead)
	}, friendRequestsIdKey)
	return ret, err
}

// MarkAsRead 标记单条申请已读（按角色）
// 如果我是接收方(req_uid=我) → 更新 receiver_read
// 如果我是发起方(user_id=我) → 更新 sender_read
func (m *defaultFriendRequestsModel) MarkAsRead(ctx context.Context, id int32, userId string) error {
	// 两条 SQL 分别更新，只有匹配的那条会生效
	q1 := fmt.Sprintf("update %s set receiver_read = 1 where id = ? and req_uid = ? and receiver_read = 0", m.table)
	q2 := fmt.Sprintf("update %s set sender_read = 1 where id = ? and user_id = ? and sender_read = 0", m.table)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		conn.ExecCtx(ctx, q1, id, userId)
		return conn.ExecCtx(ctx, q2, id, userId)
	})
	return err
}

// MarkAllAsRead 批量标记已读（按角色）
// 1. 我收到的待处理申请 → receiver_read = 1
// 2. 我发出的已有结果 → sender_read = 1
func (m *defaultFriendRequestsModel) MarkAllAsRead(ctx context.Context, userId string) error {
	q1 := fmt.Sprintf("update %s set receiver_read = 1 where req_uid = ? and handle_result = 0 and status = 1 and receiver_read = 0", m.table)
	q2 := fmt.Sprintf("update %s set sender_read = 1 where user_id = ? and handle_result in (1,2) and status = 1 and sender_read = 0", m.table)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		conn.ExecCtx(ctx, q1, userId)
		return conn.ExecCtx(ctx, q2, userId)
	})
	return err
}

func (m *defaultFriendRequestsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, primary)
}

func (m *defaultFriendRequestsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendRequestsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFriendRequestsModel) tableName() string {
	return m.table
}
