// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	comment "github.com/iceymoss/go-hichat-api/apps/trend/api/internal/handler/comment"
	like "github.com/iceymoss/go-hichat-api/apps/trend/api/internal/handler/like"
	trend "github.com/iceymoss/go-hichat-api/apps/trend/api/internal/handler/trend"
	"github.com/iceymoss/go-hichat-api/apps/trend/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建新评论
				Method:  http.MethodPost,
				Path:    "/comment",
				Handler: comment.CreateDiscussHandler(serverCtx),
			},
			{
				// 删除评论
				Method:  http.MethodDelete,
				Path:    "/comment",
				Handler: comment.DeleteDiscussHandler(serverCtx),
			},
			{
				// 获取子评论列表
				Method:  http.MethodGet,
				Path:    "/comment/children",
				Handler: comment.GetChildDiscussesHandler(serverCtx),
			},
			{
				// 标记评论为已读
				Method:  http.MethodPut,
				Path:    "/comment/mark-read",
				Handler: comment.MarkDiscussReadHandler(serverCtx),
			},
			{
				// 获取一级评论
				Method:  http.MethodGet,
				Path:    "/comment/root",
				Handler: comment.GetRootDiscussesHandler(serverCtx),
			},
			{
				// 获取评论树
				Method:  http.MethodGet,
				Path:    "/comment/tree",
				Handler: comment.GetDiscussesTreeHandler(serverCtx),
			},
			{
				// 获取未读回复通知
				Method:  http.MethodGet,
				Path:    "/comment/unread",
				Handler: comment.GetUnreadRepliesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/trend"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 点赞/取消点赞
				Method:  http.MethodPost,
				Path:    "/like",
				Handler: like.ToggleLikeHandler(serverCtx),
			},
			{
				// 批量获取点赞摘要
				Method:  http.MethodGet,
				Path:    "/like/batch-summary",
				Handler: like.BatchGetTrendLikeSummaryHandler(serverCtx),
			},
			{
				// 标记点赞为已读
				Method:  http.MethodPut,
				Path:    "/like/mark-read",
				Handler: like.MarkLikesReadHandler(serverCtx),
			},
			{
				// 获取动态点赞摘要
				Method:  http.MethodGet,
				Path:    "/like/summary",
				Handler: like.GetTrendLikeSummaryHandler(serverCtx),
			},
			{
				// 获取未读点赞通知
				Method:  http.MethodGet,
				Path:    "/like/unread",
				Handler: like.GetUnreadLikesHandler(serverCtx),
			},
			{
				// 获取点赞用户列表
				Method:  http.MethodGet,
				Path:    "/like/users",
				Handler: like.GetLikedUsersHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/trend"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建新动态
				Method:  http.MethodPost,
				Path:    "/trend",
				Handler: trend.CreateTrendHandler(serverCtx),
			},
			{
				// 删除动态
				Method:  http.MethodPost,
				Path:    "/trend/delete",
				Handler: trend.DeleteTrendHandler(serverCtx),
			},
			{
				// 获取动态详情
				Method:  http.MethodGet,
				Path:    "/trend/detail",
				Handler: trend.GetTrendDetailHandler(serverCtx),
			},
			{
				// 更新动态内容
				Method:  http.MethodPut,
				Path:    "/trend/update",
				Handler: trend.UpdateTrendHandler(serverCtx),
			},
			{
				// 获取动态列表
				Method:  http.MethodGet,
				Path:    "/trends",
				Handler: trend.ListTrendsHandler(serverCtx),
			},
			{
				// 获取最新动态流
				Method:  http.MethodGet,
				Path:    "/trends/latest",
				Handler: trend.GetLatestTrendsHandler(serverCtx),
			},
			{
				// 获取用户个人动态
				Method:  http.MethodGet,
				Path:    "/user/trends",
				Handler: trend.GetUserTrendsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
