// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package models

import (
	"context"
	"fmt"
	"gorm.io/gorm"
	"strings"
	"time"

	"github.com/iceymoss/go-hichat-api/pkg/db"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	trendAgreeFieldNames          = builder.RawFieldNames(&TrendAgree{})
	trendAgreeRows                = strings.Join(trendAgreeFieldNames, ",")
	trendAgreeRowsExpectAutoSet   = strings.Join(stringx.Remove(trendAgreeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	trendAgreeRowsWithPlaceHolder = strings.Join(stringx.Remove(trendAgreeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTrendAgreeIdPrefix            = "cache:trendAgree:id:"
	cacheTrendAgreeUseridTrendIdPrefix = "cache:trendAgree:userid:trendId:"
)

type (
	trendAgreeModel interface {
		Insert(ctx context.Context, data *TrendAgree) (int, error)
		FindOne(ctx context.Context, id uint64) (*TrendAgree, error)
		FindOneByUseridTrendId(ctx context.Context, userid uint64, trendId uint64, state int) (*TrendAgree, error)
		Update(ctx context.Context, data *TrendAgree) error
		Delete(ctx context.Context, id uint64) error
		AgreeInc(ctx context.Context, userId uint64, authorId uint64, trendId uint64, incType int) error
	}

	defaultTrendAgreeModel struct {
		sqlc.CachedConn
		table string
	}

	TrendAgree struct {
		Id         uint64    `db:"id"`          // 主键
		Userid     uint64    `db:"userid"`      // 点赞用户ID
		AuthorId   uint64    `db:"author_id"`   // 被赞动态的作者ID
		TrendId    uint64    `db:"trend_id"`    // 动态ID
		OpTime     time.Time `db:"op_time"`     // 操作时间（点赞/取消时间）
		State      uint64    `db:"state"`       // 点赞状态 0:取消，1:有效
		IsRead     uint64    `db:"is_read"`     // 已读状态 0:已读，1:未读
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 最后更新时间
	}
)

func newTrendAgreeModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTrendAgreeModel {
	return &defaultTrendAgreeModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`trend_agree`",
	}
}

func (defaultTrendAgreeModel) TableName() string {
	return "trend_agree"
}

func (m *defaultTrendAgreeModel) AgreeInc(ctx context.Context, userId uint64, authorId uint64, trendId uint64, incType int) error {
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	var agreeTemp TrendAgree
	err := mysqlConn.Table(m.table).Where("trend_id = ?", trendId).Where("userid = ?", userId).First(&agreeTemp).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return err
	}

	// 第一次点赞,创建记录
	if (err == gorm.ErrRecordNotFound || agreeTemp.Id == 0) && incType > 0 {
		//insert
		_, inserErr := m.Insert(ctx, &TrendAgree{
			Userid:     userId,
			AuthorId:   authorId,
			TrendId:    trendId,
			OpTime:     time.Now(),
			State:      1,
			IsRead:     1,
			CreateTime: time.Now(),
			UpdateTime: time.Now(),
		})

		return inserErr
	}

	if agreeTemp.Id > 0 {
		agreeTemp.State = 0
		if incType > 0 {
			agreeTemp.State = 1
		}
	}

	agreeTemp.OpTime = time.Now()
	agreeTemp.UpdateTime = time.Now()
	upErr := m.Update(ctx, &agreeTemp)

	return upErr
}

func (m *defaultTrendAgreeModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	data.State = 0
	data.UpdateTime = time.Now()
	data.OpTime = time.Now()

	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	res := mysqlConn.Table(m.table).Where("id = ?", id).Updates(data)
	if res.Error != nil {
		return res.Error
	}

	if res.RowsAffected == 0 {
		return fmt.Errorf("delete agree failed id: %s", id)
	}

	return err
}

func (m *defaultTrendAgreeModel) FindOne(ctx context.Context, id uint64) (*TrendAgree, error) {
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	var agree TrendAgree
	err := mysqlConn.Table(m.table).Where("id = ?", id).First(&agree).Error
	switch err {
	case nil:
		return &agree, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// FindOneByUseridTrendId 获取用户点赞情况
func (m *defaultTrendAgreeModel) FindOneByUseridTrendId(ctx context.Context, userid uint64, trendId uint64, state int) (*TrendAgree, error) {
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	var agree TrendAgree
	err := mysqlConn.Table(m.table).
		Where("userid = ?", userid).
		Where("trend_id = ?", trendId).
		Where("state = ?", state).
		First(&agree).Error
	switch err {
	case nil:
		return &agree, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTrendAgreeModel) Insert(ctx context.Context, data *TrendAgree) (int, error) {
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	res := mysqlConn.Table(m.table).Create(&data)
	if res.Error != nil {
		return 0, res.Error
	}

	if res.RowsAffected == 0 {
		return 0, errors.New("create agree failed")
	}
	return int(data.Id), nil
}

func (m *defaultTrendAgreeModel) Update(ctx context.Context, newData *TrendAgree) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	newData.UpdateTime = time.Now()
	newData.OpTime = time.Now()

	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	res := mysqlConn.Table(m.table).Where("id = ?", data.Id).Updates(newData)
	if res.Error != nil {
		return res.Error
	}

	if res.RowsAffected == 0 {
		return fmt.Errorf("update agree failed id: %s", data.Id)
	}

	return err
}

func (m *defaultTrendAgreeModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTrendAgreeIdPrefix, primary)
}

func (m *defaultTrendAgreeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", trendAgreeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTrendAgreeModel) tableName() string {
	return m.table
}
