// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package models

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/iceymoss/go-hichat-api/pkg/db"
	zLog "github.com/iceymoss/go-hichat-api/pkg/logger"
	"github.com/iceymoss/go-hichat-api/pkg/transaction"

	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

var (
	trendAgreeFieldNames          = builder.RawFieldNames(&TrendAgree{})
	trendAgreeRows                = strings.Join(trendAgreeFieldNames, ",")
	trendAgreeRowsExpectAutoSet   = strings.Join(stringx.Remove(trendAgreeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	trendAgreeRowsWithPlaceHolder = strings.Join(stringx.Remove(trendAgreeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTrendAgreeIdPrefix            = "cache:trendAgree:id:"
	cacheTrendAgreeUseridTrendIdPrefix = "cache:trendAgree:userid:trendId:"
)

type (
	trendAgreeModel interface {
		Insert(ctx context.Context, data *TrendAgree) (int, error)
		FindOne(ctx context.Context, id uint64) (*TrendAgree, error)
		FindOneByUseridTrendId(ctx context.Context, userid uint64, trendId uint64, state int) (*TrendAgree, error)
		Update(ctx context.Context, data *TrendAgree) error
		Delete(ctx context.Context, id uint64) error
		AgreeInc(ctx context.Context, userId uint64, authorId uint64, trendId uint64, incType int) (int, error)
		MarkRead(ctx context.Context, ids []uint64) error
		GetAgreeByTrendId(ctx context.Context, trendId uint64, field []string, lastId int, limit int) ([]*TrendAgree, int64, error)
		GetUnReadAgree(ctx context.Context, userId int, field []string, id int, limit int) ([]*TrendAgree, int64, error)
		GetTrendAgree(ctx context.Context, trendIds []uint32, state int) (map[uint64][]*TrendAgree, error)
	}

	defaultTrendAgreeModel struct {
		sqlc.CachedConn
		table string
	}

	TrendAgree struct {
		Id         uint64    `db:"id"`          // 主键
		Userid     uint64    `db:"userid"`      // 点赞用户ID
		AuthorId   uint64    `db:"author_id"`   // 被赞动态的作者ID
		TrendId    uint64    `db:"trend_id"`    // 动态ID
		OpTime     time.Time `db:"op_time"`     // 操作时间（点赞/取消时间）
		State      uint64    `db:"state"`       // 点赞状态 0:取消，1:有效
		IsRead     uint64    `db:"is_read"`     // 已读状态 0:已读，1:未读
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 最后更新时间
	}
)

func newTrendAgreeModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTrendAgreeModel {
	return &defaultTrendAgreeModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`trend_agree`",
	}
}

func (TrendAgree) TableName() string {
	return "trend_agree"
}

func (m *defaultTrendAgreeModel) GetTrendAgree(ctx context.Context, trendIds []uint32, state int) (map[uint64][]*TrendAgree, error) {
	mysqlConn := transaction.GetTransactionOrDB(ctx, db.GetMysqlConn(db.MYSQL_DB_HICHAT2))

	var agreeList []*TrendAgree
	res := mysqlConn.Table(m.table).
		Where("trend_id in ?", trendIds).
		Where("state = ?", state).
		Find(&agreeList)
	if res.Error != nil {
		return nil, res.Error
	}

	ans := make(map[uint64][]*TrendAgree, len(trendIds))
	for _, agree := range agreeList {
		if _, ok := ans[agree.TrendId]; !ok {
			ans[agree.TrendId] = make([]*TrendAgree, 0)
		}
		ans[agree.TrendId] = append(ans[agree.TrendId], agree)
	}

	return ans, nil
}

func (m *defaultTrendAgreeModel) MarkRead(ctx context.Context, ids []uint64) error {
	mysqlConn := transaction.GetTransactionOrDB(ctx, db.GetMysqlConn(db.MYSQL_DB_HICHAT2))
	res := mysqlConn.Table(m.table).
		Where("id in ?", ids).
		Update("is_read", 0).
		Update("update_time", time.Now())
	if res.Error != nil {
		return res.Error
	}

	return nil
}

func (m *defaultTrendAgreeModel) AgreeInc(ctx context.Context, userId uint64, authorId uint64, trendId uint64, incType int) (int, error) {
	mysqlConn := transaction.GetTransactionOrDB(ctx, db.GetMysqlConn(db.MYSQL_DB_HICHAT2))

	want := uint64(0)
	if incType > 0 {
		want = 1
	}

	var agreeTemp TrendAgree
	err := mysqlConn.Table(m.table).Where("trend_id = ?", trendId).Where("userid = ?", userId).First(&agreeTemp).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return 0, err
	}

	// 无记录:只有点赞才创建记录;取消点赞则幂等无操作
	if err == gorm.ErrRecordNotFound || agreeTemp.Id == 0 {
		if want == 0 {
			return 0, nil
		}
		inserErr := mysqlConn.Create(&TrendAgree{
			Userid:     userId,
			AuthorId:   authorId,
			TrendId:    trendId,
			OpTime:     time.Now(),
			State:      1,
			IsRead:     1,
			CreateTime: time.Now(),
			UpdateTime: time.Now(),
		}).Error
		if inserErr != nil {
			return 0, inserErr
		}
		return 1, nil
	}

	// 已有记录:状态未变化则幂等无操作,不调整点赞总数
	if agreeTemp.State == want {
		return 0, nil
	}

	agreeTemp.State = want
	agreeTemp.OpTime = time.Now()
	agreeTemp.UpdateTime = time.Now()
	if upErr := mysqlConn.Table(m.table).Where("id = ?", agreeTemp.Id).Save(&agreeTemp).Error; upErr != nil {
		return 0, upErr
	}

	if want == 1 {
		return 1, nil
	}
	return -1, nil
}

// GetTrendAgreeListBy 获取动态点赞信息
func (m *defaultTrendAgreeModel) GetTrendAgreeListBy(ctx context.Context, trendIds []string, field []string, lastId int, limit int) ([]*TrendAgree, int64, error) {
	if len(field) == 0 {
		field = append(field, "*")
	}
	var list []*TrendAgree
	mysqlConn := transaction.GetTransactionOrDB(ctx, db.GetMysqlConn(db.MYSQL_DB_HICHAT2))
	err := mysqlConn.Table(m.table).Select(field).Where("trend_id in ?", trendIds).Where("id < ?", lastId).Limit(limit).Find(&list).Error
	if err != nil {
		return nil, 0, err
	}

	// TODO:

	return nil, 0, nil

}

func (m *defaultTrendAgreeModel) GetUnReadAgree(ctx context.Context, userId int, field []string, lastId int, limit int) ([]*TrendAgree, int64, error) {
	if len(field) == 0 {
		field = append(field, "*")
	}
	var list []*TrendAgree
	mysqlConn := transaction.GetTransactionOrDB(ctx, db.GetMysqlConn(db.MYSQL_DB_HICHAT2))

	var count int64
	query := mysqlConn.Table(m.table).Select(field)

	if lastId != 0 {
		query = query.Where("id < ?", lastId)
	}

	query = query.Where("author_id = ?", userId).
		Where("is_read = ?", 1)

	queryCount := query
	queryCount.Count(&count)

	// 动态作者，被点赞
	err := query.Order("id DESC").
		Limit(limit).
		Find(&list).Error
	if err != nil {
		zLog.Error("get unread agree failed", zap.Any("userId", userId), zap.Error(err))
		return nil, 0, err
	}

	return list, count, nil
}

func (m *defaultTrendAgreeModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	data.State = 0
	data.UpdateTime = time.Now()
	data.OpTime = time.Now()

	mysqlConn := transaction.GetTransactionOrDB(ctx, db.GetMysqlConn(db.MYSQL_DB_HICHAT2))
	res := mysqlConn.Table(m.table).Where("id = ?", id).Updates(data)
	if res.Error != nil {
		return res.Error
	}

	if res.RowsAffected == 0 {
		return fmt.Errorf("delete agree failed id: %d", id)
	}

	return err
}

func (m *defaultTrendAgreeModel) FindOne(ctx context.Context, id uint64) (*TrendAgree, error) {
	mysqlConn := transaction.GetTransactionOrDB(ctx, db.GetMysqlConn(db.MYSQL_DB_HICHAT2))
	var agree TrendAgree
	err := mysqlConn.Table(m.table).Where("id = ?", id).First(&agree).Error
	switch err {
	case nil:
		return &agree, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// FindOneByUseridTrendId 获取用户点赞情况
func (m *defaultTrendAgreeModel) FindOneByUseridTrendId(ctx context.Context, userid uint64, trendId uint64, state int) (*TrendAgree, error) {
	mysqlConn := transaction.GetTransactionOrDB(ctx, db.GetMysqlConn(db.MYSQL_DB_HICHAT2))
	var agree TrendAgree
	err := mysqlConn.Table(m.table).
		Where("userid = ?", userid).
		Where("trend_id = ?", trendId).
		Where("state = ?", state).
		First(&agree).Error
	switch err {
	case nil:
		return &agree, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTrendAgreeModel) GetAgreeByTrendId(ctx context.Context, trendId uint64, field []string, lastId int, limit int) ([]*TrendAgree, int64, error) {
	mysqlConn := transaction.GetTransactionOrDB(ctx, db.GetMysqlConn(db.MYSQL_DB_HICHAT2))
	var list []*TrendAgree
	query := mysqlConn.Table(m.table).
		Select(field).
		Where("trend_id = ?", trendId).
		Where("state = ?", 1) // 仅统计有效点赞(state=1)，取消点赞的记录(state=0)保留但不计入

	var count int64
	countQuery := query
	countQuery.Count(&count)

	if lastId != 0 {
		query = query.Where("id < ?", lastId)
	}

	if limit == 0 {
		limit = 50
	}

	err := query.Limit(limit).
		Order("id DESC").
		Find(&list).Error
	if err != nil {
		return nil, 0, err
	}

	return list, count, nil
}

func (m *defaultTrendAgreeModel) Insert(ctx context.Context, data *TrendAgree) (int, error) {
	mysqlConn := transaction.GetTransactionOrDB(ctx, db.GetMysqlConn(db.MYSQL_DB_HICHAT2))
	res := mysqlConn.Table(m.table).Create(&data)
	if res.Error != nil {
		return 0, res.Error
	}

	if res.RowsAffected == 0 {
		return 0, errors.New("create agree failed")
	}
	return int(data.Id), nil
}

func (m *defaultTrendAgreeModel) Update(ctx context.Context, newData *TrendAgree) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	newData.UpdateTime = time.Now()
	newData.OpTime = time.Now()

	mysqlConn := transaction.GetTransactionOrDB(ctx, db.GetMysqlConn(db.MYSQL_DB_HICHAT2))
	res := mysqlConn.Table(m.table).Where("id = ?", data.Id).Updates(newData)
	if res.Error != nil {
		return res.Error
	}

	if res.RowsAffected == 0 {
		return fmt.Errorf("update agree failed id: %d", data.Id)
	}

	return err
}

func (m *defaultTrendAgreeModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTrendAgreeIdPrefix, primary)
}

func (m *defaultTrendAgreeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", trendAgreeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTrendAgreeModel) tableName() string {
	return m.table
}
