// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"gorm.io/gorm"
	"strings"
	"time"

	"github.com/iceymoss/go-hichat-api/pkg/db"

	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

const Limit = 30

var (
	trendFieldNames          = builder.RawFieldNames(&Trend{})
	trendRows                = strings.Join(trendFieldNames, ",")
	trendRowsExpectAutoSet   = strings.Join(stringx.Remove(trendFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	trendRowsWithPlaceHolder = strings.Join(stringx.Remove(trendFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTrendIdPrefix = "cache:trend:id:"
)

type (
	trendModel interface {
		Insert(ctx context.Context, data *Trend) (uint64, error)
		FindOne(ctx context.Context, id uint64) (*Trend, error)
		Update(ctx context.Context, data *Trend) error
		Delete(ctx context.Context, id uint64) error
		IncAgreeOrReply(ctx context.Context, id uint64, class int, inc int) error
		SetTop(ctx context.Context, id uint64, isTop bool) error
		OpenReply(ctx context.Context, id uint64, isOpen bool) error
		SetCircleState(ctx context.Context, id uint64, ran int) error
		List(ctx context.Context, lastId int, lastTime int64, userIds []string, filter []string, sort string, sortType int) (*[]Trend, error)
		ListByUserIds(ctx context.Context, userList []string, lastId int, scpoe int32, filter []string) (*[]Trend, error)
	}

	defaultTrendModel struct {
		sqlc.CachedConn
		table string
	}

	Trend struct {
		Id            uint64       `db:"id"`            // 动态ID
		Userid        uint64       `db:"userid"`        // 发表用户ID
		Type          uint64       `db:"type"`          // 动态类型：1文本，2混合(图片)，3长文，4第三方分享(如B站视频)，5视频，6置顶广告
		Content       string       `db:"content"`       // 动态内容
		PositionName  string       `db:"position_name"` // 位置名称
		PositionPoint string       `db:"position"`      // 位置信息
		ReplyCount    uint64       `db:"reply_count"`   // 评论数量
		AgreeCount    uint64       `db:"agree_count"`   // 点赞数量
		Createtime    time.Time    `db:"createtime"`    // 原始创建时间
		Updatetime    time.Time    `db:"updatetime"`    // 最后更新时间
		CircleState   int64        `db:"circle_state"`  // 朋友圈状态：2-不可见，1-可见，0-朋友圈删除,
		State         int64        `db:"state"`         // 是否删除 0-删除，1-正常
		IsAd          int64        `db:"is_ad"`         // 是否广告：0-普通，1-广告
		Url           string       `db:"url"`           // 广告/视频链接（类型5使用）
		AdEndTime     sql.NullTime `db:"ad_end_time"`   // 广告展示截止时间
		OpenReply     int64        `db:"open_reply"`    // 是否开启评论：0-关闭，1-开启
		IsTop         int64        `db:"is_top"`        // 是否置顶：0-否，1-是
		Title         string       `db:"title"`         // 长文标题（类型3使用）
		Idlist        string       `db:"idlist"`        // @用户ID列表（使用JSON数组）
		PicArr        string       `db:"pic_arr"`       // 图片url或者视频
		ShareUrl      string       `db:"share_url"`     // 第三方内容ID（类型4使用）
		Cover         string       `db:"cover"`         // 封面图URL（类型3/5使用）
		Ip            string       `db:"ip"`            // 发布者IP地址
		Device        string       `db:"device"`        // 发布设备标识
	}
)

func (t Trend) TableName() string {
	return "trend"
}

func newTrendModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTrendModel {
	return &defaultTrendModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`trend`",
	}
}

func (m *defaultTrendModel) ListByUserIds(ctx context.Context, userList []string, lastId int, scpoe int32, filter []string) (*[]Trend, error) {
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	var trendList []Trend
	err := mysqlConn.Table(m.table).Select(filter).Where("state = ?", 1).
		Where("id > ?", lastId).
		Where("circle_state = ?", scpoe).
		Where("userid in ?", userList).
		Order("createtime DESC").
		Find(&trendList).Limit(Limit).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return &trendList, nil

}

func (m *defaultTrendModel) List(ctx context.Context, lastId int, lastTime int64, userIds []string, filter []string, sort string, sortType int) (*[]Trend, error) {
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	query := mysqlConn.Table(m.table).Select(filter)
	var trendList []Trend
	if lastId > 0 {
		query = query.Where("id > ?", lastId)
	}

	if lastTime > 0 {
		query = query.Where("createtime > ?", lastTime)
	}

	sortTypePoint := "ACS"
	if sortType < 0 {
		sortTypePoint = "DESC"
	}

	err := query.Where("state = ?", 1).
		Where("circle_state = ?", 1).
		Where("userid in ?", userIds).
		Order(fmt.Sprintf("%s %s", sort, sortTypePoint)).
		Find(&trendList).Limit(Limit).Error

	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return &trendList, nil
}

func (m *defaultTrendModel) SetCircleState(ctx context.Context, id uint64, ran int) error {
	authStateCulom := "circle_state"
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	res := mysqlConn.Table(m.table).Where("id = ?", id).Update(authStateCulom, ran)
	if res.Error != nil {
		return res.Error
	}

	if res.RowsAffected == 0 {
		return errors.New("set reply state failed")
	}

	return nil
}

func (m *defaultTrendModel) OpenReply(ctx context.Context, id uint64, isOpen bool) error {
	open := 0
	if isOpen {
		open = 1
	}

	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	res := mysqlConn.Table(m.table).Where("id = ?", id).Update("open_reply", open)
	if res.Error != nil {
		return res.Error
	}

	if res.RowsAffected == 0 {
		return errors.New("set reply state failed")
	}

	return nil

}

// class: 1删除朋友圈，3删除所有
func (m *defaultTrendModel) Delete(ctx context.Context, id uint64) error {
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	query := mysqlConn.Table(m.table).Where("id = ?", id)
	state := "state"
	res := query.Update(state, 0).Update("circle_state", 0)
	if res.Error != nil {
		return res.Error
	}

	if res.RowsAffected == 0 {
		return errors.New("delete trend failed")
	}

	return nil
}

func (m *defaultTrendModel) SetTop(ctx context.Context, id uint64, isTop bool) error {
	top := 0
	if isTop {
		top = 1
	}

	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	res := mysqlConn.Table(m.table).Where("id = ?", id).Update("is_top", top)
	if res.Error != nil {
		return res.Error
	}

	if res.RowsAffected == 0 {
		return errors.New("set top failed")
	}

	return nil
}

// IncAgreeOrReply 评论/点赞 +1 或者 -1 class = 1评论，class = 0点赞
func (m *defaultTrendModel) IncAgreeOrReply(ctx context.Context, id uint64, class int, inc int) error {
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)

	var trend Trend
	err := mysqlConn.Table(m.table).Select([]string{"id", "agree_count", "reply_count"}).Where("id = ?", id).First(&trend).Error
	if err != nil {
		return err
	}

	count := trend.AgreeCount + 1
	updateData := "agree_count"
	if inc < 0 {
		count = trend.AgreeCount - 1
	}

	if class == 1 {
		updateData = "reply_count"
		count = trend.ReplyCount + 1
		if inc < 0 {
			count = trend.ReplyCount - 1
		}
	}

	res := mysqlConn.Table(m.table).Where("id = ?", id).Update(updateData, count)
	if res.Error != nil {
		return res.Error
	}

	if res.RowsAffected == 0 {
		return errors.New(fmt.Sprintf("update %s failed", updateData))
	}

	return nil
}

func (m *defaultTrendModel) FindOne(ctx context.Context, id uint64) (*Trend, error) {
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	var resp Trend
	err := mysqlConn.Table(m.table).Where("id = ? and state = ?", id, 1).First(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gorm.ErrRecordNotFound:
		return &Trend{}, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultTrendModel) Insert(ctx context.Context, data *Trend) (uint64, error) {
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	res := mysqlConn.Table(m.table).Create(&data)
	if res.Error != nil {
		return 0, res.Error
	}

	if res.RowsAffected == 0 {
		return 0, errors.New("create trend faile")
	}
	return data.Id, nil
}

func (m *defaultTrendModel) Update(ctx context.Context, data *Trend) error {
	//TODO:
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	var trend Trend
	err := mysqlConn.Table(m.table).Where("id = ?", data.Id).First(&trend).Error
	if err != nil {
		return err
	}

	if data.ReplyCount != 0 {

	}

	return err
}

func (m *defaultTrendModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTrendIdPrefix, primary)
}

func (m *defaultTrendModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", trendRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTrendModel) tableName() string {
	return m.table
}
