// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/iceymoss/go-hichat-api/pkg/db"

	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	trendDiscussFieldNames          = builder.RawFieldNames(&TrendDiscuss{})
	trendDiscussRows                = strings.Join(trendDiscussFieldNames, ",")
	trendDiscussRowsExpectAutoSet   = strings.Join(stringx.Remove(trendDiscussFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	trendDiscussRowsWithPlaceHolder = strings.Join(stringx.Remove(trendDiscussFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTrendDiscussIdPrefix = "cache:trendDiscuss:id:"
)

type (
	trendDiscussModel interface {
		Insert(ctx context.Context, data *TrendDiscuss) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*TrendDiscuss, error)
		Update(ctx context.Context, data UpdateInput) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTrendDiscussModel struct {
		sqlc.CachedConn
		table string
	}

	TrendDiscuss struct {
		Id           uint64    `db:"id"`            // 主键ID
		Trendid      int64     `db:"trendid"`       // 所属动态ID（一级评论关联的源动态）
		Father       int64     `db:"father"`        // 父评论ID（0表示一级评论）
		Rootid       uint64    `db:"rootid"`        // 根评论ID（多级评论的祖先ID）
		Replyer      uint64    `db:"replyer"`       // 评论者用户ID
		Userid       uint64    `db:"userid"`        // 被评论者用户ID
		Level        int64     `db:"level"`         // 评论层级（1=一级评论，2=二级评论...）
		Content      string    `db:"content"`       // 评论内容
		Idlist       string    `db:"idlist"`        // @用户的ID列表
		AgreeCount   uint64    `db:"agree_count"`   // 点赞数
		DiscussCount int64     `db:"discuss_count"` // 子评论数量
		State        uint64    `db:"state"`         // 状态（0=已删除, 1=正常）
		Read         int64     `db:"read"`          // 已读状态（0=已读, 1=未读）
		Createtime   time.Time `db:"createtime"`    // 创建时间
		Updatetime   time.Time `db:"updatetime"`    // 最后更新时间
	}
)

func newTrendDiscussModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTrendDiscussModel {
	return &defaultTrendDiscussModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`trend_discuss`",
	}
}

func (m *defaultTrendDiscussModel) Delete(ctx context.Context, id uint64) error {
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	res := mysqlConn.Table(m.table).Where("id = ?", id).Update("state", 0)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return errors.New("delete trenddiscuss filed")
	}
	return nil
}

func (m *defaultTrendDiscussModel) FindOne(ctx context.Context, id uint64) (*TrendDiscuss, error) {
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	var trendDiscuss TrendDiscuss
	err := mysqlConn.Table(m.table).Where("id = ?", id).First(&trendDiscuss).Error
	switch err {
	case nil:
		return &trendDiscuss, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTrendDiscussModel) Insert(ctx context.Context, data *TrendDiscuss) (sql.Result, error) {
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	res := mysqlConn.Table(m.table).Create(&data)
	if res.Error != nil {
		return nil, res.Error
	}
	if res.RowsAffected == 0 {
		return nil, errors.New("create trenddiscuss filed")
	}
	return nil, nil
}

type UpdateInput struct {
	Id         int  // 评论id
	ReadStatus int  // 被评论者是否阅读 0已读，1未读
	IsAgree    bool // 是否点赞
	IsDiscuss  bool // 是否评论
}

func (m *defaultTrendDiscussModel) Update(ctx context.Context, data UpdateInput) error {
	mysqlConn := db.GetMysqlConn(db.MYSQL_DB_HICHAT2)
	var trendDiscuss TrendDiscuss
	err := mysqlConn.Table(m.table).Where("id = ?", data.Id).First(&trendDiscuss).Error
	if err != nil {
		return err
	}

	// 被评论者评论已读
	if data.ReadStatus != 1 {
		trendDiscuss.Read = 0
	}

	if data.IsDiscuss {
		trendDiscuss.DiscussCount++
	}

	if data.IsAgree {
		trendDiscuss.AgreeCount++
	}

	res := mysqlConn.Table(m.table).Where("id = ?", data.Id).Updates(&trendDiscuss)
	if err != nil {
		return res.Error
	}

	if res.RowsAffected == 0 {
		return errors.New("update trenddiscuss filed")
	}

	return nil
}

func (m *defaultTrendDiscussModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTrendDiscussIdPrefix, primary)
}

func (m *defaultTrendDiscussModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", trendDiscussRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTrendDiscussModel) tableName() string {
	return m.table
}
