// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	trendAgreeFieldNames          = builder.RawFieldNames(&TrendAgree{})
	trendAgreeRows                = strings.Join(trendAgreeFieldNames, ",")
	trendAgreeRowsExpectAutoSet   = strings.Join(stringx.Remove(trendAgreeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	trendAgreeRowsWithPlaceHolder = strings.Join(stringx.Remove(trendAgreeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTrendAgreeIdPrefix            = "cache:trendAgree:id:"
	cacheTrendAgreeUseridTrendIdPrefix = "cache:trendAgree:userid:trendId:"
)

type (
	trendAgreeModel interface {
		Insert(ctx context.Context, data *TrendAgree) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*TrendAgree, error)
		FindOneByUseridTrendId(ctx context.Context, userid uint64, trendId uint64) (*TrendAgree, error)
		Update(ctx context.Context, data *TrendAgree) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTrendAgreeModel struct {
		sqlc.CachedConn
		table string
	}

	TrendAgree struct {
		Id         uint64    `db:"id"`          // 主键
		Userid     uint64    `db:"userid"`      // 点赞用户ID
		AuthorId   uint64    `db:"author_id"`   // 被赞动态的作者ID
		TrendId    uint64    `db:"trend_id"`    // 动态ID
		OpTime     time.Time `db:"op_time"`     // 操作时间（点赞/取消时间）
		State      uint64    `db:"state"`       // 点赞状态 0:取消，1:有效
		IsRead     uint64    `db:"is_read"`     // 已读状态 0:已读，1:未读
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 最后更新时间
	}
)

func newTrendAgreeModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTrendAgreeModel {
	return &defaultTrendAgreeModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`trend_agree`",
	}
}

func (m *defaultTrendAgreeModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	trendAgreeIdKey := fmt.Sprintf("%s%v", cacheTrendAgreeIdPrefix, id)
	trendAgreeUseridTrendIdKey := fmt.Sprintf("%s%v:%v", cacheTrendAgreeUseridTrendIdPrefix, data.Userid, data.TrendId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, trendAgreeIdKey, trendAgreeUseridTrendIdKey)
	return err
}

func (m *defaultTrendAgreeModel) FindOne(ctx context.Context, id uint64) (*TrendAgree, error) {
	trendAgreeIdKey := fmt.Sprintf("%s%v", cacheTrendAgreeIdPrefix, id)
	var resp TrendAgree
	err := m.QueryRowCtx(ctx, &resp, trendAgreeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", trendAgreeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTrendAgreeModel) FindOneByUseridTrendId(ctx context.Context, userid uint64, trendId uint64) (*TrendAgree, error) {
	trendAgreeUseridTrendIdKey := fmt.Sprintf("%s%v:%v", cacheTrendAgreeUseridTrendIdPrefix, userid, trendId)
	var resp TrendAgree
	err := m.QueryRowIndexCtx(ctx, &resp, trendAgreeUseridTrendIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `userid` = ? and `trend_id` = ? limit 1", trendAgreeRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userid, trendId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTrendAgreeModel) Insert(ctx context.Context, data *TrendAgree) (sql.Result, error) {
	trendAgreeIdKey := fmt.Sprintf("%s%v", cacheTrendAgreeIdPrefix, data.Id)
	trendAgreeUseridTrendIdKey := fmt.Sprintf("%s%v:%v", cacheTrendAgreeUseridTrendIdPrefix, data.Userid, data.TrendId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, trendAgreeRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Userid, data.AuthorId, data.TrendId, data.OpTime, data.State, data.IsRead)
	}, trendAgreeIdKey, trendAgreeUseridTrendIdKey)
	return ret, err
}

func (m *defaultTrendAgreeModel) Update(ctx context.Context, newData *TrendAgree) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	trendAgreeIdKey := fmt.Sprintf("%s%v", cacheTrendAgreeIdPrefix, data.Id)
	trendAgreeUseridTrendIdKey := fmt.Sprintf("%s%v:%v", cacheTrendAgreeUseridTrendIdPrefix, data.Userid, data.TrendId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, trendAgreeRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Userid, newData.AuthorId, newData.TrendId, newData.OpTime, newData.State, newData.IsRead, newData.Id)
	}, trendAgreeIdKey, trendAgreeUseridTrendIdKey)
	return err
}

func (m *defaultTrendAgreeModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTrendAgreeIdPrefix, primary)
}

func (m *defaultTrendAgreeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", trendAgreeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTrendAgreeModel) tableName() string {
	return m.table
}
