// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: trend.proto

package server

import (
	"context"

	"github.com/iceymoss/go-hichat-api/apps/trend/rpc/internal/logic"
	"github.com/iceymoss/go-hichat-api/apps/trend/rpc/internal/svc"
	"github.com/iceymoss/go-hichat-api/apps/trend/rpc/trend"
)

type TrendServiceServer struct {
	svcCtx *svc.ServiceContext
	trend.UnimplementedTrendServiceServer
}

func NewTrendServiceServer(svcCtx *svc.ServiceContext) *TrendServiceServer {
	return &TrendServiceServer{
		svcCtx: svcCtx,
	}
}

// 发布动态
func (s *TrendServiceServer) CreateTrend(ctx context.Context, in *trend.CreateTrendRequest) (*trend.CreateTrendResponse, error) {
	l := logic.NewCreateTrendLogic(ctx, s.svcCtx)
	return l.CreateTrend(in)
}

// 删除动态
func (s *TrendServiceServer) DeleteTrend(ctx context.Context, in *trend.DeleteTrendRequest) (*trend.DeleteTrendResponse, error) {
	l := logic.NewDeleteTrendLogic(ctx, s.svcCtx)
	return l.DeleteTrend(in)
}

// 更新动态
func (s *TrendServiceServer) UpdateTrend(ctx context.Context, in *trend.UpdateTrendRequest) (*trend.UpdateTrendResponse, error) {
	l := logic.NewUpdateTrendLogic(ctx, s.svcCtx)
	return l.UpdateTrend(in)
}

// 获取动态列表
func (s *TrendServiceServer) ListTrends(ctx context.Context, in *trend.ListTrendsRequest) (*trend.ListTrendsResponse, error) {
	l := logic.NewListTrendsLogic(ctx, s.svcCtx)
	return l.ListTrends(in)
}

// 获取单个动态详情
func (s *TrendServiceServer) GetTrendDetail(ctx context.Context, in *trend.GetTrendDetailRequest) (*trend.GetTrendDetailResponse, error) {
	l := logic.NewGetTrendDetailLogic(ctx, s.svcCtx)
	return l.GetTrendDetail(in)
}

// 获取最新动态（用于朋友圈/论坛动态流）
func (s *TrendServiceServer) GetLatestTrends(ctx context.Context, in *trend.GetLatestTrendsRequest) (*trend.GetLatestTrendsResponse, error) {
	l := logic.NewGetLatestTrendsLogic(ctx, s.svcCtx)
	return l.GetLatestTrends(in)
}

// 获取用户个人动态列表
func (s *TrendServiceServer) GetUserTrends(ctx context.Context, in *trend.GetUserTrendsRequest) (*trend.GetUserTrendsResponse, error) {
	l := logic.NewGetUserTrendsLogic(ctx, s.svcCtx)
	return l.GetUserTrends(in)
}
