// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type ChatLog struct {
	Id             string `json:"id,omitempty"`
	ConversationId string `json:"conversationId,omitempty"`
	SendId         string `json:"sendId,omitempty"`
	RecvId         string `json:"recvId,omitempty"`
	MsgType        int32  `json:"msgType,omitempty"`
	MsgContent     string `json:"msgContent,omitempty"`
	ChatType       int32  `json:"chatType,omitempty"`
	SendTime       int64  `json:"sendTime,omitempty"` // 修正字段名统一小写
}

type ChatLogReq struct {
	MsgId          string `json:"msgId"`
	ConversationId string `json:"conversationId"`
	StartSendTime  int64  `json:"startSendTime,omitempty"`
	EndSendTime    int64  `json:"endSendTime,omitempty"`
	Count          int64  `json:"count,omitempty"`
}

type ChatLogResp struct {
	List []ChatLog `json:"list"` // 移除多余星号*
}

type Conversation struct {
	ConversationId string `json:"conversationId,omitempty"`
	ChatType       int32  `json:"chatType,omitempty"` // 修正字段名统一小写
	IsShow         bool   `json:"isShow,omitempty"`
	Seq            int64  `json:"seq,omitempty"`
	Read           int32  `json:"read,omitempty"`
}

type GetChatLogReadRecordsReq struct {
	MsgId string `json:"msgId"`
}

type GetChatLogReadRecordsResp struct {
	Reads   []string `json:"reads"`
	UnReads []string `json:"unReads"`
}

type GetConversationsReq struct {
}

type GetConversationsResp struct {
	ConversationList map[string]Conversation `json:"conversationList"` // 移除星号*
}

type PutConversationsReq struct {
	ConversationList map[string]Conversation `json:"conversationList"` // 移除星号*
}

type PutConversationsResp struct {
}

type SetUpUserConversationReq struct {
	SendId   string `json:"sendId,omitempty"`
	RecvId   string `json:"recvId,omitempty"`
	ChatType int32  `json:"chatType,omitempty"` // 字段名统一小写
}

type SetUpUserConversationResp struct {
}
