// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type ChatLog struct {
	Id             string `json:"id,omitempty"`
	ConversationId string `json:"conversationId,omitempty"`
	SendId         string `json:"sendId,omitempty"`
	RecvId         string `json:"recvId,omitempty"`
	MsgType        int32  `json:"msgType,omitempty"`
	MsgContent     string `json:"msgContent,omitempty"`
	ChatType       int32  `json:"chatType,omitempty"`
	SendTime       int64  `json:"sendTime,omitempty"` // 修正字段名统一小写
	// ReadRecords base64(bitmap)。私聊为 "AQ=="（对方已读）/空（未读），群聊为每成员 bit 位图
	ReadRecords string `json:"readRecords,omitempty"`
}

type ChatLogReq struct {
	MsgId          string `form:"msgId,optional"`
	ConversationId string `form:"conversationId"`
	StartSendTime  int64  `form:"startSendTime,optional"`
	EndSendTime    int64  `form:"endSendTime,optional"`
	Count          int64  `form:"count,optional"`
}

type ChatLogResp struct {
	List []ChatLog `json:"list"` // 移除多余星号*
}

type Conversation struct {
	ConversationId string  `json:"conversationId,optional,omitempty"`
	ChatType       int32   `json:"chatType,optional,omitempty"`
	IsShow         bool    `json:"isShow,optional,omitempty"`
	Seq            int64   `json:"seq,optional,omitempty"`
	Read           int32   `json:"read,optional,omitempty"`
	Msg            ChatLog `json:"message,optional,omitempty"`

	// 附带的用户/群信息（API 层填充，前端无需二次查询）
	TargetName   string `json:"targetName,optional,omitempty"`
	TargetAvatar string `json:"targetAvatar,optional,omitempty"`
	MemberCount  int    `json:"memberCount,optional,omitempty"`
}

type GetChatLogReadRecordsReq struct {
	MsgId string `form:"msgId"`
}

type ReadRecordUser struct {
	Id       string `json:"id"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	// 已读时间戳（unix nano），仅已读列表里有值；未读列表里为 0
	ReadAt int64 `json:"readAt,omitempty"`
}

type GetChatLogReadRecordsResp struct {
	Reads   []ReadRecordUser `json:"reads"`
	UnReads []ReadRecordUser `json:"unReads"`
}

type GetConversationsReq struct {
}

type GetConversationsResp struct {
	ConversationList map[string]Conversation `json:"conversationList"` // 移除星号*
}

type PutConversationsReq struct {
	ConversationList map[string]Conversation `json:"conversationList"` // 移除星号*
}

type PutConversationsResp struct {
}

type SetUpUserConversationReq struct {
	SendId   string `json:"sendId,omitempty"`
	RecvId   string `json:"recvId,omitempty"`
	ChatType int32  `json:"chatType,omitempty"` // 字段名统一小写
}

type SetUpUserConversationResp struct {
}
