mysql:         #MySQL config
  host: '127.0.0.1'
  port: '3306'
  name: 'hichat2'
  user: 'root'
  password: '123456789'
redis:
  host: 'localhost'
  port: '6379'
  user: ''
  passWord: ''
  url: 'redis://localhost:6379'
mq: 
  uri: 'amqp://admin:admin123@3.1.22.21:5672/'
mongo:
  link: 'mongodb://root:hichat2@localhost:27017/?authSource=admin&connectTimeoutMS=3000&socketTimeoutMS=5000&maxPoolSize=120&minPoolSize=20&retryWrites=true'
mailer:
    host: 'smtp.163.com'
    port: '465'
    username: 'hichat2'
    password: 'hichat2'


