mysql:         #MySQL config
  host: '127.0.0.1'
  port: '3306'
  name: 'hichat2'
  user: 'root'
  password: '123456789'
redis:
  host: 'localhost'
  port: '6379'
  user: ''
  passWord: ''
  url: 'redis://localhost:6379'
mq: 
  uri: 'amqp://admin:admin123@3.1.22.21:5672/'
