Name: trend.rpc
ListenOn: 0.0.0.0:10003
Etcd:
  Hosts:
    - etcd:2379
  Key: trend.rpc

Mysql:
  DataSource: root:123456789@tcp(mysql:3306)/hichat2?charset=utf8mb4&parseTime=true

Cache:
  - Host: redis:6379
    Type: node
