// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AtMember struct {
	UserId        string `json:"user_id,omitempty"`
	Nickname      string `json:"nickname,omitempty"`
	GroupNickname string `json:"group_nickname,omitempty"`
	Avatar        string `json:"avatar,omitempty"`
	RoleLevel     int32  `json:"role_level,omitempty"`
}

type FriendBlockReq struct {
	FriendUid string `json:"friend_uid"`
	Block     bool   `json:"block"`
}

type FriendBlockResp struct {
}

type FriendDeleteReq struct {
	FriendUid string `json:"friend_uid"`
}

type FriendDeleteResp struct {
}

type FriendListReq struct {
}

type FriendListResp struct {
	List []*Friends `json:"list"`
}

type FriendMomentsPermissionReq struct {
	FriendUid  string `json:"friend_uid"`
	Permission int32  `json:"permission"` // 0允许 1仅聊天 2屏蔽朋友圈
}

type FriendMomentsPermissionResp struct {
}

type FriendMuteReq struct {
	FriendUid string `json:"friend_uid"`
	Muted     bool   `json:"muted"`
}

type FriendMuteResp struct {
}

type FriendNotificationReq struct {
	FriendUid string `json:"friend_uid"`
	Enabled   bool   `json:"enabled"`
}

type FriendNotificationResp struct {
}

type FriendPinReq struct {
	FriendUid string `json:"friend_uid"`
	Pinned    bool   `json:"pinned"`
}

type FriendPinResp struct {
}

type FriendPutInDeleteReq struct {
	FriendReqId int32 `json:"friend_req_id,omitempty"` // 申请ID
}

type FriendPutInDeleteResp struct {
}

type FriendPutInHandleReq struct {
	FriendReqId  int32    `json:"friend_req_id,omitempty"`
	HandleResult int32    `json:"handle_result,omitempty"` // 处理结果
	Remark       string   `json:"remark,omitempty"`        // 备注
	Tags         []string `json:"tags,omitempty"`          // 标签
}

type FriendPutInHandleResp struct {
}

type FriendPutInListReq struct {
	Type  int32  `form:"type,optional"`  // 处理类型：0-待处理, 1-已通过, 2-已拒绝, 3-已忽略
	Class string `form:"class,optional"` // 申请列表类型：0-我发起的申请, 1-我收到的申请
}

type FriendPutInListResp struct {
	List []*FriendRequests `json:"list"`
}

type FriendPutInMessageCountReq struct {
}

type FriendPutInMessageCountResp struct {
	Count int32 `json:"count,omitempty"` // 消息数量
}

type FriendPutInReadReq struct {
	FriendReqId int32 `json:"friend_req_id,omitempty"` // 0 或不传表示全部已读
}

type FriendPutInReadResp struct {
}

type FriendPutInReq struct {
	ReqMsg  string `json:"req_msg,omitempty"`
	ReqTime int64  `json:"req_time,omitempty"`
	UserId  string `json:"user_uid"`
}

type FriendPutInResp struct {
}

type FriendRemarkReq struct {
	FriendUid string `json:"friend_uid"`
	Remark    string `json:"remark"`
}

type FriendRemarkResp struct {
}

type FriendReportReq struct {
	FriendUid string `json:"friend_uid"`
	Reason    string `json:"reason,optional"`
}

type FriendReportResp struct {
}

type FriendRequests struct {
	Id            int64  `json:"id,omitempty"`
	UserId        string `json:"user_id,omitempty"`
	ReqUid        string `json:"req_uid,omitempty"`
	ReqMsg        string `json:"req_msg,omitempty"`
	MessageStatus int    `json:"message_status,omitempty"` // 消息状态（0:已删除 1:正常显示 2:忽略不显示）
	ReqTime       int64  `json:"req_time,omitempty"`
	HandleResult  int    `json:"handle_result"`         // 0-待处理, 1-已同意, 2-已拒绝, 3-已忽略（不使用omitempty确保0值也会返回）
	Status        string `json:"status,omitempty"`      // 状态文本: pending-待处理, accepted-已同意, rejected-已拒绝, ignored-已忽略
	StatusText    string `json:"status_text,omitempty"` // 状态中文文本: 待处理, 已同意, 已拒绝, 已忽略
	HandleMsg     string `json:"handle_msg,omitempty"`
	ReadState     int    `json:"read_state,omitempty"`   // 读取状态 0未读 1已读
	Nickname      string `json:"nickname,omitempty"`     // 昵称
	Avatar        string `json:"avatar,omitempty"`       // 头像
	Sex           int32  `json:"sex,omitempty"`          // 性别（0-未知 1-男 2-女）
	Email         string `json:"email,omitempty"`        // 邮箱
	Phone         string `json:"phone,omitempty"`        // 手机号
	Introduction  string `json:"introduction,omitempty"` // 个性签名
	Region        string `json:"region,omitempty"`       // 地区
	Occupation    string `json:"occupation,omitempty"`   // 职业
	Tags          string `json:"tags,omitempty"`         // 个人标签（JSON数组字符串）
	UserStatus    int32  `json:"user_status,omitempty"`  // 用户状态（0-禁用 1-正常）
	UserType      int32  `json:"user_type,omitempty"`    // 用户类型（0-普通用户 1-管理员）
	LastLogin     int64  `json:"last_login,omitempty"`   // 最后登录时间（时间戳）
}

type FriendShareReq struct {
	FriendUid string `json:"friend_uid"`
	TargetUid string `json:"target_uid,optional"`
}

type FriendShareResp struct {
}

type FriendTagsReq struct {
	FriendUid string   `json:"friend_uid"`
	Tags      []string `json:"tags"`
}

type FriendTagsResp struct {
}

type Friends struct {
	Id                string   `json:"id,omitempty"`                 // 用户ID（好友的用户ID，不是关系表ID）
	FriendUid         string   `json:"friend_uid,omitempty"`         // 好友用户ID（与id相同，保留用于兼容）
	Nickname          string   `json:"nickname,omitempty"`           // 昵称
	Avatar            string   `json:"avatar,omitempty"`             // 头像
	Remark            string   `json:"remark,omitempty"`             // 备注
	Sex               int32    `json:"sex,omitempty"`                // 性别（0-未知 1-男 2-女）
	Email             string   `json:"email,omitempty"`              // 邮箱
	Phone             string   `json:"phone,omitempty"`              // 手机号
	Introduction      string   `json:"introduction,omitempty"`       // 个性签名
	Region            string   `json:"region,omitempty"`             // 地区
	Occupation        string   `json:"occupation,omitempty"`         // 职业
	Tags              string   `json:"tags,omitempty"`               // 个人标签（JSON数组字符串）
	Status            int32    `json:"status,omitempty"`             // 用户状态（0-禁用 1-正常）
	Type              int32    `json:"type,omitempty"`               // 用户类型（0-普通用户 1-管理员）
	LastLogin         int64    `json:"last_login,omitempty"`         // 最后登录时间（时间戳）
	Blacklisted       bool     `json:"blacklisted,omitempty"`        // 是否拉黑
	MomentsPermission int32    `json:"moments_permission,omitempty"` // 朋友圈权限 0允许 1仅聊天 2屏蔽朋友圈
	NotifyEnabled     bool     `json:"notify_enabled,omitempty"`     // 消息通知开关
	Pinned            bool     `json:"pinned,omitempty"`             // 是否置顶
	Muted             bool     `json:"muted,omitempty"`              // 是否静音
	FriendTags        []string `json:"friend_tags,omitempty"`        // 好友标签数组
}

type FriendsOnlineReq struct {
}

type FriendsOnlineResp struct {
	OnlineList map[string]bool `json:"onLineList"`
}

type GetMyGroupMemberSettingReq struct {
	GroupId string `form:"group_id"`
}

type GetMyGroupMemberSettingResp struct {
	Setting GroupMemberSetting `json:"setting,omitempty"`
}

type GroupAnnouncement struct {
	Id        int64  `json:"id,omitempty"`
	GroupId   string `json:"group_id,omitempty"`
	Content   string `json:"content,omitempty"`
	CreatedBy string `json:"created_by,omitempty"`
	CreatedAt int64  `json:"created_at,omitempty"`
	Pinned    bool   `json:"pinned,omitempty"`
	PinnedAt  int64  `json:"pinned_at,omitempty"`
}

type GroupAnnouncementCreateReq struct {
	GroupId string `json:"group_id"`
	Content string `json:"content"`
}

type GroupAnnouncementCreateResp struct {
	Id int64 `json:"id,omitempty"`
}

type GroupAnnouncementListReq struct {
	GroupId        string `form:"group_id"`
	IncludeDeleted bool   `form:"include_deleted,optional"`
}

type GroupAnnouncementListResp struct {
	List []GroupAnnouncement `json:"list,omitempty"`
}

type GroupAnnouncementPinReq struct {
	GroupId        string `json:"group_id"`
	AnnouncementId int64  `json:"announcement_id"`
	Pinned         bool   `json:"pinned"`
}

type GroupAnnouncementPinResp struct {
}

type GroupAtListReq struct {
	GroupId string `form:"group_id"`
	Keyword string `form:"keyword,optional"`
}

type GroupAtListResp struct {
	List []AtMember `json:"list,omitempty"`
}

type GroupCreateReq struct {
	Name string `json:"name,omitempty"`
	Icon string `json:"icon,omitempty"`
}

type GroupCreateResp struct {
	GroupId string `json:"group_id"`
}

type GroupDetailReq struct {
	GroupId string `form:"group_id"`
}

type GroupDetailResp struct {
	Group   Groups          `json:"group"`
	Members []*GroupMembers `json:"members"`
}

type GroupDisbandReq struct {
	GroupId string `json:"group_id"`
}

type GroupDisbandResp struct {
}

type GroupInviteLink struct {
	Token     string `json:"token,omitempty"`
	GroupId   string `json:"group_id,omitempty"`
	CreatedBy string `json:"created_by,omitempty"`
	CreatedAt int64  `json:"created_at,omitempty"`
	ExpireAt  int64  `json:"expire_at,omitempty"`
	MaxUses   int32  `json:"max_uses,omitempty"`
	UsedCount int32  `json:"used_count,omitempty"`
	Revoked   bool   `json:"revoked,omitempty"`
	RevokedAt int64  `json:"revoked_at,omitempty"`
}

type GroupInviteLinkCreateReq struct {
	GroupId       string `json:"group_id"`
	ExpireSeconds int64  `json:"expire_seconds,optional"` // 0=永不过期
	MaxUses       int32  `json:"max_uses,optional"`       // 0=无限
}

type GroupInviteLinkCreateResp struct {
	Link GroupInviteLink `json:"link,omitempty"`
}

type GroupInviteLinkListReq struct {
	GroupId        string `form:"group_id"`
	IncludeRevoked bool   `form:"include_revoked,optional"`
}

type GroupInviteLinkListResp struct {
	List []GroupInviteLink `json:"list,omitempty"`
}

type GroupInviteLinkRevokeReq struct {
	GroupId string `json:"group_id"`
	Token   string `json:"token"`
}

type GroupInviteLinkRevokeResp struct {
}

type GroupInviteReq struct {
	GroupId   string   `json:"group_id"`
	FriendIds []string `json:"friend_ids"`
}

type GroupInviteResp struct {
}

type GroupJoinByTokenReq struct {
	Token  string `json:"token"`
	ReqMsg string `json:"req_msg,optional"`
}

type GroupJoinByTokenResp struct {
	GroupId int32 `json:"group_id,omitempty"`
	IsPass  int32 `json:"is_pass,omitempty"` // 1=直接进群 0=进入申请流程
}

type GroupKickReq struct {
	GroupId   string   `json:"group_id"`
	MemberIds []string `json:"member_ids"`
}

type GroupKickResp struct {
}

type GroupListReq struct {
}

type GroupListResp struct {
	List []*Groups `json:"list,omitempty"`
}

type GroupMemberSetting struct {
	GroupId       string `json:"group_id,omitempty"`
	UserId        string `json:"user_id,omitempty"`
	GroupNickname string `json:"group_nickname,omitempty"`
	GroupRemark   string `json:"group_remark,omitempty"`
	UpdatedAt     int64  `json:"updated_at,omitempty"`
}

type GroupMembers struct {
	Id            int64  `json:"id,omitempty"`
	GroupId       string `json:"group_id,omitempty"`
	UserId        string `json:"user_id,omitempty"`
	Nickname      string `json:"nickname,omitempty"`
	UserAvatarUrl string `json:"user_avatar_url,omitempty"`
	RoleLevel     int    `json:"role_level,omitempty"`
	InviterUid    string `json:"inviter_uid,omitempty"`
	OperatorUid   string `json:"operator_uid,omitempty"`
	User          User   `json:"user,omitempty"`
}

type GroupPutInHandleReq struct {
	GroupReqId   int32  `json:"group_req_id,omitempty"`
	GroupId      string `json:"group_id,omitempty"`
	HandleResult int32  `json:"handle_result,omitempty"` // 处理结果
}

type GroupPutInHandleResp struct {
}

type GroupPutInListReq struct {
	GroupId string  `json:"group_id,omitempty"`
	Type    []int32 `json:"type,optional"`
	Class   int32   `json:"class,optional"`
}

type GroupPutInListResp struct {
	List []*GroupRequests `json:"list,omitempty"`
}

type GroupPutInReq struct {
	GroupId    string `json:"group_id,optional"`    // 群ID（普通申请/邀请入群时必传，token入群时可为空）
	ReqId      string `json:"req_id,optional"`      // 申请者/被邀请者ID（邀请入群时必传，普通申请时为空则使用当前用户ID）
	ReqMsg     string `json:"req_msg,optional"`     // 申请消息
	ReqTime    int64  `json:"req_time,optional"`    // 请求时间
	JoinSource int64  `json:"join_source,optional"` // 1=申请入群, 2=邀请入群, 3=邀请链接/二维码入群
	InviterUid string `json:"inviter_uid,optional"` // 邀请人UID（邀请入群/token入群时必传）
	Token      string `json:"token,optional"`       // 邀请链接token（token入群时必传，此时groupId可为空）
}

type GroupPutInResp struct {
	GroupId int `json:"group_id,omitempty"`
	IsPass  int `json:"is_pass,omitempty"` // 1=直接进群, 0=进入申请流程
}

type GroupQuitReq struct {
	GroupId string `json:"group_id"`
}

type GroupQuitResp struct {
}

type GroupRequests struct {
	Id            int64  `json:"id,omitempty"`
	UserId        string `json:"user_id,omitempty"`
	GroupId       string `json:"group_id,omitempty"`
	ReqMsg        string `json:"req_msg,omitempty"`
	ReqTime       int64  `json:"req_time,omitempty"`
	JoinSource    int64  `json:"join_source,omitempty"`
	InviterUserId string `json:"inviter_user_id,omitempty"`
	HandleUserId  string `json:"handle_user_id,omitempty"`
	HandleTime    int64  `json:"handle_time,omitempty"`
	HandleResult  int64  `json:"handle_result,omitempty"`
	User          User   `json:"user,omitempty"`
	Group         Groups `json:"group,omitempty"`
}

type GroupSetAdminReq struct {
	GroupId   string   `json:"group_id"`
	MemberIds []string `json:"member_ids"`
	IsAdmin   bool     `json:"is_admin"` // true=设为管理员 false=取消管理员
}

type GroupSetAdminResp struct {
}

type GroupTransferOwnerReq struct {
	GroupId             string `json:"group_id"`
	NewOwnerId          string `json:"new_owner_id"`
	KeepOldOwnerAsAdmin bool   `json:"keep_old_owner_as_admin,optional"` // 默认 true（服务端兜底）
}

type GroupTransferOwnerResp struct {
}

type GroupUpdateReq struct {
	GroupId      string `json:"group_id"`
	Name         string `json:"name,optional"`
	Icon         string `json:"icon,optional"`
	Notification string `json:"notification,optional"`
	IsVerify     int32  `json:"is_verify,optional"` // -1不修改 0不需要验证 1需要验证
}

type GroupUpdateResp struct {
}

type GroupUserListReq struct {
	GroupId string `json:"group_id,omitempty"`
}

type GroupUserListResp struct {
	List []*GroupMembers `json:"List,omitempty"`
}

type GroupUserOnlineReq struct {
	GroupId string `json:"group_id,omitempty"`
}

type GroupUserOnlineResp struct {
	OnlineList map[string]bool `json:"onLineList"`
}

type Groups struct {
	Id              string `json:"id,omitempty"`
	Name            string `json:"name,omitempty"`
	Icon            string `json:"icon,omitempty"`
	Status          int64  `json:"status,omitempty"`
	GroupType       int64  `json:"group_type,omitempty"`
	IsVerify        bool   `json:"is_verify,omitempty"`
	Notification    string `json:"notification,omitempty"`
	NotificationUid string `json:"notification_uid,omitempty"`
	CreateUid       string `json:"create_uid,omitempty"`
}

type UpdateMyGroupMemberSettingReq struct {
	GroupId       string `json:"group_id"`
	GroupNickname string `json:"group_nickname,optional"`
	GroupRemark   string `json:"group_remark,optional"`
}

type UpdateMyGroupMemberSettingResp struct {
}

type User struct {
	Id            string `json:"id,omitempty"`
	Nickname      string `json:"nickname,omitempty"`
	Sex           int    `json:"sex,omitempty"`
	Avatar        string `json:"avatar,omitempty"`
	Introduction  string `json:"introduction,omitempty"`
	IsCurrentUser int    `json:"is_current_user,omitempty"`
}
