// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type FriendBlockReq struct {
	FriendUid string `json:"friend_uid"`
	Block     bool   `json:"block"`
}

type FriendBlockResp struct {
}

type FriendDeleteReq struct {
	FriendUid string `json:"friend_uid"`
}

type FriendDeleteResp struct {
}

type FriendListReq struct {
}

type FriendListResp struct {
	List []*Friends `json:"list"`
}

type FriendMomentsPermissionReq struct {
	FriendUid  string `json:"friend_uid"`
	Permission int32  `json:"permission"` // 0允许 1仅聊天 2屏蔽朋友圈
}

type FriendMomentsPermissionResp struct {
}

type FriendMuteReq struct {
	FriendUid string `json:"friend_uid"`
	Muted     bool   `json:"muted"`
}

type FriendMuteResp struct {
}

type FriendNotificationReq struct {
	FriendUid string `json:"friend_uid"`
	Enabled   bool   `json:"enabled"`
}

type FriendNotificationResp struct {
}

type FriendPinReq struct {
	FriendUid string `json:"friend_uid"`
	Pinned    bool   `json:"pinned"`
}

type FriendPinResp struct {
}

type FriendPutInDeleteReq struct {
	FriendReqId int32 `json:"friend_req_id,omitempty"` // 申请ID
}

type FriendPutInDeleteResp struct {
}

type FriendPutInHandleReq struct {
	FriendReqId  int32 `json:"friend_req_id,omitempty"`
	HandleResult int32 `json:"handle_result,omitempty"` // 处理结果
}

type FriendPutInHandleResp struct {
}

type FriendPutInIgnoreReq struct {
	FriendReqId int32 `json:"friend_req_id,omitempty"` // 申请ID
}

type FriendPutInIgnoreResp struct {
}

type FriendPutInListReq struct {
	Type  int32  `form:"type,optional"`  // 处理类型：0-待处理, 1-已通过, 2-已拒绝, 3-已忽略
	Class string `form:"class,optional"` // 申请列表类型：0-我发起的申请, 1-我收到的申请
}

type FriendPutInListResp struct {
	List []*FriendRequests `json:"list"`
}

type FriendPutInMessageCountReq struct {
}

type FriendPutInMessageCountResp struct {
	Count int32 `json:"count,omitempty"` // 消息数量
}

type FriendPutInReq struct {
	ReqMsg  string `json:"req_msg,omitempty"`
	ReqTime int64  `json:"req_time,omitempty"`
	UserId  string `json:"user_uid"`
}

type FriendPutInResp struct {
}

type FriendRemarkReq struct {
	FriendUid string `json:"friend_uid"`
	Remark    string `json:"remark"`
}

type FriendRemarkResp struct {
}

type FriendReportReq struct {
	FriendUid string `json:"friend_uid"`
	Reason    string `json:"reason,optional"`
}

type FriendReportResp struct {
}

type FriendRequests struct {
	Id            int64  `json:"id,omitempty"`
	UserId        string `json:"user_id,omitempty"`
	ReqUid        string `json:"req_uid,omitempty"`
	ReqMsg        string `json:"req_msg,omitempty"`
	MessageStatus int    `json:"message_status,omitempty"` // 消息状态（0:已删除 1:正常显示 2:忽略不显示）
	ReqTime       int64  `json:"req_time,omitempty"`
	HandleResult  int    `json:"handle_result"`         // 0-待处理, 1-已同意, 2-已拒绝, 3-已忽略（不使用omitempty确保0值也会返回）
	Status        string `json:"status,omitempty"`      // 状态文本: pending-待处理, accepted-已同意, rejected-已拒绝, ignored-已忽略
	StatusText    string `json:"status_text,omitempty"` // 状态中文文本: 待处理, 已同意, 已拒绝, 已忽略
	HandleMsg     string `json:"handle_msg,omitempty"`
}

type FriendShareReq struct {
	FriendUid string `json:"friend_uid"`
	TargetUid string `json:"target_uid,optional"`
}

type FriendShareResp struct {
}

type FriendTagsReq struct {
	FriendUid string   `json:"friend_uid"`
	Tags      []string `json:"tags"`
}

type FriendTagsResp struct {
}

type Friends struct {
	Id                string   `json:"id,omitempty"`                 // 用户ID（好友的用户ID，不是关系表ID）
	FriendUid         string   `json:"friend_uid,omitempty"`         // 好友用户ID（与id相同，保留用于兼容）
	Nickname          string   `json:"nickname,omitempty"`           // 昵称
	Avatar            string   `json:"avatar,omitempty"`             // 头像
	Remark            string   `json:"remark,omitempty"`             // 备注
	Sex               int32    `json:"sex,omitempty"`                // 性别（0-未知 1-男 2-女）
	Email             string   `json:"email,omitempty"`              // 邮箱
	Phone             string   `json:"phone,omitempty"`              // 手机号
	Introduction      string   `json:"introduction,omitempty"`       // 个性签名
	Region            string   `json:"region,omitempty"`             // 地区
	Occupation        string   `json:"occupation,omitempty"`         // 职业
	Tags              string   `json:"tags,omitempty"`               // 个人标签（JSON数组字符串）
	Status            int32    `json:"status,omitempty"`             // 用户状态（0-禁用 1-正常）
	Type              int32    `json:"type,omitempty"`               // 用户类型（0-普通用户 1-管理员）
	LastLogin         int64    `json:"last_login,omitempty"`         // 最后登录时间（时间戳）
	Blacklisted       bool     `json:"blacklisted,omitempty"`        // 是否拉黑
	MomentsPermission int32    `json:"moments_permission,omitempty"` // 朋友圈权限 0允许 1仅聊天 2屏蔽朋友圈
	NotifyEnabled     bool     `json:"notify_enabled,omitempty"`     // 消息通知开关
	Pinned            bool     `json:"pinned,omitempty"`             // 是否置顶
	Muted             bool     `json:"muted,omitempty"`              // 是否静音
	FriendTags        []string `json:"friend_tags,omitempty"`        // 好友标签数组
}

type FriendsOnlineReq struct {
}

type FriendsOnlineResp struct {
	OnlineList map[string]bool `json:"onLineList"`
}

type GroupCreateReq struct {
	Name string `json:"name,omitempty"`
	Icon string `json:"icon,omitempty"`
}

type GroupCreateResp struct {
}

type GroupListRep struct {
}

type GroupListResp struct {
	List []*Groups `json:"list,omitempty"`
}

type GroupMembers struct {
	Id            int64  `json:"id,omitempty"`
	GroupId       string `json:"group_id,omitempty"`
	UserId        string `json:"user_id,omitempty"`
	Nickname      string `json:"nickname,omitempty"`
	UserAvatarUrl string `json:"user_avatar_url,omitempty"`
	RoleLevel     int    `json:"role_level,omitempty"`
	InviterUid    string `json:"inviter_uid,omitempty"`
	OperatorUid   string `json:"operator_uid,omitempty"`
	User          User   `json:"user,omitempty"`
}

type GroupPutInHandleRep struct {
	GroupReqId   int32  `json:"group_req_id,omitempty"`
	GroupId      string `json:"group_id,omitempty"`
	HandleResult int32  `json:"handle_result,omitempty"` // 处理结果
}

type GroupPutInHandleResp struct {
}

type GroupPutInListRep struct {
	GroupId string  `json:"group_id,omitempty"`
	Type    []int32 `json:"type,optional"`
	Class   int32   `json:"class,optional"`
}

type GroupPutInListResp struct {
	List []*GroupRequests `json:"list,omitempty"`
}

type GroupPutInRep struct {
	GroupId    string `json:"group_id,omitempty"`
	ReqMsg     string `json:"req_msg,omitempty"`
	ReqTime    int64  `json:"req_time,omitempty"`
	JoinSource int64  `json:"join_source,omitempty"`
	InviterUid string `json:"inviter_uid,omitempty"`
}

type GroupPutInResp struct {
	GroupId int `json:"group_id,omitempty"`
}

type GroupRequests struct {
	Id            int64  `json:"id,omitempty"`
	UserId        string `json:"user_id,omitempty"`
	GroupId       string `json:"group_id,omitempty"`
	ReqMsg        string `json:"req_msg,omitempty"`
	ReqTime       int64  `json:"req_time,omitempty"`
	JoinSource    int64  `json:"join_source,omitempty"`
	InviterUserId string `json:"inviter_user_id,omitempty"`
	HandleUserId  string `json:"handle_user_id,omitempty"`
	HandleTime    int64  `json:"handle_time,omitempty"`
	HandleResult  int64  `json:"handle_result,omitempty"`
	User          User   `json:"user,omitempty"`
	Group         Groups `json:"group,omitempty"`
}

type GroupUserListReq struct {
	GroupId string `json:"group_id,omitempty"`
}

type GroupUserListResp struct {
	List []*GroupMembers `json:"List,omitempty"`
}

type GroupUserOnlineReq struct {
	GroupId string `json:"group_id,omitempty"`
}

type GroupUserOnlineResp struct {
	OnlineList map[string]bool `json:"onLineList"`
}

type Groups struct {
	Id              string `json:"id,omitempty"`
	Name            string `json:"name,omitempty"`
	Icon            string `json:"icon,omitempty"`
	Status          int64  `json:"status,omitempty"`
	GroupType       int64  `json:"group_type,omitempty"`
	IsVerify        bool   `json:"is_verify,omitempty"`
	Notification    string `json:"notification,omitempty"`
	NotificationUid string `json:"notification_uid,omitempty"`
	CreateUid       string `json:"create_uid,omitempty"`
}

type User struct {
	Id            string `json:"id,omitempty"`
	Nickname      string `json:"nickname,omitempty"`
	Sex           int    `json:"sex,omitempty"`
	Avatar        string `json:"avatar,omitempty"`
	Introduction  string `json:"introduction,omitempty"`
	IsCurrentUser int    `json:"is_current_user,omitempty"`
}
