// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: social.proto

package social

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Social_FriendPutIn_FullMethodName                = "/social.social/FriendPutIn"
	Social_FriendPutInHandle_FullMethodName          = "/social.social/FriendPutInHandle"
	Social_FriendPutInRead_FullMethodName            = "/social.social/FriendPutInRead"
	Social_FriendPutInDelete_FullMethodName          = "/social.social/FriendPutInDelete"
	Social_FriendPutInList_FullMethodName            = "/social.social/FriendPutInList"
	Social_FriendPutInMessageCount_FullMethodName    = "/social.social/FriendPutInMessageCount"
	Social_FriendList_FullMethodName                 = "/social.social/FriendList"
	Social_FriendUpdateRemark_FullMethodName         = "/social.social/FriendUpdateRemark"
	Social_FriendDelete_FullMethodName               = "/social.social/FriendDelete"
	Social_FriendBlock_FullMethodName                = "/social.social/FriendBlock"
	Social_FriendMomentsPermission_FullMethodName    = "/social.social/FriendMomentsPermission"
	Social_FriendNotification_FullMethodName         = "/social.social/FriendNotification"
	Social_FriendPin_FullMethodName                  = "/social.social/FriendPin"
	Social_FriendMute_FullMethodName                 = "/social.social/FriendMute"
	Social_FriendTags_FullMethodName                 = "/social.social/FriendTags"
	Social_FriendReport_FullMethodName               = "/social.social/FriendReport"
	Social_FriendShare_FullMethodName                = "/social.social/FriendShare"
	Social_GroupCreate_FullMethodName                = "/social.social/GroupCreate"
	Social_GroupPutin_FullMethodName                 = "/social.social/GroupPutin"
	Social_GroupPutinList_FullMethodName             = "/social.social/GroupPutinList"
	Social_GetGroupPutListByUid_FullMethodName       = "/social.social/GetGroupPutListByUid"
	Social_MarkGroupReqRead_FullMethodName           = "/social.social/MarkGroupReqRead"
	Social_GroupPutInHandle_FullMethodName           = "/social.social/GroupPutInHandle"
	Social_GroupList_FullMethodName                  = "/social.social/GroupList"
	Social_GroupUsers_FullMethodName                 = "/social.social/GroupUsers"
	Social_FindGroupList_FullMethodName              = "/social.social/FindGroupList"
	Social_GroupSearch_FullMethodName                = "/social.social/GroupSearch"
	Social_GroupQuit_FullMethodName                  = "/social.social/GroupQuit"
	Social_GroupKick_FullMethodName                  = "/social.social/GroupKick"
	Social_GroupUpdate_FullMethodName                = "/social.social/GroupUpdate"
	Social_GroupDetail_FullMethodName                = "/social.social/GroupDetail"
	Social_GroupDisband_FullMethodName               = "/social.social/GroupDisband"
	Social_GroupTransferOwner_FullMethodName         = "/social.social/GroupTransferOwner"
	Social_GroupSetAdmin_FullMethodName              = "/social.social/GroupSetAdmin"
	Social_GroupInvite_FullMethodName                = "/social.social/GroupInvite"
	Social_GroupInviteLinkCreate_FullMethodName      = "/social.social/GroupInviteLinkCreate"
	Social_GroupInviteLinkList_FullMethodName        = "/social.social/GroupInviteLinkList"
	Social_GroupInviteLinkRevoke_FullMethodName      = "/social.social/GroupInviteLinkRevoke"
	Social_GroupJoinByToken_FullMethodName           = "/social.social/GroupJoinByToken"
	Social_GetMyGroupMemberSetting_FullMethodName    = "/social.social/GetMyGroupMemberSetting"
	Social_UpdateMyGroupMemberSetting_FullMethodName = "/social.social/UpdateMyGroupMemberSetting"
	Social_GroupAtList_FullMethodName                = "/social.social/GroupAtList"
	Social_GetMemberRole_FullMethodName              = "/social.social/GetMemberRole"
	Social_GroupAnnouncementCreate_FullMethodName    = "/social.social/GroupAnnouncementCreate"
	Social_GroupAnnouncementList_FullMethodName      = "/social.social/GroupAnnouncementList"
	Social_GroupAnnouncementPin_FullMethodName       = "/social.social/GroupAnnouncementPin"
	Social_GroupInvitationCreate_FullMethodName      = "/social.social/GroupInvitationCreate"
	Social_GroupInvitationList_FullMethodName        = "/social.social/GroupInvitationList"
	Social_GroupInvitationRead_FullMethodName        = "/social.social/GroupInvitationRead"
	Social_GroupRequestMessageCount_FullMethodName   = "/social.social/GroupRequestMessageCount"
	Social_GroupInvitationHandle_FullMethodName      = "/social.social/GroupInvitationHandle"
	Social_ExpireGroupInvitations_FullMethodName     = "/social.social/ExpireGroupInvitations"
)

// SocialClient is the client API for Social service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// svc
type SocialClient interface {
	// 好友业务：请求好友、通过或拒绝申请、好友列表
	FriendPutIn(ctx context.Context, in *FriendPutInReq, opts ...grpc.CallOption) (*FriendPutInResp, error)
	FriendPutInHandle(ctx context.Context, in *FriendPutInHandleReq, opts ...grpc.CallOption) (*FriendPutInHandleResp, error)
	FriendPutInRead(ctx context.Context, in *FriendPutInReadReq, opts ...grpc.CallOption) (*FriendPutInReadResp, error)
	FriendPutInDelete(ctx context.Context, in *FriendPutInDeleteReq, opts ...grpc.CallOption) (*FriendPutInDeleteResp, error)
	FriendPutInList(ctx context.Context, in *FriendPutInListReq, opts ...grpc.CallOption) (*FriendPutInListResp, error)
	FriendPutInMessageCount(ctx context.Context, in *FriendPutInMessageCountReq, opts ...grpc.CallOption) (*FriendPutInMessageCountResp, error)
	FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error)
	FriendUpdateRemark(ctx context.Context, in *FriendUpdateRemarkReq, opts ...grpc.CallOption) (*FriendUpdateRemarkResp, error)
	FriendDelete(ctx context.Context, in *FriendDeleteReq, opts ...grpc.CallOption) (*FriendDeleteResp, error)
	FriendBlock(ctx context.Context, in *FriendBlockReq, opts ...grpc.CallOption) (*FriendBlockResp, error)
	FriendMomentsPermission(ctx context.Context, in *FriendMomentsPermissionReq, opts ...grpc.CallOption) (*FriendMomentsPermissionResp, error)
	FriendNotification(ctx context.Context, in *FriendNotificationReq, opts ...grpc.CallOption) (*FriendNotificationResp, error)
	FriendPin(ctx context.Context, in *FriendPinReq, opts ...grpc.CallOption) (*FriendPinResp, error)
	FriendMute(ctx context.Context, in *FriendMuteReq, opts ...grpc.CallOption) (*FriendMuteResp, error)
	FriendTags(ctx context.Context, in *FriendTagsReq, opts ...grpc.CallOption) (*FriendTagsResp, error)
	FriendReport(ctx context.Context, in *FriendReportReq, opts ...grpc.CallOption) (*FriendReportResp, error)
	FriendShare(ctx context.Context, in *FriendShareReq, opts ...grpc.CallOption) (*FriendShareResp, error)
	// 群业务：创建群，修改群，群公告，申请群，用户群列表，群成员，申请群，群退出..
	// 群要求
	GroupCreate(ctx context.Context, in *GroupCreateReq, opts ...grpc.CallOption) (*GroupCreateResp, error)
	GroupPutin(ctx context.Context, in *GroupPutinReq, opts ...grpc.CallOption) (*GroupPutinResp, error)
	GroupPutinList(ctx context.Context, in *GroupPutinListReq, opts ...grpc.CallOption) (*GroupPutinListResp, error)
	GetGroupPutListByUid(ctx context.Context, in *GetGroupPutListByUidReq, opts ...grpc.CallOption) (*GroupPutinListResp, error)
	MarkGroupReqRead(ctx context.Context, in *MarkGroupReqReadReq, opts ...grpc.CallOption) (*MarkGroupReqReadResp, error)
	GroupPutInHandle(ctx context.Context, in *GroupPutInHandleReq, opts ...grpc.CallOption) (*GroupPutInHandleResp, error)
	GroupList(ctx context.Context, in *GroupListReq, opts ...grpc.CallOption) (*GroupListResp, error)
	GroupUsers(ctx context.Context, in *GroupUsersReq, opts ...grpc.CallOption) (*GroupUsersResp, error)
	FindGroupList(ctx context.Context, in *FindGroupListReq, opts ...grpc.CallOption) (*FindGroupListResp, error)
	GroupSearch(ctx context.Context, in *GroupSearchReq, opts ...grpc.CallOption) (*GroupSearchResp, error)
	GroupQuit(ctx context.Context, in *GroupQuitReq, opts ...grpc.CallOption) (*GroupQuitResp, error)
	GroupKick(ctx context.Context, in *GroupKickReq, opts ...grpc.CallOption) (*GroupKickResp, error)
	GroupUpdate(ctx context.Context, in *GroupUpdateReq, opts ...grpc.CallOption) (*GroupUpdateResp, error)
	GroupDetail(ctx context.Context, in *GroupDetailReq, opts ...grpc.CallOption) (*GroupDetailResp, error)
	GroupDisband(ctx context.Context, in *GroupDisbandReq, opts ...grpc.CallOption) (*GroupDisbandResp, error)
	GroupTransferOwner(ctx context.Context, in *GroupTransferOwnerReq, opts ...grpc.CallOption) (*GroupTransferOwnerResp, error)
	GroupSetAdmin(ctx context.Context, in *GroupSetAdminReq, opts ...grpc.CallOption) (*GroupSetAdminResp, error)
	GroupInvite(ctx context.Context, in *GroupInviteReq, opts ...grpc.CallOption) (*GroupInviteResp, error)
	// 邀请链接/二维码入群
	GroupInviteLinkCreate(ctx context.Context, in *GroupInviteLinkCreateReq, opts ...grpc.CallOption) (*GroupInviteLinkCreateResp, error)
	GroupInviteLinkList(ctx context.Context, in *GroupInviteLinkListReq, opts ...grpc.CallOption) (*GroupInviteLinkListResp, error)
	GroupInviteLinkRevoke(ctx context.Context, in *GroupInviteLinkRevokeReq, opts ...grpc.CallOption) (*GroupInviteLinkRevokeResp, error)
	GroupJoinByToken(ctx context.Context, in *GroupJoinByTokenReq, opts ...grpc.CallOption) (*GroupJoinByTokenResp, error)
	// 群成员资料（群内昵称/群备注/@列表）
	GetMyGroupMemberSetting(ctx context.Context, in *GetMyGroupMemberSettingReq, opts ...grpc.CallOption) (*GetMyGroupMemberSettingResp, error)
	UpdateMyGroupMemberSetting(ctx context.Context, in *UpdateMyGroupMemberSettingReq, opts ...grpc.CallOption) (*UpdateMyGroupMemberSettingResp, error)
	GroupAtList(ctx context.Context, in *GroupAtListReq, opts ...grpc.CallOption) (*GroupAtListResp, error)
	GetMemberRole(ctx context.Context, in *GetMemberRoleReq, opts ...grpc.CallOption) (*GetMemberRoleResp, error)
	// 公告历史/置顶
	GroupAnnouncementCreate(ctx context.Context, in *GroupAnnouncementCreateReq, opts ...grpc.CallOption) (*GroupAnnouncementCreateResp, error)
	GroupAnnouncementList(ctx context.Context, in *GroupAnnouncementListReq, opts ...grpc.CallOption) (*GroupAnnouncementListResp, error)
	GroupAnnouncementPin(ctx context.Context, in *GroupAnnouncementPinReq, opts ...grpc.CallOption) (*GroupAnnouncementPinResp, error)
	GroupInvitationCreate(ctx context.Context, in *GroupInvitationCreateReq, opts ...grpc.CallOption) (*GroupInvitationCreateResp, error)
	GroupInvitationList(ctx context.Context, in *GroupInvitationListReq, opts ...grpc.CallOption) (*GroupInvitationListResp, error)
	GroupInvitationRead(ctx context.Context, in *GroupInvitationReadReq, opts ...grpc.CallOption) (*GroupInvitationReadResp, error)
	GroupRequestMessageCount(ctx context.Context, in *GroupRequestMessageCountReq, opts ...grpc.CallOption) (*GroupRequestMessageCountResp, error)
	GroupInvitationHandle(ctx context.Context, in *GroupInvitationHandleReq, opts ...grpc.CallOption) (*GroupInvitationHandleResp, error)
	ExpireGroupInvitations(ctx context.Context, in *ExpireGroupInvitationsReq, opts ...grpc.CallOption) (*ExpireGroupInvitationsResp, error)
}

type socialClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialClient(cc grpc.ClientConnInterface) SocialClient {
	return &socialClient{cc}
}

func (c *socialClient) FriendPutIn(ctx context.Context, in *FriendPutInReq, opts ...grpc.CallOption) (*FriendPutInResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendPutInResp)
	err := c.cc.Invoke(ctx, Social_FriendPutIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FriendPutInHandle(ctx context.Context, in *FriendPutInHandleReq, opts ...grpc.CallOption) (*FriendPutInHandleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendPutInHandleResp)
	err := c.cc.Invoke(ctx, Social_FriendPutInHandle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FriendPutInRead(ctx context.Context, in *FriendPutInReadReq, opts ...grpc.CallOption) (*FriendPutInReadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendPutInReadResp)
	err := c.cc.Invoke(ctx, Social_FriendPutInRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FriendPutInDelete(ctx context.Context, in *FriendPutInDeleteReq, opts ...grpc.CallOption) (*FriendPutInDeleteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendPutInDeleteResp)
	err := c.cc.Invoke(ctx, Social_FriendPutInDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FriendPutInList(ctx context.Context, in *FriendPutInListReq, opts ...grpc.CallOption) (*FriendPutInListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendPutInListResp)
	err := c.cc.Invoke(ctx, Social_FriendPutInList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FriendPutInMessageCount(ctx context.Context, in *FriendPutInMessageCountReq, opts ...grpc.CallOption) (*FriendPutInMessageCountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendPutInMessageCountResp)
	err := c.cc.Invoke(ctx, Social_FriendPutInMessageCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendListResp)
	err := c.cc.Invoke(ctx, Social_FriendList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FriendUpdateRemark(ctx context.Context, in *FriendUpdateRemarkReq, opts ...grpc.CallOption) (*FriendUpdateRemarkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendUpdateRemarkResp)
	err := c.cc.Invoke(ctx, Social_FriendUpdateRemark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FriendDelete(ctx context.Context, in *FriendDeleteReq, opts ...grpc.CallOption) (*FriendDeleteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendDeleteResp)
	err := c.cc.Invoke(ctx, Social_FriendDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FriendBlock(ctx context.Context, in *FriendBlockReq, opts ...grpc.CallOption) (*FriendBlockResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendBlockResp)
	err := c.cc.Invoke(ctx, Social_FriendBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FriendMomentsPermission(ctx context.Context, in *FriendMomentsPermissionReq, opts ...grpc.CallOption) (*FriendMomentsPermissionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendMomentsPermissionResp)
	err := c.cc.Invoke(ctx, Social_FriendMomentsPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FriendNotification(ctx context.Context, in *FriendNotificationReq, opts ...grpc.CallOption) (*FriendNotificationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendNotificationResp)
	err := c.cc.Invoke(ctx, Social_FriendNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FriendPin(ctx context.Context, in *FriendPinReq, opts ...grpc.CallOption) (*FriendPinResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendPinResp)
	err := c.cc.Invoke(ctx, Social_FriendPin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FriendMute(ctx context.Context, in *FriendMuteReq, opts ...grpc.CallOption) (*FriendMuteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendMuteResp)
	err := c.cc.Invoke(ctx, Social_FriendMute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FriendTags(ctx context.Context, in *FriendTagsReq, opts ...grpc.CallOption) (*FriendTagsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendTagsResp)
	err := c.cc.Invoke(ctx, Social_FriendTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FriendReport(ctx context.Context, in *FriendReportReq, opts ...grpc.CallOption) (*FriendReportResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendReportResp)
	err := c.cc.Invoke(ctx, Social_FriendReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FriendShare(ctx context.Context, in *FriendShareReq, opts ...grpc.CallOption) (*FriendShareResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendShareResp)
	err := c.cc.Invoke(ctx, Social_FriendShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupCreate(ctx context.Context, in *GroupCreateReq, opts ...grpc.CallOption) (*GroupCreateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupCreateResp)
	err := c.cc.Invoke(ctx, Social_GroupCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupPutin(ctx context.Context, in *GroupPutinReq, opts ...grpc.CallOption) (*GroupPutinResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupPutinResp)
	err := c.cc.Invoke(ctx, Social_GroupPutin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupPutinList(ctx context.Context, in *GroupPutinListReq, opts ...grpc.CallOption) (*GroupPutinListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupPutinListResp)
	err := c.cc.Invoke(ctx, Social_GroupPutinList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetGroupPutListByUid(ctx context.Context, in *GetGroupPutListByUidReq, opts ...grpc.CallOption) (*GroupPutinListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupPutinListResp)
	err := c.cc.Invoke(ctx, Social_GetGroupPutListByUid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) MarkGroupReqRead(ctx context.Context, in *MarkGroupReqReadReq, opts ...grpc.CallOption) (*MarkGroupReqReadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkGroupReqReadResp)
	err := c.cc.Invoke(ctx, Social_MarkGroupReqRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupPutInHandle(ctx context.Context, in *GroupPutInHandleReq, opts ...grpc.CallOption) (*GroupPutInHandleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupPutInHandleResp)
	err := c.cc.Invoke(ctx, Social_GroupPutInHandle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupList(ctx context.Context, in *GroupListReq, opts ...grpc.CallOption) (*GroupListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupListResp)
	err := c.cc.Invoke(ctx, Social_GroupList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupUsers(ctx context.Context, in *GroupUsersReq, opts ...grpc.CallOption) (*GroupUsersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupUsersResp)
	err := c.cc.Invoke(ctx, Social_GroupUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FindGroupList(ctx context.Context, in *FindGroupListReq, opts ...grpc.CallOption) (*FindGroupListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindGroupListResp)
	err := c.cc.Invoke(ctx, Social_FindGroupList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupSearch(ctx context.Context, in *GroupSearchReq, opts ...grpc.CallOption) (*GroupSearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupSearchResp)
	err := c.cc.Invoke(ctx, Social_GroupSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupQuit(ctx context.Context, in *GroupQuitReq, opts ...grpc.CallOption) (*GroupQuitResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupQuitResp)
	err := c.cc.Invoke(ctx, Social_GroupQuit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupKick(ctx context.Context, in *GroupKickReq, opts ...grpc.CallOption) (*GroupKickResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupKickResp)
	err := c.cc.Invoke(ctx, Social_GroupKick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupUpdate(ctx context.Context, in *GroupUpdateReq, opts ...grpc.CallOption) (*GroupUpdateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupUpdateResp)
	err := c.cc.Invoke(ctx, Social_GroupUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupDetail(ctx context.Context, in *GroupDetailReq, opts ...grpc.CallOption) (*GroupDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupDetailResp)
	err := c.cc.Invoke(ctx, Social_GroupDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupDisband(ctx context.Context, in *GroupDisbandReq, opts ...grpc.CallOption) (*GroupDisbandResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupDisbandResp)
	err := c.cc.Invoke(ctx, Social_GroupDisband_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupTransferOwner(ctx context.Context, in *GroupTransferOwnerReq, opts ...grpc.CallOption) (*GroupTransferOwnerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupTransferOwnerResp)
	err := c.cc.Invoke(ctx, Social_GroupTransferOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupSetAdmin(ctx context.Context, in *GroupSetAdminReq, opts ...grpc.CallOption) (*GroupSetAdminResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupSetAdminResp)
	err := c.cc.Invoke(ctx, Social_GroupSetAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupInvite(ctx context.Context, in *GroupInviteReq, opts ...grpc.CallOption) (*GroupInviteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupInviteResp)
	err := c.cc.Invoke(ctx, Social_GroupInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupInviteLinkCreate(ctx context.Context, in *GroupInviteLinkCreateReq, opts ...grpc.CallOption) (*GroupInviteLinkCreateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupInviteLinkCreateResp)
	err := c.cc.Invoke(ctx, Social_GroupInviteLinkCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupInviteLinkList(ctx context.Context, in *GroupInviteLinkListReq, opts ...grpc.CallOption) (*GroupInviteLinkListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupInviteLinkListResp)
	err := c.cc.Invoke(ctx, Social_GroupInviteLinkList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupInviteLinkRevoke(ctx context.Context, in *GroupInviteLinkRevokeReq, opts ...grpc.CallOption) (*GroupInviteLinkRevokeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupInviteLinkRevokeResp)
	err := c.cc.Invoke(ctx, Social_GroupInviteLinkRevoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupJoinByToken(ctx context.Context, in *GroupJoinByTokenReq, opts ...grpc.CallOption) (*GroupJoinByTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupJoinByTokenResp)
	err := c.cc.Invoke(ctx, Social_GroupJoinByToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetMyGroupMemberSetting(ctx context.Context, in *GetMyGroupMemberSettingReq, opts ...grpc.CallOption) (*GetMyGroupMemberSettingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyGroupMemberSettingResp)
	err := c.cc.Invoke(ctx, Social_GetMyGroupMemberSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) UpdateMyGroupMemberSetting(ctx context.Context, in *UpdateMyGroupMemberSettingReq, opts ...grpc.CallOption) (*UpdateMyGroupMemberSettingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMyGroupMemberSettingResp)
	err := c.cc.Invoke(ctx, Social_UpdateMyGroupMemberSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupAtList(ctx context.Context, in *GroupAtListReq, opts ...grpc.CallOption) (*GroupAtListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupAtListResp)
	err := c.cc.Invoke(ctx, Social_GroupAtList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetMemberRole(ctx context.Context, in *GetMemberRoleReq, opts ...grpc.CallOption) (*GetMemberRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemberRoleResp)
	err := c.cc.Invoke(ctx, Social_GetMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupAnnouncementCreate(ctx context.Context, in *GroupAnnouncementCreateReq, opts ...grpc.CallOption) (*GroupAnnouncementCreateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupAnnouncementCreateResp)
	err := c.cc.Invoke(ctx, Social_GroupAnnouncementCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupAnnouncementList(ctx context.Context, in *GroupAnnouncementListReq, opts ...grpc.CallOption) (*GroupAnnouncementListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupAnnouncementListResp)
	err := c.cc.Invoke(ctx, Social_GroupAnnouncementList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupAnnouncementPin(ctx context.Context, in *GroupAnnouncementPinReq, opts ...grpc.CallOption) (*GroupAnnouncementPinResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupAnnouncementPinResp)
	err := c.cc.Invoke(ctx, Social_GroupAnnouncementPin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupInvitationCreate(ctx context.Context, in *GroupInvitationCreateReq, opts ...grpc.CallOption) (*GroupInvitationCreateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupInvitationCreateResp)
	err := c.cc.Invoke(ctx, Social_GroupInvitationCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupInvitationList(ctx context.Context, in *GroupInvitationListReq, opts ...grpc.CallOption) (*GroupInvitationListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupInvitationListResp)
	err := c.cc.Invoke(ctx, Social_GroupInvitationList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupInvitationRead(ctx context.Context, in *GroupInvitationReadReq, opts ...grpc.CallOption) (*GroupInvitationReadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupInvitationReadResp)
	err := c.cc.Invoke(ctx, Social_GroupInvitationRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupRequestMessageCount(ctx context.Context, in *GroupRequestMessageCountReq, opts ...grpc.CallOption) (*GroupRequestMessageCountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupRequestMessageCountResp)
	err := c.cc.Invoke(ctx, Social_GroupRequestMessageCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GroupInvitationHandle(ctx context.Context, in *GroupInvitationHandleReq, opts ...grpc.CallOption) (*GroupInvitationHandleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupInvitationHandleResp)
	err := c.cc.Invoke(ctx, Social_GroupInvitationHandle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) ExpireGroupInvitations(ctx context.Context, in *ExpireGroupInvitationsReq, opts ...grpc.CallOption) (*ExpireGroupInvitationsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpireGroupInvitationsResp)
	err := c.cc.Invoke(ctx, Social_ExpireGroupInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialServer is the server API for Social service.
// All implementations must embed UnimplementedSocialServer
// for forward compatibility.
//
// svc
type SocialServer interface {
	// 好友业务：请求好友、通过或拒绝申请、好友列表
	FriendPutIn(context.Context, *FriendPutInReq) (*FriendPutInResp, error)
	FriendPutInHandle(context.Context, *FriendPutInHandleReq) (*FriendPutInHandleResp, error)
	FriendPutInRead(context.Context, *FriendPutInReadReq) (*FriendPutInReadResp, error)
	FriendPutInDelete(context.Context, *FriendPutInDeleteReq) (*FriendPutInDeleteResp, error)
	FriendPutInList(context.Context, *FriendPutInListReq) (*FriendPutInListResp, error)
	FriendPutInMessageCount(context.Context, *FriendPutInMessageCountReq) (*FriendPutInMessageCountResp, error)
	FriendList(context.Context, *FriendListReq) (*FriendListResp, error)
	FriendUpdateRemark(context.Context, *FriendUpdateRemarkReq) (*FriendUpdateRemarkResp, error)
	FriendDelete(context.Context, *FriendDeleteReq) (*FriendDeleteResp, error)
	FriendBlock(context.Context, *FriendBlockReq) (*FriendBlockResp, error)
	FriendMomentsPermission(context.Context, *FriendMomentsPermissionReq) (*FriendMomentsPermissionResp, error)
	FriendNotification(context.Context, *FriendNotificationReq) (*FriendNotificationResp, error)
	FriendPin(context.Context, *FriendPinReq) (*FriendPinResp, error)
	FriendMute(context.Context, *FriendMuteReq) (*FriendMuteResp, error)
	FriendTags(context.Context, *FriendTagsReq) (*FriendTagsResp, error)
	FriendReport(context.Context, *FriendReportReq) (*FriendReportResp, error)
	FriendShare(context.Context, *FriendShareReq) (*FriendShareResp, error)
	// 群业务：创建群，修改群，群公告，申请群，用户群列表，群成员，申请群，群退出..
	// 群要求
	GroupCreate(context.Context, *GroupCreateReq) (*GroupCreateResp, error)
	GroupPutin(context.Context, *GroupPutinReq) (*GroupPutinResp, error)
	GroupPutinList(context.Context, *GroupPutinListReq) (*GroupPutinListResp, error)
	GetGroupPutListByUid(context.Context, *GetGroupPutListByUidReq) (*GroupPutinListResp, error)
	MarkGroupReqRead(context.Context, *MarkGroupReqReadReq) (*MarkGroupReqReadResp, error)
	GroupPutInHandle(context.Context, *GroupPutInHandleReq) (*GroupPutInHandleResp, error)
	GroupList(context.Context, *GroupListReq) (*GroupListResp, error)
	GroupUsers(context.Context, *GroupUsersReq) (*GroupUsersResp, error)
	FindGroupList(context.Context, *FindGroupListReq) (*FindGroupListResp, error)
	GroupSearch(context.Context, *GroupSearchReq) (*GroupSearchResp, error)
	GroupQuit(context.Context, *GroupQuitReq) (*GroupQuitResp, error)
	GroupKick(context.Context, *GroupKickReq) (*GroupKickResp, error)
	GroupUpdate(context.Context, *GroupUpdateReq) (*GroupUpdateResp, error)
	GroupDetail(context.Context, *GroupDetailReq) (*GroupDetailResp, error)
	GroupDisband(context.Context, *GroupDisbandReq) (*GroupDisbandResp, error)
	GroupTransferOwner(context.Context, *GroupTransferOwnerReq) (*GroupTransferOwnerResp, error)
	GroupSetAdmin(context.Context, *GroupSetAdminReq) (*GroupSetAdminResp, error)
	GroupInvite(context.Context, *GroupInviteReq) (*GroupInviteResp, error)
	// 邀请链接/二维码入群
	GroupInviteLinkCreate(context.Context, *GroupInviteLinkCreateReq) (*GroupInviteLinkCreateResp, error)
	GroupInviteLinkList(context.Context, *GroupInviteLinkListReq) (*GroupInviteLinkListResp, error)
	GroupInviteLinkRevoke(context.Context, *GroupInviteLinkRevokeReq) (*GroupInviteLinkRevokeResp, error)
	GroupJoinByToken(context.Context, *GroupJoinByTokenReq) (*GroupJoinByTokenResp, error)
	// 群成员资料（群内昵称/群备注/@列表）
	GetMyGroupMemberSetting(context.Context, *GetMyGroupMemberSettingReq) (*GetMyGroupMemberSettingResp, error)
	UpdateMyGroupMemberSetting(context.Context, *UpdateMyGroupMemberSettingReq) (*UpdateMyGroupMemberSettingResp, error)
	GroupAtList(context.Context, *GroupAtListReq) (*GroupAtListResp, error)
	GetMemberRole(context.Context, *GetMemberRoleReq) (*GetMemberRoleResp, error)
	// 公告历史/置顶
	GroupAnnouncementCreate(context.Context, *GroupAnnouncementCreateReq) (*GroupAnnouncementCreateResp, error)
	GroupAnnouncementList(context.Context, *GroupAnnouncementListReq) (*GroupAnnouncementListResp, error)
	GroupAnnouncementPin(context.Context, *GroupAnnouncementPinReq) (*GroupAnnouncementPinResp, error)
	GroupInvitationCreate(context.Context, *GroupInvitationCreateReq) (*GroupInvitationCreateResp, error)
	GroupInvitationList(context.Context, *GroupInvitationListReq) (*GroupInvitationListResp, error)
	GroupInvitationRead(context.Context, *GroupInvitationReadReq) (*GroupInvitationReadResp, error)
	GroupRequestMessageCount(context.Context, *GroupRequestMessageCountReq) (*GroupRequestMessageCountResp, error)
	GroupInvitationHandle(context.Context, *GroupInvitationHandleReq) (*GroupInvitationHandleResp, error)
	ExpireGroupInvitations(context.Context, *ExpireGroupInvitationsReq) (*ExpireGroupInvitationsResp, error)
	mustEmbedUnimplementedSocialServer()
}

// UnimplementedSocialServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocialServer struct{}

func (UnimplementedSocialServer) FriendPutIn(context.Context, *FriendPutInReq) (*FriendPutInResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendPutIn not implemented")
}
func (UnimplementedSocialServer) FriendPutInHandle(context.Context, *FriendPutInHandleReq) (*FriendPutInHandleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendPutInHandle not implemented")
}
func (UnimplementedSocialServer) FriendPutInRead(context.Context, *FriendPutInReadReq) (*FriendPutInReadResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendPutInRead not implemented")
}
func (UnimplementedSocialServer) FriendPutInDelete(context.Context, *FriendPutInDeleteReq) (*FriendPutInDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendPutInDelete not implemented")
}
func (UnimplementedSocialServer) FriendPutInList(context.Context, *FriendPutInListReq) (*FriendPutInListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendPutInList not implemented")
}
func (UnimplementedSocialServer) FriendPutInMessageCount(context.Context, *FriendPutInMessageCountReq) (*FriendPutInMessageCountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendPutInMessageCount not implemented")
}
func (UnimplementedSocialServer) FriendList(context.Context, *FriendListReq) (*FriendListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendList not implemented")
}
func (UnimplementedSocialServer) FriendUpdateRemark(context.Context, *FriendUpdateRemarkReq) (*FriendUpdateRemarkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendUpdateRemark not implemented")
}
func (UnimplementedSocialServer) FriendDelete(context.Context, *FriendDeleteReq) (*FriendDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendDelete not implemented")
}
func (UnimplementedSocialServer) FriendBlock(context.Context, *FriendBlockReq) (*FriendBlockResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendBlock not implemented")
}
func (UnimplementedSocialServer) FriendMomentsPermission(context.Context, *FriendMomentsPermissionReq) (*FriendMomentsPermissionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendMomentsPermission not implemented")
}
func (UnimplementedSocialServer) FriendNotification(context.Context, *FriendNotificationReq) (*FriendNotificationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendNotification not implemented")
}
func (UnimplementedSocialServer) FriendPin(context.Context, *FriendPinReq) (*FriendPinResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendPin not implemented")
}
func (UnimplementedSocialServer) FriendMute(context.Context, *FriendMuteReq) (*FriendMuteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendMute not implemented")
}
func (UnimplementedSocialServer) FriendTags(context.Context, *FriendTagsReq) (*FriendTagsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendTags not implemented")
}
func (UnimplementedSocialServer) FriendReport(context.Context, *FriendReportReq) (*FriendReportResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendReport not implemented")
}
func (UnimplementedSocialServer) FriendShare(context.Context, *FriendShareReq) (*FriendShareResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendShare not implemented")
}
func (UnimplementedSocialServer) GroupCreate(context.Context, *GroupCreateReq) (*GroupCreateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupCreate not implemented")
}
func (UnimplementedSocialServer) GroupPutin(context.Context, *GroupPutinReq) (*GroupPutinResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupPutin not implemented")
}
func (UnimplementedSocialServer) GroupPutinList(context.Context, *GroupPutinListReq) (*GroupPutinListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupPutinList not implemented")
}
func (UnimplementedSocialServer) GetGroupPutListByUid(context.Context, *GetGroupPutListByUidReq) (*GroupPutinListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupPutListByUid not implemented")
}
func (UnimplementedSocialServer) MarkGroupReqRead(context.Context, *MarkGroupReqReadReq) (*MarkGroupReqReadResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkGroupReqRead not implemented")
}
func (UnimplementedSocialServer) GroupPutInHandle(context.Context, *GroupPutInHandleReq) (*GroupPutInHandleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupPutInHandle not implemented")
}
func (UnimplementedSocialServer) GroupList(context.Context, *GroupListReq) (*GroupListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupList not implemented")
}
func (UnimplementedSocialServer) GroupUsers(context.Context, *GroupUsersReq) (*GroupUsersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupUsers not implemented")
}
func (UnimplementedSocialServer) FindGroupList(context.Context, *FindGroupListReq) (*FindGroupListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindGroupList not implemented")
}
func (UnimplementedSocialServer) GroupSearch(context.Context, *GroupSearchReq) (*GroupSearchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupSearch not implemented")
}
func (UnimplementedSocialServer) GroupQuit(context.Context, *GroupQuitReq) (*GroupQuitResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupQuit not implemented")
}
func (UnimplementedSocialServer) GroupKick(context.Context, *GroupKickReq) (*GroupKickResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupKick not implemented")
}
func (UnimplementedSocialServer) GroupUpdate(context.Context, *GroupUpdateReq) (*GroupUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupUpdate not implemented")
}
func (UnimplementedSocialServer) GroupDetail(context.Context, *GroupDetailReq) (*GroupDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupDetail not implemented")
}
func (UnimplementedSocialServer) GroupDisband(context.Context, *GroupDisbandReq) (*GroupDisbandResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupDisband not implemented")
}
func (UnimplementedSocialServer) GroupTransferOwner(context.Context, *GroupTransferOwnerReq) (*GroupTransferOwnerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupTransferOwner not implemented")
}
func (UnimplementedSocialServer) GroupSetAdmin(context.Context, *GroupSetAdminReq) (*GroupSetAdminResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupSetAdmin not implemented")
}
func (UnimplementedSocialServer) GroupInvite(context.Context, *GroupInviteReq) (*GroupInviteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupInvite not implemented")
}
func (UnimplementedSocialServer) GroupInviteLinkCreate(context.Context, *GroupInviteLinkCreateReq) (*GroupInviteLinkCreateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupInviteLinkCreate not implemented")
}
func (UnimplementedSocialServer) GroupInviteLinkList(context.Context, *GroupInviteLinkListReq) (*GroupInviteLinkListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupInviteLinkList not implemented")
}
func (UnimplementedSocialServer) GroupInviteLinkRevoke(context.Context, *GroupInviteLinkRevokeReq) (*GroupInviteLinkRevokeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupInviteLinkRevoke not implemented")
}
func (UnimplementedSocialServer) GroupJoinByToken(context.Context, *GroupJoinByTokenReq) (*GroupJoinByTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupJoinByToken not implemented")
}
func (UnimplementedSocialServer) GetMyGroupMemberSetting(context.Context, *GetMyGroupMemberSettingReq) (*GetMyGroupMemberSettingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyGroupMemberSetting not implemented")
}
func (UnimplementedSocialServer) UpdateMyGroupMemberSetting(context.Context, *UpdateMyGroupMemberSettingReq) (*UpdateMyGroupMemberSettingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMyGroupMemberSetting not implemented")
}
func (UnimplementedSocialServer) GroupAtList(context.Context, *GroupAtListReq) (*GroupAtListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupAtList not implemented")
}
func (UnimplementedSocialServer) GetMemberRole(context.Context, *GetMemberRoleReq) (*GetMemberRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemberRole not implemented")
}
func (UnimplementedSocialServer) GroupAnnouncementCreate(context.Context, *GroupAnnouncementCreateReq) (*GroupAnnouncementCreateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupAnnouncementCreate not implemented")
}
func (UnimplementedSocialServer) GroupAnnouncementList(context.Context, *GroupAnnouncementListReq) (*GroupAnnouncementListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupAnnouncementList not implemented")
}
func (UnimplementedSocialServer) GroupAnnouncementPin(context.Context, *GroupAnnouncementPinReq) (*GroupAnnouncementPinResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupAnnouncementPin not implemented")
}
func (UnimplementedSocialServer) GroupInvitationCreate(context.Context, *GroupInvitationCreateReq) (*GroupInvitationCreateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupInvitationCreate not implemented")
}
func (UnimplementedSocialServer) GroupInvitationList(context.Context, *GroupInvitationListReq) (*GroupInvitationListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupInvitationList not implemented")
}
func (UnimplementedSocialServer) GroupInvitationRead(context.Context, *GroupInvitationReadReq) (*GroupInvitationReadResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupInvitationRead not implemented")
}
func (UnimplementedSocialServer) GroupRequestMessageCount(context.Context, *GroupRequestMessageCountReq) (*GroupRequestMessageCountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupRequestMessageCount not implemented")
}
func (UnimplementedSocialServer) GroupInvitationHandle(context.Context, *GroupInvitationHandleReq) (*GroupInvitationHandleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupInvitationHandle not implemented")
}
func (UnimplementedSocialServer) ExpireGroupInvitations(context.Context, *ExpireGroupInvitationsReq) (*ExpireGroupInvitationsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpireGroupInvitations not implemented")
}
func (UnimplementedSocialServer) mustEmbedUnimplementedSocialServer() {}
func (UnimplementedSocialServer) testEmbeddedByValue()                {}

// UnsafeSocialServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialServer will
// result in compilation errors.
type UnsafeSocialServer interface {
	mustEmbedUnimplementedSocialServer()
}

func RegisterSocialServer(s grpc.ServiceRegistrar, srv SocialServer) {
	// If the following call pancis, it indicates UnimplementedSocialServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Social_ServiceDesc, srv)
}

func _Social_FriendPutIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendPutInReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FriendPutIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FriendPutIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FriendPutIn(ctx, req.(*FriendPutInReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FriendPutInHandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendPutInHandleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FriendPutInHandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FriendPutInHandle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FriendPutInHandle(ctx, req.(*FriendPutInHandleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FriendPutInRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendPutInReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FriendPutInRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FriendPutInRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FriendPutInRead(ctx, req.(*FriendPutInReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FriendPutInDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendPutInDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FriendPutInDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FriendPutInDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FriendPutInDelete(ctx, req.(*FriendPutInDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FriendPutInList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendPutInListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FriendPutInList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FriendPutInList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FriendPutInList(ctx, req.(*FriendPutInListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FriendPutInMessageCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendPutInMessageCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FriendPutInMessageCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FriendPutInMessageCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FriendPutInMessageCount(ctx, req.(*FriendPutInMessageCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FriendList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FriendList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FriendList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FriendList(ctx, req.(*FriendListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FriendUpdateRemark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendUpdateRemarkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FriendUpdateRemark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FriendUpdateRemark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FriendUpdateRemark(ctx, req.(*FriendUpdateRemarkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FriendDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FriendDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FriendDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FriendDelete(ctx, req.(*FriendDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FriendBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendBlockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FriendBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FriendBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FriendBlock(ctx, req.(*FriendBlockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FriendMomentsPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendMomentsPermissionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FriendMomentsPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FriendMomentsPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FriendMomentsPermission(ctx, req.(*FriendMomentsPermissionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FriendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendNotificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FriendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FriendNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FriendNotification(ctx, req.(*FriendNotificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FriendPin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendPinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FriendPin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FriendPin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FriendPin(ctx, req.(*FriendPinReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FriendMute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendMuteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FriendMute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FriendMute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FriendMute(ctx, req.(*FriendMuteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FriendTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendTagsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FriendTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FriendTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FriendTags(ctx, req.(*FriendTagsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FriendReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendReportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FriendReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FriendReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FriendReport(ctx, req.(*FriendReportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FriendShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendShareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FriendShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FriendShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FriendShare(ctx, req.(*FriendShareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupCreate(ctx, req.(*GroupCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupPutin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupPutinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupPutin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupPutin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupPutin(ctx, req.(*GroupPutinReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupPutinList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupPutinListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupPutinList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupPutinList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupPutinList(ctx, req.(*GroupPutinListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetGroupPutListByUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupPutListByUidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetGroupPutListByUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GetGroupPutListByUid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetGroupPutListByUid(ctx, req.(*GetGroupPutListByUidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_MarkGroupReqRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkGroupReqReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).MarkGroupReqRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_MarkGroupReqRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).MarkGroupReqRead(ctx, req.(*MarkGroupReqReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupPutInHandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupPutInHandleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupPutInHandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupPutInHandle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupPutInHandle(ctx, req.(*GroupPutInHandleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupList(ctx, req.(*GroupListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupUsers(ctx, req.(*GroupUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FindGroupList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindGroupListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FindGroupList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FindGroupList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FindGroupList(ctx, req.(*FindGroupListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupSearch(ctx, req.(*GroupSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupQuit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupQuitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupQuit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupQuit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupQuit(ctx, req.(*GroupQuitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupKick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupKickReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupKick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupKick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupKick(ctx, req.(*GroupKickReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupUpdate(ctx, req.(*GroupUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupDetail(ctx, req.(*GroupDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupDisband_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupDisbandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupDisband(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupDisband_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupDisband(ctx, req.(*GroupDisbandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupTransferOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupTransferOwnerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupTransferOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupTransferOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupTransferOwner(ctx, req.(*GroupTransferOwnerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupSetAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupSetAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupSetAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupSetAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupSetAdmin(ctx, req.(*GroupSetAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupInviteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupInvite(ctx, req.(*GroupInviteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupInviteLinkCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupInviteLinkCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupInviteLinkCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupInviteLinkCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupInviteLinkCreate(ctx, req.(*GroupInviteLinkCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupInviteLinkList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupInviteLinkListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupInviteLinkList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupInviteLinkList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupInviteLinkList(ctx, req.(*GroupInviteLinkListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupInviteLinkRevoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupInviteLinkRevokeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupInviteLinkRevoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupInviteLinkRevoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupInviteLinkRevoke(ctx, req.(*GroupInviteLinkRevokeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupJoinByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupJoinByTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupJoinByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupJoinByToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupJoinByToken(ctx, req.(*GroupJoinByTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetMyGroupMemberSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyGroupMemberSettingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetMyGroupMemberSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GetMyGroupMemberSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetMyGroupMemberSetting(ctx, req.(*GetMyGroupMemberSettingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_UpdateMyGroupMemberSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMyGroupMemberSettingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).UpdateMyGroupMemberSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_UpdateMyGroupMemberSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).UpdateMyGroupMemberSetting(ctx, req.(*UpdateMyGroupMemberSettingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupAtList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupAtListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupAtList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupAtList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupAtList(ctx, req.(*GroupAtListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GetMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetMemberRole(ctx, req.(*GetMemberRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupAnnouncementCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupAnnouncementCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupAnnouncementCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupAnnouncementCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupAnnouncementCreate(ctx, req.(*GroupAnnouncementCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupAnnouncementList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupAnnouncementListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupAnnouncementList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupAnnouncementList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupAnnouncementList(ctx, req.(*GroupAnnouncementListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupAnnouncementPin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupAnnouncementPinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupAnnouncementPin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupAnnouncementPin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupAnnouncementPin(ctx, req.(*GroupAnnouncementPinReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupInvitationCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupInvitationCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupInvitationCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupInvitationCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupInvitationCreate(ctx, req.(*GroupInvitationCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupInvitationList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupInvitationListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupInvitationList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupInvitationList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupInvitationList(ctx, req.(*GroupInvitationListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupInvitationRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupInvitationReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupInvitationRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupInvitationRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupInvitationRead(ctx, req.(*GroupInvitationReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupRequestMessageCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRequestMessageCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupRequestMessageCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupRequestMessageCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupRequestMessageCount(ctx, req.(*GroupRequestMessageCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GroupInvitationHandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupInvitationHandleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GroupInvitationHandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GroupInvitationHandle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GroupInvitationHandle(ctx, req.(*GroupInvitationHandleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_ExpireGroupInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpireGroupInvitationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).ExpireGroupInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_ExpireGroupInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).ExpireGroupInvitations(ctx, req.(*ExpireGroupInvitationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Social_ServiceDesc is the grpc.ServiceDesc for Social service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Social_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.social",
	HandlerType: (*SocialServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FriendPutIn",
			Handler:    _Social_FriendPutIn_Handler,
		},
		{
			MethodName: "FriendPutInHandle",
			Handler:    _Social_FriendPutInHandle_Handler,
		},
		{
			MethodName: "FriendPutInRead",
			Handler:    _Social_FriendPutInRead_Handler,
		},
		{
			MethodName: "FriendPutInDelete",
			Handler:    _Social_FriendPutInDelete_Handler,
		},
		{
			MethodName: "FriendPutInList",
			Handler:    _Social_FriendPutInList_Handler,
		},
		{
			MethodName: "FriendPutInMessageCount",
			Handler:    _Social_FriendPutInMessageCount_Handler,
		},
		{
			MethodName: "FriendList",
			Handler:    _Social_FriendList_Handler,
		},
		{
			MethodName: "FriendUpdateRemark",
			Handler:    _Social_FriendUpdateRemark_Handler,
		},
		{
			MethodName: "FriendDelete",
			Handler:    _Social_FriendDelete_Handler,
		},
		{
			MethodName: "FriendBlock",
			Handler:    _Social_FriendBlock_Handler,
		},
		{
			MethodName: "FriendMomentsPermission",
			Handler:    _Social_FriendMomentsPermission_Handler,
		},
		{
			MethodName: "FriendNotification",
			Handler:    _Social_FriendNotification_Handler,
		},
		{
			MethodName: "FriendPin",
			Handler:    _Social_FriendPin_Handler,
		},
		{
			MethodName: "FriendMute",
			Handler:    _Social_FriendMute_Handler,
		},
		{
			MethodName: "FriendTags",
			Handler:    _Social_FriendTags_Handler,
		},
		{
			MethodName: "FriendReport",
			Handler:    _Social_FriendReport_Handler,
		},
		{
			MethodName: "FriendShare",
			Handler:    _Social_FriendShare_Handler,
		},
		{
			MethodName: "GroupCreate",
			Handler:    _Social_GroupCreate_Handler,
		},
		{
			MethodName: "GroupPutin",
			Handler:    _Social_GroupPutin_Handler,
		},
		{
			MethodName: "GroupPutinList",
			Handler:    _Social_GroupPutinList_Handler,
		},
		{
			MethodName: "GetGroupPutListByUid",
			Handler:    _Social_GetGroupPutListByUid_Handler,
		},
		{
			MethodName: "MarkGroupReqRead",
			Handler:    _Social_MarkGroupReqRead_Handler,
		},
		{
			MethodName: "GroupPutInHandle",
			Handler:    _Social_GroupPutInHandle_Handler,
		},
		{
			MethodName: "GroupList",
			Handler:    _Social_GroupList_Handler,
		},
		{
			MethodName: "GroupUsers",
			Handler:    _Social_GroupUsers_Handler,
		},
		{
			MethodName: "FindGroupList",
			Handler:    _Social_FindGroupList_Handler,
		},
		{
			MethodName: "GroupSearch",
			Handler:    _Social_GroupSearch_Handler,
		},
		{
			MethodName: "GroupQuit",
			Handler:    _Social_GroupQuit_Handler,
		},
		{
			MethodName: "GroupKick",
			Handler:    _Social_GroupKick_Handler,
		},
		{
			MethodName: "GroupUpdate",
			Handler:    _Social_GroupUpdate_Handler,
		},
		{
			MethodName: "GroupDetail",
			Handler:    _Social_GroupDetail_Handler,
		},
		{
			MethodName: "GroupDisband",
			Handler:    _Social_GroupDisband_Handler,
		},
		{
			MethodName: "GroupTransferOwner",
			Handler:    _Social_GroupTransferOwner_Handler,
		},
		{
			MethodName: "GroupSetAdmin",
			Handler:    _Social_GroupSetAdmin_Handler,
		},
		{
			MethodName: "GroupInvite",
			Handler:    _Social_GroupInvite_Handler,
		},
		{
			MethodName: "GroupInviteLinkCreate",
			Handler:    _Social_GroupInviteLinkCreate_Handler,
		},
		{
			MethodName: "GroupInviteLinkList",
			Handler:    _Social_GroupInviteLinkList_Handler,
		},
		{
			MethodName: "GroupInviteLinkRevoke",
			Handler:    _Social_GroupInviteLinkRevoke_Handler,
		},
		{
			MethodName: "GroupJoinByToken",
			Handler:    _Social_GroupJoinByToken_Handler,
		},
		{
			MethodName: "GetMyGroupMemberSetting",
			Handler:    _Social_GetMyGroupMemberSetting_Handler,
		},
		{
			MethodName: "UpdateMyGroupMemberSetting",
			Handler:    _Social_UpdateMyGroupMemberSetting_Handler,
		},
		{
			MethodName: "GroupAtList",
			Handler:    _Social_GroupAtList_Handler,
		},
		{
			MethodName: "GetMemberRole",
			Handler:    _Social_GetMemberRole_Handler,
		},
		{
			MethodName: "GroupAnnouncementCreate",
			Handler:    _Social_GroupAnnouncementCreate_Handler,
		},
		{
			MethodName: "GroupAnnouncementList",
			Handler:    _Social_GroupAnnouncementList_Handler,
		},
		{
			MethodName: "GroupAnnouncementPin",
			Handler:    _Social_GroupAnnouncementPin_Handler,
		},
		{
			MethodName: "GroupInvitationCreate",
			Handler:    _Social_GroupInvitationCreate_Handler,
		},
		{
			MethodName: "GroupInvitationList",
			Handler:    _Social_GroupInvitationList_Handler,
		},
		{
			MethodName: "GroupInvitationRead",
			Handler:    _Social_GroupInvitationRead_Handler,
		},
		{
			MethodName: "GroupRequestMessageCount",
			Handler:    _Social_GroupRequestMessageCount_Handler,
		},
		{
			MethodName: "GroupInvitationHandle",
			Handler:    _Social_GroupInvitationHandle_Handler,
		},
		{
			MethodName: "ExpireGroupInvitations",
			Handler:    _Social_ExpireGroupInvitations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "social.proto",
}
