CREATE TABLE trend (
                       id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '动态ID',
                       userid BIGINT UNSIGNED NOT NULL COMMENT '发表用户ID',
                       type TINYINT UNSIGNED NOT NULL COMMENT '动态类型：1文本，2混合(图片)，3长文，4第三方分享(如B站视频)，5视频，6置顶广告',
                       content TEXT NOT NULL COMMENT '动态内容',
                       position_name VARCHAR(255) DEFAULT '' COMMENT '位置名称',
                       position_point varchar(30) COMMENT '位置信息（使用JSON数组）',
                       reply_count BIGINT UNSIGNED DEFAULT 0 COMMENT '评论数量',
                       agree_count BIGINT UNSIGNED DEFAULT 0 COMMENT '点赞数量',
                       createtime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '原始创建时间',
                       updatetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
                       circle_state BIGINT NOT NULL DEFAULT 1 COMMENT '朋友圈状态：2-不可见，1-可见，0-朋友圈删除',
                       state BIGINT NOT NULL DEFAULT 0 COMMENT '是否删除 0-删除，1-正常',
                       is_ad BIGINT DEFAULT 0 COMMENT '是否广告：0-普通，1-广告',
                       url VARCHAR(255) DEFAULT '' COMMENT '广告/视频链接（类型5使用）',
                       ad_end_time DATETIME DEFAULT NULL COMMENT '广告展示截止时间',
                       open_reply BIGINT DEFAULT 1 COMMENT '是否开启评论：0-关闭，1-开启',
                       is_top BIGINT DEFAULT 0 COMMENT '是否置顶：0-否，1-是',
                       title VARCHAR(255) DEFAULT '' COMMENT '长文标题（类型3使用）',
                       idlist varchar(100) COMMENT '@用户ID列表（使用JSON数组）',
                       pic_arr TEXT COMMENT '图片url或者视频',
                       share_url VARCHAR(255) DEFAULT '' COMMENT '第三方内容URL（类型4使用）',
                       cover VARCHAR(255) DEFAULT '' COMMENT '封面图URL（类型3/5使用）',
                       ip VARCHAR(45) DEFAULT '' COMMENT '发布者IP地址',
                       device VARCHAR(100) DEFAULT '' COMMENT '发布设备标识',

                       PRIMARY KEY (id),
                       INDEX idx_userid_circle (userid, updatetime) COMMENT '用户朋友圈动态索引',
                       INDEX idx_circle_time (createtime) COMMENT '朋友圈时间排序索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='社交动态表（朋友圈）';